#theme: minima
remote_theme: jekyll/minima

title: Peter Brown
author: Peter Brown
description: Chess/Arduboy projects

header_pages:
  - about.md

minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/peter-l-brown/" }
    - { platform: github,   user_url: "https://github.com/tiberiusbrown" }
