
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign({},d),ca=(a,b)=>{throw b;},da="object"==typeof window,k="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",t,v,fa,fs,ha,ia;
if(ea)q=k?require("path").dirname(q)+"/":__dirname+"/",ia=()=>{ha||(fs=require("fs"),ha=require("path"))},t=function(a,b){ia();a=ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},fa=a=>{a=t(a,!0);a.buffer||(a=new Uint8Array(a));return a},v=(a,b,c)=>{ia();a=ha.normalize(a);fs.readFile(a,function(e,f){e?c(e):b(f.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!=typeof module&&(module.exports=d),process.on("uncaughtException",function(a){if(!(a instanceof
ja))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ca=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof ja||y("exiting due to exception: "+b);process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(da||k)k?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.send(null);return b.responseText},k&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),v=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var ka=d.print||console.log.bind(console),y=d.printErr||console.warn.bind(console);Object.assign(d,ba);ba=null;d.quit&&(ca=d.quit);var A;
d.wasmBinary&&(A=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;"object"!=typeof WebAssembly&&B("no native wasm support detected");var la,C=!1;
function ma(a,b,c,e,f){function g(r){0!==n&&na(n);return"string"===b?oa(r):"boolean"===b?!!r:r}var h={string:function(r){var u=0;if(null!==r&&void 0!==r&&0!==r){var w=(r.length<<2)+1;u=pa(w);D(r,E,u,w)}return u},array:function(r){var u=pa(r.length);F.set(r,u);return u}};a=d["_"+a];var l=[],n=0;if(e)for(var m=0;m<e.length;m++){var p=h[c[m]];p?(0===n&&(n=qa()),l[m]=p(e[m])):l[m]=e[m]}c=G;e=a.apply(null,l);f=f&&f.async;if(G!=c)return ra().then(g);e=g(e);return f?Promise.resolve(e):e}
var sa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&sa)return sa.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function oa(a){return a?H(E,a,void 0):""}
function D(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(c+3>=e)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}var ua,F,E,va,I,wa,xa=[],ya=[],za=[],Aa=[],Ba=[];function Ca(){var a=d.preRun.shift();xa.unshift(a)}var J=0,Da=null,K=null;function Ea(){J++;d.monitorRunDependencies&&d.monitorRunDependencies(J)}
function Fa(){J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(0==J&&(null!==Da&&(clearInterval(Da),Da=null),K)){var a=K;K=null;a()}}d.preloadedImages={};d.preloadedAudios={};function B(a){if(d.onAbort)d.onAbort(a);a="Aborted("+a+")";y(a);C=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ga(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="ardurogue.wasm";if(!Ga()){var Ha=L;L=d.locateFile?d.locateFile(Ha,q):q+Ha}
function Ia(){var a=L;try{if(a==L&&A)return new Uint8Array(A);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){B(b)}}
function Ja(){if(!A&&(da||k)){if("function"==typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ia()});if(v)return new Promise(function(a,b){v(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ia()})}
var M,Ka,La={6136:function(){N.qa(function(a){!a||B(void 0)})},6179:function(){N.mkdir("/offline");N.L(O,{},"/offline");N.qa(!0,function(){ma("initpers","v")})},6295:function(a,b,c){let e=E.subarray(a,a+b*c*4);a=d.canvas;a.width=innerWidth;a.height=innerHeight;let f=a.getContext("2d");f.imageSmoothingEnabled=!1;let g=document.createElement("canvas"),h=g.getContext("2d");g.width=128;g.height=64;b=h.createImageData(b,c);b.data.set(e);h.putImageData(b,0,0);c=Math.floor(Math.min(a.width/128,a.height/
64));b=128*c;c*=64;f.fillStyle="#000";f.fillRect(0,0,a.width,a.height);f.drawImage(g,Math.floor((a.width-b)/2),Math.floor((a.height-c)/2),b,c)}};function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.hb;"number"==typeof c?void 0===b.Ua&&dynCall_v.call(null,c):c(void 0===b.Ua?null:b.Ua)}}}function Na(a){a instanceof ja||"unwind"==a||ca(1,a)}
function Oa(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Pa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Qa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function P(a){if("/"===a)return"/";a=Pa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Q(a,b){return Pa(a+"/"+b)}
function Ra(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ea)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){B("randomDevice")}}
function T(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:N.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function Sa(a,b){function c(h){for(var l=0;l<h.length&&""===h[l];l++);for(var n=h.length-1;0<=n&&""===h[n];n--);return l>n?[]:h.slice(l,n-l+1)}a=T(a).substr(1);b=T(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],ga:b};N.Ra(a,Va)}
var Va={open:function(a){var b=Ta[a.node.rdev];if(!b)throw new N.G(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ga.flush(a.tty)},flush:function(a){a.tty.ga.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.ga.jb)throw new N.G(60);for(var f=0,g=0;g<e;g++){try{var h=a.tty.ga.jb(a.tty)}catch(l){throw new N.G(29);}if(void 0===h&&0===f)throw new N.G(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.ga.Oa)throw new N.G(60);
try{for(var f=0;f<e;f++)a.tty.ga.Oa(a.tty,b[c+f])}catch(g){throw new N.G(29);}e&&(a.node.timestamp=Date.now());return f}},Xa={jb:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Wa(b)}return a.input.shift()},Oa:function(a,b){null===b||10===b?(ka(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(H(a.output,0)),a.output=[])}},Ya={Oa:function(a,b){null===b||10===b?(y(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(y(H(a.output,0)),a.output=[])}},U={W:null,L:function(){return U.createNode(null,"/",16895,0)},createNode:function(a,
b,c,e){if(N.Nb(c)||N.isFIFO(c))throw new N.G(63);U.W||(U.W={dir:{node:{T:U.H.T,O:U.H.O,lookup:U.H.lookup,Y:U.H.Y,rename:U.H.rename,unlink:U.H.unlink,rmdir:U.H.rmdir,readdir:U.H.readdir,symlink:U.H.symlink},stream:{U:U.J.U}},file:{node:{T:U.H.T,O:U.H.O},stream:{U:U.J.U,read:U.J.read,write:U.J.write,ha:U.J.ha,la:U.J.la,pa:U.J.pa}},link:{node:{T:U.H.T,O:U.H.O,readlink:U.H.readlink},stream:{}},Ya:{node:{T:U.H.T,O:U.H.O},stream:N.wb}});c=N.createNode(a,b,c,e);N.N(c.mode)?(c.H=U.W.dir.node,c.J=U.W.dir.stream,
c.I={}):N.isFile(c.mode)?(c.H=U.W.file.node,c.J=U.W.file.stream,c.M=0,c.I=null):N.ka(c.mode)?(c.H=U.W.link.node,c.J=U.W.link.stream):N.ua(c.mode)&&(c.H=U.W.Ya.node,c.J=U.W.Ya.stream);c.timestamp=Date.now();a&&(a.I[b]=c,a.timestamp=c.timestamp);return c},Kb:function(a){return a.I?a.I.subarray?a.I.subarray(0,a.M):new Uint8Array(a.I):new Uint8Array(0)},eb:function(a,b){var c=a.I?a.I.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.I,a.I=new Uint8Array(b),0<a.M&&a.I.set(c.subarray(0,
a.M),0))},cc:function(a,b){if(a.M!=b)if(0==b)a.I=null,a.M=0;else{var c=a.I;a.I=new Uint8Array(b);c&&a.I.set(c.subarray(0,Math.min(b,a.M)));a.M=b}},H:{T:function(a){var b={};b.dev=N.ua(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N.N(a.mode)?b.size=4096:N.isFile(a.mode)?b.size=a.M:N.ka(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.vb=4096;b.blocks=Math.ceil(b.size/b.vb);return b},
O:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.cc(a,b.size)},lookup:function(){throw N.Da[44];},Y:function(a,b,c,e){return U.createNode(a,b,c,e)},rename:function(a,b,c){if(N.N(a.mode)){try{var e=N.X(b,c)}catch(g){}if(e)for(var f in e.I)throw new N.G(55);}delete a.parent.I[a.name];a.parent.timestamp=Date.now();a.name=c;b.I[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.I[b];a.timestamp=Date.now()},rmdir:function(a,
b){var c=N.X(a,b),e;for(e in c.I)throw new N.G(55);delete a.I[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.I)a.I.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!N.ka(a.mode))throw new N.G(28);return a.link}},J:{read:function(a,b,c,e,f){var g=a.node.I;if(f>=a.node.M)return 0;a=Math.min(a.node.M-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},
write:function(a,b,c,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.I||a.I.subarray)){if(g)return a.I=b.subarray(c,c+e),a.M=e;if(0===a.M&&0===f)return a.I=b.slice(c,c+e),a.M=e;if(f+e<=a.M)return a.I.set(b.subarray(c,c+e),f),e}U.eb(a,f+e);if(a.I.subarray&&b.subarray)a.I.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.I[f+g]=b[c+g];a.M=Math.max(a.M,f+e);return e},U:function(a,b,c){1===c?b+=a.position:2===c&&N.isFile(a.node.mode)&&(b+=a.node.M);if(0>b)throw new N.G(28);return b},
ha:function(a,b,c){U.eb(a.node,b+c);a.node.M=Math.max(a.node.M,b+c)},la:function(a,b,c,e,f,g){if(0!==b)throw new N.G(28);if(!N.isFile(a.node.mode))throw new N.G(43);a=a.node.I;if(g&2||a.buffer!==ua){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;B();c=void 0;if(!c)throw new N.G(48);F.set(a,c)}else e=!1,c=a.byteOffset;return{wc:c,kc:e}},pa:function(a,b,c,e,f){if(!N.isFile(a.node.mode))throw new N.G(43);if(f&2)return 0;U.J.write(a,b,0,e,c,!1);return 0}}};
function Za(a,b,c){var e="al "+a;v(a,function(f){f||B('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&Fa()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ea()}
var O={ab:{},indexedDB:()=>{if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||B("IDBFS used, but indexedDB not supported");return a},ra:21,P:"FILE_DATA",L:function(a){return U.L.apply(null,arguments)},qa:(a,b,c)=>{O.Lb(a,(e,f)=>{if(e)return c(e);O.Mb(a,(g,h)=>{if(g)return c(g);O.$b(b?h:f,b?f:h,c)})})},Ib:(a,b)=>{var c=O.ab[a];if(c)return b(null,c);try{var e=O.indexedDB().open(a,
O.ra)}catch(f){return b(f)}if(!e)return b("Unable to connect to IndexedDB");e.onupgradeneeded=f=>{var g=f.target.result;f=f.target.transaction;var h;g.objectStoreNames.contains(O.P)?h=f.objectStore(O.P):h=g.createObjectStore(O.P);h.indexNames.contains("timestamp")||h.createIndex("timestamp","timestamp",{unique:!1})};e.onsuccess=()=>{c=e.result;O.ab[a]=c;b(null,c)};e.onerror=f=>{b(this.error);f.preventDefault()}},Lb:(a,b)=>{function c(l){return"."!==l&&".."!==l}function e(l){return n=>Q(l,n)}var f=
{};for(a=N.readdir(a.na).filter(c).map(e(a.na));a.length;){var g=a.pop();try{var h=N.stat(g)}catch(l){return b(l)}N.N(h.mode)&&a.push.apply(a,N.readdir(g).filter(c).map(e(g)));f[g]={timestamp:h.mtime}}return b(null,{type:"local",entries:f})},Mb:(a,b)=>{var c={};O.Ib(a.na,(e,f)=>{if(e)return b(e);try{var g=f.transaction([O.P],"readonly");g.onerror=h=>{b(this.error);h.preventDefault()};g.objectStore(O.P).index("timestamp").openKeyCursor().onsuccess=h=>{h=h.target.result;if(!h)return b(null,{type:"remote",
db:f,entries:c});c[h.primaryKey]={timestamp:h.key};h.continue()}}catch(h){return b(h)}})},Pb:(a,b)=>{try{var c=N.K(a).node;var e=N.stat(a)}catch(f){return b(f)}return N.N(e.mode)?b(null,{timestamp:e.mtime,mode:e.mode}):N.isFile(e.mode)?(c.I=U.Kb(c),b(null,{timestamp:e.mtime,mode:e.mode,contents:c.I})):b(Error("node type not supported"))},fc:(a,b,c)=>{try{if(N.N(b.mode))N.Tb(a,b.mode);else if(N.isFile(b.mode))N.writeFile(a,b.contents,{Xa:!0});else return c(Error("node type not supported"));N.chmod(a,
b.mode);N.jc(a,b.timestamp,b.timestamp)}catch(e){return c(e)}c(null)},ac:(a,b)=>{try{N.K(a);var c=N.stat(a);N.N(c.mode)?N.rmdir(a):N.isFile(c.mode)&&N.unlink(a)}catch(e){return b(e)}b(null)},Qb:(a,b,c)=>{a=a.get(b);a.onsuccess=e=>{c(null,e.target.result)};a.onerror=e=>{c(this.error);e.preventDefault()}},hc:(a,b,c,e)=>{try{var f=a.put(c,b)}catch(g){e(g);return}f.onsuccess=()=>{e(null)};f.onerror=g=>{e(this.error);g.preventDefault()}},bc:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>{c(null)};a.onerror=e=>
{c(this.error);e.preventDefault()}},$b:(a,b,c)=>{function e(p){if(p&&!l)return l=!0,c(p)}var f=0,g=[];Object.keys(a.entries).forEach(function(p){var r=a.entries[p],u=b.entries[p];u&&r.timestamp.getTime()==u.timestamp.getTime()||(g.push(p),f++)});var h=[];Object.keys(b.entries).forEach(function(p){a.entries[p]||(h.push(p),f++)});if(!f)return c(null);var l=!1,n=("remote"===a.type?a.db:b.db).transaction([O.P],"readwrite"),m=n.objectStore(O.P);n.onerror=p=>{e(this.error);p.preventDefault()};n.oncomplete=
()=>{l||c(null)};g.sort().forEach(p=>{"local"===b.type?O.Qb(m,p,(r,u)=>{if(r)return e(r);O.fc(p,u,e)}):O.Pb(p,(r,u)=>{if(r)return e(r);O.hc(m,p,u,e)})});h.sort().reverse().forEach(p=>{"local"===b.type?O.ac(p,e):O.bc(m,p,e)})}},N={root:null,oa:[],bb:{},streams:[],Vb:1,V:null,$a:"/",Ha:!1,ob:!0,G:null,Da:{},Gb:null,ya:0,K:(a,b={})=>{a=T(N.cwd(),a);if(!a)return{path:"",node:null};b=Object.assign({Ca:!0,Qa:0},b);if(8<b.Qa)throw new N.G(32);a=Oa(a.split("/").filter(h=>!!h),!1);for(var c=N.root,e="/",f=
0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=N.X(c,a[f]);e=Q(e,a[f]);N.aa(c)&&(!g||g&&b.Ca)&&(c=c.ma.root);if(!g||b.S)for(g=0;N.ka(c.mode);)if(c=N.readlink(e),e=T(Qa(e),c),c=N.K(e,{Qa:b.Qa+1}).node,40<g++)throw new N.G(32);}return{path:e,node:c}},$:a=>{for(var b;;){if(N.va(a))return a=a.L.na,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ga:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%N.V.length},mb:a=>{var b=N.Ga(a.parent.id,
a.name);a.da=N.V[b];N.V[b]=a},nb:a=>{var b=N.Ga(a.parent.id,a.name);if(N.V[b]===a)N.V[b]=a.da;else for(b=N.V[b];b;){if(b.da===a){b.da=a.da;break}b=b.da}},X:(a,b)=>{var c=N.Rb(a);if(c)throw new N.G(c,a);for(c=N.V[N.Ga(a.id,b)];c;c=c.da){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return N.lookup(a,b)},createNode:(a,b,c,e)=>{a=new N.pb(a,b,c,e);N.mb(a);return a},Ba:a=>{N.nb(a)},va:a=>a===a.parent,aa:a=>!!a.ma,isFile:a=>32768===(a&61440),N:a=>16384===(a&61440),ka:a=>40960===(a&61440),ua:a=>8192===
(a&61440),Nb:a=>24576===(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),Hb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Ub:a=>{var b=N.Hb[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},fb:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ea:(a,b)=>{if(N.ob)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Rb:a=>{var b=N.ea(a,"x");return b?b:a.H.lookup?
0:2},Na:(a,b)=>{try{return N.X(a,b),20}catch(c){}return N.ea(a,"wx")},wa:(a,b,c)=>{try{var e=N.X(a,b)}catch(f){return f.R}if(a=N.ea(a,"wx"))return a;if(c){if(!N.N(e.mode))return 54;if(N.va(e)||N.$(e)===N.cwd())return 10}else if(N.N(e.mode))return 31;return 0},Sb:(a,b)=>a?N.ka(a.mode)?32:N.N(a.mode)&&("r"!==N.fb(b)||b&512)?31:N.ea(a,N.fb(b)):44,rb:4096,Wb:(a=0,b=N.rb)=>{for(;a<=b;a++)if(!N.streams[a])return a;throw new N.G(33);},fa:a=>N.streams[a],Db:(a,b,c)=>{N.za||(N.za=function(){},N.za.prototype=
{object:{get:function(){return this.node},set:function(e){this.node=e}}});a=Object.assign(new N.za,a);b=N.Wb(b,c);a.fd=b;return N.streams[b]=a},xb:a=>{N.streams[a]=null},wb:{open:a=>{a.J=N.Jb(a.node.rdev).J;a.J.open&&a.J.open(a)},U:()=>{throw new N.G(70);}},Ma:a=>a>>8,tc:a=>a&255,ba:(a,b)=>a<<8|b,Ra:(a,b)=>{N.bb[a]={J:b}},Jb:a=>N.bb[a],ib:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.oa)}return b},qa:(a,b)=>{function c(h){N.ya--;return b(h)}function e(h){if(h){if(!e.Eb)return e.Eb=
!0,c(h)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);N.ya++;1<N.ya&&y("warning: "+N.ya+" FS.syncfs operations in flight at once, probably just doing extra work");var f=N.ib(N.root.L),g=0;f.forEach(h=>{if(!h.type.qa)return e(null);h.type.qa(h,a,e)})},L:(a,b,c)=>{var e="/"===c,f=!c;if(e&&N.root)throw new N.G(10);if(!e&&!f){var g=N.K(c,{Ca:!1});c=g.path;g=g.node;if(N.aa(g))throw new N.G(10);if(!N.N(g.mode))throw new N.G(54);}b={type:a,vc:b,na:c,oa:[]};a=a.L(b);a.L=b;b.root=a;e?N.root=
a:g&&(g.ma=b,g.L&&g.L.oa.push(b));return a},Bc:a=>{a=N.K(a,{Ca:!1});if(!N.aa(a.node))throw new N.G(28);a=a.node;var b=a.ma,c=N.ib(b);Object.keys(N.V).forEach(e=>{for(e=N.V[e];e;){var f=e.da;c.includes(e.L)&&N.Ba(e);e=f}});a.ma=null;a.L.oa.splice(a.L.oa.indexOf(b),1)},lookup:(a,b)=>a.H.lookup(a,b),Y:(a,b,c)=>{var e=N.K(a,{parent:!0}).node;a=P(a);if(!a||"."===a||".."===a)throw new N.G(28);var f=N.Na(e,a);if(f)throw new N.G(f);if(!e.H.Y)throw new N.G(63);return e.H.Y(e,a,b,c)},create:(a,b)=>N.Y(a,(void 0!==
b?b:438)&4095|32768,0),mkdir:(a,b)=>N.Y(a,(void 0!==b?b:511)&1023|16384,0),Tb:(a,b)=>{a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{N.mkdir(c,b)}catch(f){if(20!=f.R)throw f;}}},xa:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return N.Y(a,b|8192,c)},symlink:(a,b)=>{if(!T(a))throw new N.G(44);var c=N.K(b,{parent:!0}).node;if(!c)throw new N.G(44);b=P(b);var e=N.Na(c,b);if(e)throw new N.G(e);if(!c.H.symlink)throw new N.G(63);return c.H.symlink(c,b,a)},rename:(a,b)=>{var c=Qa(a),
e=Qa(b),f=P(a),g=P(b);var h=N.K(a,{parent:!0});var l=h.node;h=N.K(b,{parent:!0});h=h.node;if(!l||!h)throw new N.G(44);if(l.L!==h.L)throw new N.G(75);var n=N.X(l,f);a=Sa(a,e);if("."!==a.charAt(0))throw new N.G(28);a=Sa(b,c);if("."!==a.charAt(0))throw new N.G(55);try{var m=N.X(h,g)}catch(p){}if(n!==m){b=N.N(n.mode);if(f=N.wa(l,f,b))throw new N.G(f);if(f=m?N.wa(h,g,b):N.Na(h,g))throw new N.G(f);if(!l.H.rename)throw new N.G(63);if(N.aa(n)||m&&N.aa(m))throw new N.G(10);if(h!==l&&(f=N.ea(l,"w")))throw new N.G(f);
N.nb(n);try{l.H.rename(n,h,g)}catch(p){throw p;}finally{N.mb(n)}}},rmdir:a=>{var b=N.K(a,{parent:!0}).node;a=P(a);var c=N.X(b,a),e=N.wa(b,a,!0);if(e)throw new N.G(e);if(!b.H.rmdir)throw new N.G(63);if(N.aa(c))throw new N.G(10);b.H.rmdir(b,a);N.Ba(c)},readdir:a=>{a=N.K(a,{S:!0}).node;if(!a.H.readdir)throw new N.G(54);return a.H.readdir(a)},unlink:a=>{var b=N.K(a,{parent:!0}).node;if(!b)throw new N.G(44);a=P(a);var c=N.X(b,a),e=N.wa(b,a,!1);if(e)throw new N.G(e);if(!b.H.unlink)throw new N.G(63);if(N.aa(c))throw new N.G(10);
b.H.unlink(b,a);N.Ba(c)},readlink:a=>{a=N.K(a).node;if(!a)throw new N.G(44);if(!a.H.readlink)throw new N.G(28);return T(N.$(a.parent),a.H.readlink(a))},stat:(a,b)=>{a=N.K(a,{S:!b}).node;if(!a)throw new N.G(44);if(!a.H.T)throw new N.G(63);return a.H.T(a)},lstat:a=>N.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?N.K(a,{S:!c}).node:a;if(!a.H.O)throw new N.G(63);a.H.O(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{N.chmod(a,b,!0)},fchmod:(a,b)=>{a=N.fa(a);if(!a)throw new N.G(8);
N.chmod(a.node,b)},chown:(a,b,c,e)=>{a="string"==typeof a?N.K(a,{S:!e}).node:a;if(!a.H.O)throw new N.G(63);a.H.O(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{N.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=N.fa(a);if(!a)throw new N.G(8);N.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new N.G(28);a="string"==typeof a?N.K(a,{S:!0}).node:a;if(!a.H.O)throw new N.G(63);if(N.N(a.mode))throw new N.G(31);if(!N.isFile(a.mode))throw new N.G(28);var c=N.ea(a,"w");if(c)throw new N.G(c);a.H.O(a,{size:b,timestamp:Date.now()})},
qc:(a,b)=>{a=N.fa(a);if(!a)throw new N.G(8);if(0===(a.flags&2097155))throw new N.G(28);N.truncate(a.node,b)},jc:(a,b,c)=>{a=N.K(a,{S:!0}).node;a.H.O(a,{timestamp:Math.max(b,c)})},open:(a,b,c,e,f)=>{if(""===a)throw new N.G(44);b="string"==typeof b?N.Ub(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var g=a;else{a=Pa(a);try{g=N.K(a,{S:!(b&131072)}).node}catch(l){}}var h=!1;if(b&64)if(g){if(b&128)throw new N.G(20);}else g=N.Y(a,c,0),h=!0;if(!g)throw new N.G(44);N.ua(g.mode)&&
(b&=-513);if(b&65536&&!N.N(g.mode))throw new N.G(54);if(!h&&(c=N.Sb(g,b)))throw new N.G(c);b&512&&N.truncate(g,0);b&=-131713;e=N.Db({node:g,path:N.$(g),flags:b,seekable:!0,position:0,J:g.J,ic:[],error:!1},e,f);e.J.open&&e.J.open(e);!d.logReadFiles||b&1||(N.Pa||(N.Pa={}),a in N.Pa||(N.Pa[a]=1));return e},close:a=>{if(N.ja(a))throw new N.G(8);a.Fa&&(a.Fa=null);try{a.J.close&&a.J.close(a)}catch(b){throw b;}finally{N.xb(a.fd)}a.fd=null},ja:a=>null===a.fd,U:(a,b,c)=>{if(N.ja(a))throw new N.G(8);if(!a.seekable||
!a.J.U)throw new N.G(70);if(0!=c&&1!=c&&2!=c)throw new N.G(28);a.position=a.J.U(a,b,c);a.ic=[];return a.position},read:(a,b,c,e,f)=>{if(0>e||0>f)throw new N.G(28);if(N.ja(a))throw new N.G(8);if(1===(a.flags&2097155))throw new N.G(8);if(N.N(a.node.mode))throw new N.G(31);if(!a.J.read)throw new N.G(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new N.G(70);b=a.J.read(a,b,c,e,f);g||(a.position+=b);return b},write:(a,b,c,e,f,g)=>{if(0>e||0>f)throw new N.G(28);if(N.ja(a))throw new N.G(8);
if(0===(a.flags&2097155))throw new N.G(8);if(N.N(a.node.mode))throw new N.G(31);if(!a.J.write)throw new N.G(28);a.seekable&&a.flags&1024&&N.U(a,0,2);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new N.G(70);b=a.J.write(a,b,c,e,f,g);h||(a.position+=b);return b},ha:(a,b,c)=>{if(N.ja(a))throw new N.G(8);if(0>b||0>=c)throw new N.G(28);if(0===(a.flags&2097155))throw new N.G(8);if(!N.isFile(a.node.mode)&&!N.N(a.node.mode))throw new N.G(43);if(!a.J.ha)throw new N.G(138);a.J.ha(a,
b,c)},la:(a,b,c,e,f,g)=>{if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new N.G(2);if(1===(a.flags&2097155))throw new N.G(2);if(!a.J.la)throw new N.G(43);return a.J.la(a,b,c,e,f,g)},pa:(a,b,c,e,f)=>a&&a.J.pa?a.J.pa(a,b,c,e,f):0,uc:()=>0,Ia:(a,b,c)=>{if(!a.J.Ia)throw new N.G(59);return a.J.Ia(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=N.open(a,b.flags);
a=N.stat(a).size;var f=new Uint8Array(a);N.read(e,f,0,a,0);"utf8"===b.encoding?c=H(f,0):"binary"===b.encoding&&(c=f);N.close(e);return c},writeFile:(a,b,c={})=>{c.flags=c.flags||577;a=N.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(ta(b)+1);b=D(b,e,0,e.length);N.write(a,e,0,b,void 0,c.Xa)}else if(ArrayBuffer.isView(b))N.write(a,b,0,b.byteLength,void 0,c.Xa);else throw Error("Unsupported data type");N.close(a)},cwd:()=>N.$a,chdir:a=>{a=N.K(a,{S:!0});if(null===a.node)throw new N.G(44);
if(!N.N(a.node.mode))throw new N.G(54);var b=N.ea(a.node,"x");if(b)throw new N.G(b);N.$a=a.path},zb:()=>{N.mkdir("/tmp");N.mkdir("/home");N.mkdir("/home/web_user")},yb:()=>{N.mkdir("/dev");N.Ra(N.ba(1,3),{read:()=>0,write:(b,c,e,f)=>f});N.xa("/dev/null",N.ba(1,3));Ua(N.ba(5,0),Xa);Ua(N.ba(6,0),Ya);N.xa("/dev/tty",N.ba(5,0));N.xa("/dev/tty1",N.ba(6,0));var a=Ra();N.Z("/dev","random",a);N.Z("/dev","urandom",a);N.mkdir("/dev/shm");N.mkdir("/dev/shm/tmp")},Bb:()=>{N.mkdir("/proc");var a=N.mkdir("/proc/self");
N.mkdir("/proc/self/fd");N.L({L:()=>{var b=N.createNode(a,"fd",16895,73);b.H={lookup:(c,e)=>{var f=N.fa(+e);if(!f)throw new N.G(8);c={parent:null,L:{na:"fake"},H:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},Cb:()=>{d.stdin?N.Z("/dev","stdin",d.stdin):N.symlink("/dev/tty","/dev/stdin");d.stdout?N.Z("/dev","stdout",null,d.stdout):N.symlink("/dev/tty","/dev/stdout");d.stderr?N.Z("/dev","stderr",null,d.stderr):N.symlink("/dev/tty1","/dev/stderr");N.open("/dev/stdin",0);N.open("/dev/stdout",
1);N.open("/dev/stderr",1)},cb:()=>{N.G||(N.G=function(a,b){this.node=b;this.dc=function(c){this.R=c};this.dc(a);this.message="FS error"},N.G.prototype=Error(),N.G.prototype.constructor=N.G,[44].forEach(a=>{N.Da[a]=new N.G(a);N.Da[a].stack="<generic error, no stack>"}))},ec:()=>{N.cb();N.V=Array(4096);N.L(U,{},"/");N.zb();N.yb();N.Bb();N.Gb={MEMFS:U,IDBFS:O}},ta:(a,b,c)=>{N.ta.Ha=!0;N.cb();d.stdin=a||d.stdin;d.stdout=b||d.stdout;d.stderr=c||d.stderr;N.Cb()},xc:()=>{N.ta.Ha=!1;for(var a=0;a<N.streams.length;a++){var b=
N.streams[a];b&&N.close(b)}},Ea:(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},pc:(a,b)=>{a=N.Aa(a,b);return a.exists?a.object:null},Aa:(a,b)=>{try{var c=N.K(a,{S:!b});a=c.path}catch(f){}var e={va:!1,exists:!1,error:0,name:null,path:null,object:null,Xb:!1,Zb:null,Yb:null};try{c=N.K(a,{parent:!0}),e.Xb=!0,e.Zb=c.path,e.Yb=c.node,e.name=P(a),c=N.K(a,{S:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.va="/"===c.path}catch(f){e.error=f.R}return e},nc:(a,b)=>{a="string"==typeof a?
a:N.$(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=Q(a,c);try{N.mkdir(e)}catch(f){}a=e}}return e},Ab:(a,b,c,e,f)=>{a=Q("string"==typeof a?a:N.$(a),b);return N.create(a,N.Ea(e,f))},Za:(a,b,c,e,f,g)=>{var h=b;a&&(a="string"==typeof a?a:N.$(a),h=b?Q(a,b):a);a=N.Ea(e,f);h=N.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(f=c.length;e<f;++e)b[e]=c.charCodeAt(e);c=b}N.chmod(h,a|146);b=N.open(h,577);N.write(b,c,0,c.length,0,g);N.close(b);N.chmod(h,a)}return h},
Z:(a,b,c,e)=>{a=Q("string"==typeof a?a:N.$(a),b);b=N.Ea(!!c,!!e);N.Z.Ma||(N.Z.Ma=64);var f=N.ba(N.Z.Ma++,0);N.Ra(f,{open:g=>{g.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(g,h,l,n)=>{for(var m=0,p=0;p<n;p++){try{var r=c()}catch(u){throw new N.G(29);}if(void 0===r&&0===m)throw new N.G(6);if(null===r||void 0===r)break;m++;h[l+p]=r}m&&(g.node.timestamp=Date.now());return m},write:(g,h,l,n)=>{for(var m=0;m<n;m++)try{e(h[l+m])}catch(p){throw new N.G(29);}n&&(g.node.timestamp=Date.now());
return m}});return N.xa(a,b,f)},gb:a=>{if(a.Ja||a.Ob||a.link||a.I)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(t)try{a.I=Wa(t(a.url)),a.M=a.I.length}catch(b){throw new N.G(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},mc:(a,b,c,e,f)=>{function g(){this.Ka=!1;this.sa=
[]}g.prototype.get=function(m){if(!(m>this.length-1||0>m)){var p=m%this.chunkSize;return this.kb(m/this.chunkSize|0)[p]}};g.prototype.qb=function(m){this.kb=m};g.prototype.Va=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var p=Number(m.getResponseHeader("Content-length")),r,u=(r=m.getResponseHeader("Accept-Ranges"))&&"bytes"===r;m=(r=m.getResponseHeader("Content-Encoding"))&&
"gzip"===r;var w=1048576;u||(w=p);var x=this;x.qb(R=>{var aa=R*w,S=(R+1)*w-1;S=Math.min(S,p-1);if("undefined"==typeof x.sa[R]){var Cb=x.sa;if(aa>S)throw Error("invalid range ("+aa+", "+S+") or no bytes requested!");if(S>p-1)throw Error("only "+p+" bytes available! programmer error!");var z=new XMLHttpRequest;z.open("GET",c,!1);p!==w&&z.setRequestHeader("Range","bytes="+aa+"-"+S);z.responseType="arraybuffer";z.overrideMimeType&&z.overrideMimeType("text/plain; charset=x-user-defined");z.send(null);
if(!(200<=z.status&&300>z.status||304===z.status))throw Error("Couldn't load "+c+". Status: "+z.status);aa=void 0!==z.response?new Uint8Array(z.response||[]):Wa(z.responseText||"");Cb[R]=aa}if("undefined"==typeof x.sa[R])throw Error("doXHR failed!");return x.sa[R]});if(m||!p)w=p=1,w=p=this.kb(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.tb=p;this.sb=w;this.Ka=!0};if("undefined"!=typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new g;Object.defineProperties(h,{length:{get:function(){this.Ka||this.Va();return this.tb}},chunkSize:{get:function(){this.Ka||this.Va();return this.sb}}});h={Ja:!1,I:h}}else h={Ja:!1,url:c};var l=N.Ab(a,b,h,e,f);h.I?l.I=h.I:h.url&&(l.I=null,l.url=h.url);Object.defineProperties(l,{M:{get:function(){return this.I.length}}});var n={};Object.keys(l.J).forEach(m=>{var p=l.J[m];n[m]=function(){N.gb(l);return p.apply(null,arguments)}});n.read=(m,p,r,u,w)=>{N.gb(l);m=m.node.I;if(w>=m.length)return 0;
u=Math.min(m.length-w,u);if(m.slice)for(var x=0;x<u;x++)p[r+x]=m[w+x];else for(x=0;x<u;x++)p[r+x]=m.get(w+x);return u};l.J=n;return l},oc:(a,b,c,e,f,g,h,l,n,m)=>{function p(u){function w(x){m&&m();l||N.Za(a,b,x,e,f,n);g&&g();Fa()}V.rc(u,r,w,()=>{h&&h();Fa()})||w(u)}var r=b?T(Q(a,b)):a;Ea();"string"==typeof c?Za(c,u=>p(u),h):p(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Ta:()=>"EM_FS_"+window.location.pathname,ra:20,P:"FILE_DATA",yc:(a,b,c)=>
{b=b||(()=>{});c=c||(()=>{});var e=N.indexedDB();try{var f=e.open(N.Ta(),N.ra)}catch(g){return c(g)}f.onupgradeneeded=()=>{ka("creating db");f.result.createObjectStore(N.P)};f.onsuccess=()=>{var g=f.result.transaction([N.P],"readwrite"),h=g.objectStore(N.P),l=0,n=0,m=a.length;a.forEach(p=>{p=h.put(N.Aa(p).object.I,p);p.onsuccess=()=>{l++;l+n==m&&(0==n?b():c())};p.onerror=()=>{n++;l+n==m&&(0==n?b():c())}});g.onerror=c};f.onerror=c},sc:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=N.indexedDB();try{var f=
e.open(N.Ta(),N.ra)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=()=>{var g=f.result;try{var h=g.transaction([N.P],"readonly")}catch(r){c(r);return}var l=h.objectStore(N.P),n=0,m=0,p=a.length;a.forEach(r=>{var u=l.get(r);u.onsuccess=()=>{N.Aa(r).exists&&N.unlink(r);N.Za(Qa(r),P(r),u.result,!0,!0,!0);n++;n+m==p&&(0==m?b():c())};u.onerror=()=>{m++;n+m==p&&(0==m?b():c())}});h.onerror=c};f.onerror=c}},$a=void 0;function W(){$a+=4;return I[$a-4>>2]}
function X(a){a=N.fa(a);if(!a)throw new N.G(8);return a}var ab=[],bb;bb=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var cb=0;function db(){for(var a=Y.length-1;0<=a;--a)eb(a);Y=[];fb=[]}var fb=[];function gb(){if(cb&&hb.ub)for(var a=0;a<fb.length;++a){var b=fb[a];fb.splice(a,1);--a;b.zc.apply(null,b.lc)}}var Y=[];function eb(a){var b=Y[a];b.target.removeEventListener(b.ia,b.Fb,b.Sa);Y.splice(a,1)}
function ib(a){function b(e){++cb;hb=a;gb();a.lb(e);gb();--cb}if(a.Wa)a.Fb=b,a.target.addEventListener(a.ia,b,a.Sa),Y.push(a),jb||(Aa.push(db),jb=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].ia==a.ia&&eb(c--)}var jb,hb,kb,lb,mb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function nb(a){a=2<a?oa(a):a;return mb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}
function ob(a,b,c,e,f,g){kb||(kb=pb(176));a={target:nb(a),ub:!0,ia:g,Wa:e,lb:function(h){var l=kb;wa[l>>3]=h.timeStamp;var n=l>>2;I[n+2]=h.location;I[n+3]=h.ctrlKey;I[n+4]=h.shiftKey;I[n+5]=h.altKey;I[n+6]=h.metaKey;I[n+7]=h.repeat;I[n+8]=h.charCode;I[n+9]=h.keyCode;I[n+10]=h.which;D(h.key||"",E,l+44,32);D(h.code||"",E,l+76,32);D(h.char||"",E,l+108,32);D(h.locale||"",E,l+140,32);qb.apply(null,[e,f,l,b])&&h.preventDefault()},Sa:c};ib(a)}
function rb(a,b,c,e){lb||(lb=pb(36));a=nb(a);ib({target:a,ia:"resize",Wa:e,lb:function(f){f=f||event;if(f.target==a){var g=document.body;if(g){var h=lb;I[h>>2]=f.detail;I[h+4>>2]=g.clientWidth;I[h+8>>2]=g.clientHeight;I[h+12>>2]=innerWidth;I[h+16>>2]=innerHeight;I[h+20>>2]=outerWidth;I[h+24>>2]=outerHeight;I[h+28>>2]=pageXOffset;I[h+32>>2]=pageYOffset;qb.apply(null,[e,10,h,b])&&f.preventDefault()}}},Sa:c})}function sb(a){if(!C)try{a()}catch(b){Na(b)}}
function tb(a,b){return setTimeout(function(){sb(a)},b)}function ub(a){try{a()}catch(b){B(b)}}var Z=0,G=null,vb=[],wb={},xb={},yb=0,zb=null,Ab=[];function Bb(a){var b={},c;for(c in a)(function(e){var f=a[e];b[e]="function"==typeof f?function(){vb.push(e);try{return f.apply(null,arguments)}finally{C||(vb.pop()===e||B(void 0),G&&1===Z&&0===vb.length&&(Z=0,ub(d._asyncify_stop_unwind),"undefined"!=typeof Fibers&&Fibers.Ac()))}}:f})(c);return b}
function ra(){return new Promise((a,b)=>{zb={resolve:a,reject:b}})}function Db(){var a=pb(4108),b=a+12;I[a>>2]=b;I[a+4>>2]=b+4096;b=vb[0];var c=wb[b];void 0===c&&(c=yb++,wb[b]=c,xb[c]=b);I[a+8>>2]=c;return a}
function Eb(a){if(!C)if(0===Z){var b=!1,c=!1;a(()=>{if(!C&&(b=!0,c)){Z=2;ub(()=>d._asyncify_start_rewind(G));"undefined"!=typeof V&&V.La.hb&&V.La.resume();var e=!1;try{var f=(0,d.asm[xb[I[G+8>>2]]])()}catch(l){f=l,e=!0}var g=!1;if(!G){var h=zb;h&&(zb=null,(e?h.reject:h.resolve)(f),g=!0)}if(e&&!g)throw f;}});c=!0;b||(Z=1,G=Db(),ub(()=>d._asyncify_start_unwind(G)),"undefined"!=typeof V&&V.La.hb&&V.La.pause())}else 2===Z?(Z=0,ub(d._asyncify_stop_rewind),Fb(G),G=null,Ab.forEach(e=>sb(e))):B("invalid state: "+
Z)}function Gb(a,b,c,e){a||(a=this);this.parent=a;this.L=a.L;this.ma=null;this.id=N.Vb++;this.name=b;this.mode=c;this.H={};this.J={};this.rdev=e}Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ob:{get:function(){return N.N(this.mode)}},Ja:{get:function(){return N.ua(this.mode)}}});N.pb=Gb;N.ec();var V;
function Wa(a){var b=Array(ta(a)+1);a=D(a,b,0,b.length);b.length=a;return b}
var Ib={d:function(a,b,c){$a=c;try{var e=X(a);switch(b){case 0:var f=W();return 0>f?-28:N.open(e.path,e.flags,0,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=W(),e.flags|=f,0;case 5:return f=W(),va[f+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return I[Hb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof N||!(g instanceof N.G))throw g;return-g.R}},g:function(a,b,c){$a=c;try{var e=X(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?
0:-59;case 21519:if(!e.tty)return-59;var f=W();return I[f>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return f=W(),N.Ia(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:B("bad ioctl syscall "+b)}}catch(g){if("undefined"==typeof N||!(g instanceof N.G))throw g;return-g.R}},h:function(a,b,c,e){$a=e;try{b=oa(b);var f=b;if("/"===f[0])b=f;else{if(-100===a)var g=N.cwd();else{var h=N.fa(a);if(!h)throw new N.G(8);g=h.path}if(0==f.length)throw new N.G(44);b=Q(g,f)}var l=e?W():
0;return N.open(b,c,l).fd}catch(n){if("undefined"==typeof N||!(n instanceof N.G))throw n;return-n.R}},a:function(a,b,c){ab.length=0;var e;for(c>>=2;e=E[b++];)(e=105>e)&&c&1&&c++,ab.push(e?wa[c++>>1]:I[c]),++c;return La[a].apply(null,ab)},f:bb,l:function(){return Math.random()},b:function(){B("OOM")},j:function(a,b,c,e){ob(a,b,c,e,2,"keydown");return 0},i:function(a,b,c,e){ob(a,b,c,e,3,"keyup");return 0},k:function(a,b,c,e){rb(a,b,c,e);return 0},c:function(a){Eb(b=>tb(b,a))},e:function(a){try{var b=
X(a);N.close(b);return 0}catch(c){if("undefined"==typeof N||!(c instanceof N.G))throw c;return c.R}},o:function(a,b,c,e){try{a:{for(var f=X(a),g=a=0;g<c;g++){var h=I[b+(8*g+4)>>2],l=N.read(f,F,I[b+8*g>>2],h,void 0);if(0>l){var n=-1;break a}a+=l;if(l<h)break}n=a}I[e>>2]=n;return 0}catch(m){if("undefined"==typeof N||!(m instanceof N.G))throw m;return m.R}},m:function(a,b,c,e,f){try{var g=X(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;N.U(g,a,e);Ka=[g.position>>>0,
(M=g.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];I[f>>2]=Ka[0];I[f+4>>2]=Ka[1];g.Fa&&0===a&&0===e&&(g.Fa=null);return 0}catch(h){if("undefined"==typeof N||!(h instanceof N.G))throw h;return h.R}},n:function(a,b,c,e){try{a:{for(var f=X(a),g=a=0;g<c;g++){var h=N.write(f,F,I[b+8*g>>2],I[b+(8*g+4)>>2],void 0);if(0>h){var l=-1;break a}a+=h}l=a}I[e>>2]=l;return 0}catch(n){if("undefined"==typeof N||!(n instanceof N.G))throw n;
return n.R}}};
(function(){function a(g){g=g.exports;g=Bb(g);d.asm=g;la=d.asm.p;ua=g=la.buffer;d.HEAP8=F=new Int8Array(g);d.HEAP16=va=new Int16Array(g);d.HEAP32=I=new Int32Array(g);d.HEAPU8=E=new Uint8Array(g);d.HEAPU16=new Uint16Array(g);d.HEAPU32=new Uint32Array(g);d.HEAPF32=new Float32Array(g);d.HEAPF64=wa=new Float64Array(g);ya.unshift(d.asm.q);Fa()}function b(g){a(g.instance)}function c(g){return Ja().then(function(h){return WebAssembly.instantiate(h,e)}).then(function(h){return h}).then(g,function(h){y("failed to asynchronously prepare wasm: "+h);
B(h)})}var e={a:Ib};Ea();if(d.instantiateWasm)try{var f=d.instantiateWasm(e,a);return f=Bb(f)}catch(g){return y("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return A||"function"!=typeof WebAssembly.instantiateStreaming||Ga()||L.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.q).apply(null,arguments)};d._initpers=function(){return(d._initpers=d.asm.r).apply(null,arguments)};d._main=function(){return(d._main=d.asm.s).apply(null,arguments)};
var Hb=d.___errno_location=function(){return(Hb=d.___errno_location=d.asm.t).apply(null,arguments)},Fb=d._free=function(){return(Fb=d._free=d.asm.u).apply(null,arguments)},pb=d._malloc=function(){return(pb=d._malloc=d.asm.v).apply(null,arguments)},qa=d.stackSave=function(){return(qa=d.stackSave=d.asm.x).apply(null,arguments)},na=d.stackRestore=function(){return(na=d.stackRestore=d.asm.y).apply(null,arguments)},pa=d.stackAlloc=function(){return(pa=d.stackAlloc=d.asm.z).apply(null,arguments)},qb=d.dynCall_iiii=
function(){return(qb=d.dynCall_iiii=d.asm.A).apply(null,arguments)},dynCall_v=d.dynCall_v=function(){return(dynCall_v=d.dynCall_v=d.asm.B).apply(null,arguments)};d._asyncify_start_unwind=function(){return(d._asyncify_start_unwind=d.asm.C).apply(null,arguments)};d._asyncify_stop_unwind=function(){return(d._asyncify_stop_unwind=d.asm.D).apply(null,arguments)};d._asyncify_start_rewind=function(){return(d._asyncify_start_rewind=d.asm.E).apply(null,arguments)};
d._asyncify_stop_rewind=function(){return(d._asyncify_stop_rewind=d.asm.F).apply(null,arguments)};d.ccall=ma;d.FS=N;var Jb;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Kb(){Jb||Lb();Jb||(K=Kb)};
function Lb(){function a(){if(!Jb&&(Jb=!0,d.calledRun=!0,!C)){d.noFSInit||N.ta.Ha||N.ta();N.ob=!1;Ma(ya);Ma(za);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Mb){var b=d._main;try{var c=b(0,0);if(!noExitRuntime){if(d.onExit)d.onExit(c);C=!0}ca(c,new ja(c))}catch(e){Na(e)}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)b=d.postRun.shift(),Ba.unshift(b);Ma(Ba)}}if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ca();
Ma(xa);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=Lb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Mb=!0;d.noInitialRun&&(Mb=!1);Lb();
