
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign({},d),ca=(a,b)=>{throw b;},da="object"==typeof window,k="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",t,v,fa,fs,ha,ia;
if(ea)q=k?require("path").dirname(q)+"/":__dirname+"/",ia=()=>{ha||(fs=require("fs"),ha=require("path"))},t=function(a,b){ia();a=ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},fa=a=>{a=t(a,!0);a.buffer||(a=new Uint8Array(a));return a},v=(a,b,c)=>{ia();a=ha.normalize(a);fs.readFile(a,function(e,f){e?c(e):b(f.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!=typeof module&&(module.exports=d),process.on("uncaughtException",function(a){if(!(a instanceof
ja))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ca=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof ja||y("exiting due to exception: "+b);process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(da||k)k?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.send(null);return b.responseText},k&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),v=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var ka=d.print||console.log.bind(console),y=d.printErr||console.warn.bind(console);Object.assign(d,ba);ba=null;d.quit&&(ca=d.quit);var A;
d.wasmBinary&&(A=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;"object"!=typeof WebAssembly&&B("no native wasm support detected");var la,C=!1;
function ma(a,b,c,e,f){function g(r){0!==p&&na(p);return"string"===b?oa(r):"boolean"===b?!!r:r}var h={string:function(r){var u=0;if(null!==r&&void 0!==r&&0!==r){var w=(r.length<<2)+1;u=pa(w);D(r,E,u,w)}return u},array:function(r){var u=pa(r.length);F.set(r,u);return u}};a=d["_"+a];var m=[],p=0;if(e)for(var l=0;l<e.length;l++){var n=h[c[l]];n?(0===p&&(p=qa()),m[l]=n(e[l])):m[l]=e[l]}c=G;e=a.apply(null,m);f=f&&f.async;if(G!=c)return ra().then(g);e=g(e);return f?Promise.resolve(e):e}
var sa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&sa)return sa.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function oa(a){return a?H(E,a,void 0):""}
function D(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(c+3>=e)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}var ua,F,E,va,I,wa,xa=[],ya=[],za=[],Aa=[],Ba=[];function Ca(){var a=d.preRun.shift();xa.unshift(a)}var J=0,Da=null,K=null;function Ea(){J++;d.monitorRunDependencies&&d.monitorRunDependencies(J)}
function Fa(){J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(0==J&&(null!==Da&&(clearInterval(Da),Da=null),K)){var a=K;K=null;a()}}d.preloadedImages={};d.preloadedAudios={};function B(a){if(d.onAbort)d.onAbort(a);a="Aborted("+a+")";y(a);C=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ga(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="ardurogue.wasm";if(!Ga()){var Ha=L;L=d.locateFile?d.locateFile(Ha,q):q+Ha}
function Ia(){var a=L;try{if(a==L&&A)return new Uint8Array(A);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){B(b)}}
function Ja(){if(!A&&(da||k)){if("function"==typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ia()});if(v)return new Promise(function(a,b){v(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ia()})}
var M,Ka,La={6040:function(){N.oa(function(a){!a||B(void 0)})},6083:function(){N.mkdir("/offline");N.J(O,{},"/offline");N.oa(!0,function(){ma("initpers","v")})},6199:function(a,b,c){let e=E.subarray(a,a+b*c*4);a=d.canvas;a.width=innerWidth;a.height=innerHeight;let f=a.getContext("2d");f.imageSmoothingEnabled=!1;let g=document.createElement("canvas"),h=g.getContext("2d");g.width=128;g.height=64;b=h.createImageData(b,c);b.data.set(e);h.putImageData(b,0,0);c=Math.floor(Math.min(a.width/128,a.height/
64));b=128*c;c*=64;f.fillStyle="#000";f.fillRect(0,0,a.width,a.height);f.drawImage(g,Math.floor((a.width-b)/2),Math.floor((a.height-c)/2),b,c)}};function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.fb;"number"==typeof c?void 0===b.Sa&&dynCall_v.call(null,c):c(void 0===b.Sa?null:b.Sa)}}}function Na(a){a instanceof ja||"unwind"==a||ca(1,a)}
function Oa(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Pa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Qa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function P(a){if("/"===a)return"/";a=Pa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Q(a,b){return Pa(a+"/"+b)}
function Ra(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ea)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){B("randomDevice")}}
function T(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:N.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function Sa(a,b){function c(h){for(var m=0;m<h.length&&""===h[m];m++);for(var p=h.length-1;0<=p&&""===h[p];p--);return m>p?[]:h.slice(m,p-m+1)}a=T(a).substr(1);b=T(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],ea:b};N.Pa(a,Va)}
var Va={open:function(a){var b=Ta[a.node.rdev];if(!b)throw new N.u(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ea.flush(a.tty)},flush:function(a){a.tty.ea.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.ea.hb)throw new N.u(60);for(var f=0,g=0;g<e;g++){try{var h=a.tty.ea.hb(a.tty)}catch(m){throw new N.u(29);}if(void 0===h&&0===f)throw new N.u(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.ea.Ma)throw new N.u(60);
try{for(var f=0;f<e;f++)a.tty.ea.Ma(a.tty,b[c+f])}catch(g){throw new N.u(29);}e&&(a.node.timestamp=Date.now());return f}},Xa={hb:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Wa(b)}return a.input.shift()},Ma:function(a,b){null===b||10===b?(ka(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(H(a.output,0)),a.output=[])}},Ya={Ma:function(a,b){null===b||10===b?(y(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(y(H(a.output,0)),a.output=[])}},U={U:null,J:function(){return U.createNode(null,"/",16895,0)},createNode:function(a,
b,c,e){if(N.Lb(c)||N.isFIFO(c))throw new N.u(63);U.U||(U.U={dir:{node:{R:U.F.R,M:U.F.M,lookup:U.F.lookup,W:U.F.W,rename:U.F.rename,unlink:U.F.unlink,rmdir:U.F.rmdir,readdir:U.F.readdir,symlink:U.F.symlink},stream:{S:U.H.S}},file:{node:{R:U.F.R,M:U.F.M},stream:{S:U.H.S,read:U.H.read,write:U.H.write,fa:U.H.fa,ja:U.H.ja,na:U.H.na}},link:{node:{R:U.F.R,M:U.F.M,readlink:U.F.readlink},stream:{}},Wa:{node:{R:U.F.R,M:U.F.M},stream:N.ub}});c=N.createNode(a,b,c,e);N.L(c.mode)?(c.F=U.U.dir.node,c.H=U.U.dir.stream,
c.G={}):N.isFile(c.mode)?(c.F=U.U.file.node,c.H=U.U.file.stream,c.K=0,c.G=null):N.ia(c.mode)?(c.F=U.U.link.node,c.H=U.U.link.stream):N.ra(c.mode)&&(c.F=U.U.Wa.node,c.H=U.U.Wa.stream);c.timestamp=Date.now();a&&(a.G[b]=c,a.timestamp=c.timestamp);return c},Ib:function(a){return a.G?a.G.subarray?a.G.subarray(0,a.K):new Uint8Array(a.G):new Uint8Array(0)},bb:function(a,b){var c=a.G?a.G.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.G,a.G=new Uint8Array(b),0<a.K&&a.G.set(c.subarray(0,
a.K),0))},ac:function(a,b){if(a.K!=b)if(0==b)a.G=null,a.K=0;else{var c=a.G;a.G=new Uint8Array(b);c&&a.G.set(c.subarray(0,Math.min(b,a.K)));a.K=b}},F:{R:function(a){var b={};b.dev=N.ra(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N.L(a.mode)?b.size=4096:N.isFile(a.mode)?b.size=a.K:N.ia(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.tb=4096;b.blocks=Math.ceil(b.size/b.tb);return b},
M:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.ac(a,b.size)},lookup:function(){throw N.Ba[44];},W:function(a,b,c,e){return U.createNode(a,b,c,e)},rename:function(a,b,c){if(N.L(a.mode)){try{var e=N.V(b,c)}catch(g){}if(e)for(var f in e.G)throw new N.u(55);}delete a.parent.G[a.name];a.parent.timestamp=Date.now();a.name=c;b.G[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.G[b];a.timestamp=Date.now()},rmdir:function(a,
b){var c=N.V(a,b),e;for(e in c.G)throw new N.u(55);delete a.G[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.G)a.G.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!N.ia(a.mode))throw new N.u(28);return a.link}},H:{read:function(a,b,c,e,f){var g=a.node.G;if(f>=a.node.K)return 0;a=Math.min(a.node.K-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},
write:function(a,b,c,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.G||a.G.subarray)){if(g)return a.G=b.subarray(c,c+e),a.K=e;if(0===a.K&&0===f)return a.G=b.slice(c,c+e),a.K=e;if(f+e<=a.K)return a.G.set(b.subarray(c,c+e),f),e}U.bb(a,f+e);if(a.G.subarray&&b.subarray)a.G.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.G[f+g]=b[c+g];a.K=Math.max(a.K,f+e);return e},S:function(a,b,c){1===c?b+=a.position:2===c&&N.isFile(a.node.mode)&&(b+=a.node.K);if(0>b)throw new N.u(28);return b},
fa:function(a,b,c){U.bb(a.node,b+c);a.node.K=Math.max(a.node.K,b+c)},ja:function(a,b,c,e,f,g){if(0!==b)throw new N.u(28);if(!N.isFile(a.node.mode))throw new N.u(43);a=a.node.G;if(g&2||a.buffer!==ua){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;B();c=void 0;if(!c)throw new N.u(48);F.set(a,c)}else e=!1,c=a.byteOffset;return{uc:c,ic:e}},na:function(a,b,c,e,f){if(!N.isFile(a.node.mode))throw new N.u(43);if(f&2)return 0;U.H.write(a,b,0,e,c,!1);return 0}}};
function Za(a,b,c){var e="al "+a;v(a,function(f){f||B('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&Fa()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ea()}
var O={Za:{},indexedDB:()=>{if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||B("IDBFS used, but indexedDB not supported");return a},pa:21,N:"FILE_DATA",J:function(a){return U.J.apply(null,arguments)},oa:(a,b,c)=>{O.Jb(a,(e,f)=>{if(e)return c(e);O.Kb(a,(g,h)=>{if(g)return c(g);O.Yb(b?h:f,b?f:h,c)})})},Gb:(a,b)=>{var c=O.Za[a];if(c)return b(null,c);try{var e=O.indexedDB().open(a,
O.pa)}catch(f){return b(f)}if(!e)return b("Unable to connect to IndexedDB");e.onupgradeneeded=f=>{var g=f.target.result;f=f.target.transaction;var h;g.objectStoreNames.contains(O.N)?h=f.objectStore(O.N):h=g.createObjectStore(O.N);h.indexNames.contains("timestamp")||h.createIndex("timestamp","timestamp",{unique:!1})};e.onsuccess=()=>{c=e.result;O.Za[a]=c;b(null,c)};e.onerror=f=>{b(this.error);f.preventDefault()}},Jb:(a,b)=>{function c(m){return"."!==m&&".."!==m}function e(m){return p=>Q(m,p)}var f=
{};for(a=N.readdir(a.la).filter(c).map(e(a.la));a.length;){var g=a.pop();try{var h=N.stat(g)}catch(m){return b(m)}N.L(h.mode)&&a.push.apply(a,N.readdir(g).filter(c).map(e(g)));f[g]={timestamp:h.mtime}}return b(null,{type:"local",entries:f})},Kb:(a,b)=>{var c={};O.Gb(a.la,(e,f)=>{if(e)return b(e);try{var g=f.transaction([O.N],"readonly");g.onerror=h=>{b(this.error);h.preventDefault()};g.objectStore(O.N).index("timestamp").openKeyCursor().onsuccess=h=>{h=h.target.result;if(!h)return b(null,{type:"remote",
db:f,entries:c});c[h.primaryKey]={timestamp:h.key};h.continue()}}catch(h){return b(h)}})},Nb:(a,b)=>{try{var c=N.I(a).node;var e=N.stat(a)}catch(f){return b(f)}return N.L(e.mode)?b(null,{timestamp:e.mtime,mode:e.mode}):N.isFile(e.mode)?(c.G=U.Ib(c),b(null,{timestamp:e.mtime,mode:e.mode,contents:c.G})):b(Error("node type not supported"))},dc:(a,b,c)=>{try{if(N.L(b.mode))N.Rb(a,b.mode);else if(N.isFile(b.mode))N.writeFile(a,b.contents,{Va:!0});else return c(Error("node type not supported"));N.chmod(a,
b.mode);N.hc(a,b.timestamp,b.timestamp)}catch(e){return c(e)}c(null)},Zb:(a,b)=>{try{N.I(a);var c=N.stat(a);N.L(c.mode)?N.rmdir(a):N.isFile(c.mode)&&N.unlink(a)}catch(e){return b(e)}b(null)},Ob:(a,b,c)=>{a=a.get(b);a.onsuccess=e=>{c(null,e.target.result)};a.onerror=e=>{c(this.error);e.preventDefault()}},ec:(a,b,c,e)=>{try{var f=a.put(c,b)}catch(g){e(g);return}f.onsuccess=()=>{e(null)};f.onerror=g=>{e(this.error);g.preventDefault()}},$b:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>{c(null)};a.onerror=e=>
{c(this.error);e.preventDefault()}},Yb:(a,b,c)=>{function e(n){if(n&&!m)return m=!0,c(n)}var f=0,g=[];Object.keys(a.entries).forEach(function(n){var r=a.entries[n],u=b.entries[n];u&&r.timestamp.getTime()==u.timestamp.getTime()||(g.push(n),f++)});var h=[];Object.keys(b.entries).forEach(function(n){a.entries[n]||(h.push(n),f++)});if(!f)return c(null);var m=!1,p=("remote"===a.type?a.db:b.db).transaction([O.N],"readwrite"),l=p.objectStore(O.N);p.onerror=n=>{e(this.error);n.preventDefault()};p.oncomplete=
()=>{m||c(null)};g.sort().forEach(n=>{"local"===b.type?O.Ob(l,n,(r,u)=>{if(r)return e(r);O.dc(n,u,e)}):O.Nb(n,(r,u)=>{if(r)return e(r);O.ec(l,n,u,e)})});h.sort().reverse().forEach(n=>{"local"===b.type?O.Zb(n,e):O.$b(l,n,e)})}},N={root:null,ma:[],$a:{},streams:[],Tb:1,T:null,Ya:"/",Fa:!1,mb:!0,u:null,Ba:{},Eb:null,va:0,I:(a,b={})=>{a=T(N.cwd(),a);if(!a)return{path:"",node:null};b=Object.assign({Aa:!0,Oa:0},b);if(8<b.Oa)throw new N.u(32);a=Oa(a.split("/").filter(h=>!!h),!1);for(var c=N.root,e="/",f=
0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=N.V(c,a[f]);e=Q(e,a[f]);N.Z(c)&&(!g||g&&b.Aa)&&(c=c.ka.root);if(!g||b.P)for(g=0;N.ia(c.mode);)if(c=N.readlink(e),e=T(Qa(e),c),c=N.I(e,{Oa:b.Oa+1}).node,40<g++)throw new N.u(32);}return{path:e,node:c}},Y:a=>{for(var b;;){if(N.sa(a))return a=a.J.la,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ea:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%N.T.length},kb:a=>{var b=N.Ea(a.parent.id,
a.name);a.aa=N.T[b];N.T[b]=a},lb:a=>{var b=N.Ea(a.parent.id,a.name);if(N.T[b]===a)N.T[b]=a.aa;else for(b=N.T[b];b;){if(b.aa===a){b.aa=a.aa;break}b=b.aa}},V:(a,b)=>{var c=N.Pb(a);if(c)throw new N.u(c,a);for(c=N.T[N.Ea(a.id,b)];c;c=c.aa){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return N.lookup(a,b)},createNode:(a,b,c,e)=>{a=new N.ob(a,b,c,e);N.kb(a);return a},za:a=>{N.lb(a)},sa:a=>a===a.parent,Z:a=>!!a.ka,isFile:a=>32768===(a&61440),L:a=>16384===(a&61440),ia:a=>40960===(a&61440),ra:a=>8192===
(a&61440),Lb:a=>24576===(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),Fb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Sb:a=>{var b=N.Fb[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},cb:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ba:(a,b)=>{if(N.mb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Pb:a=>{var b=N.ba(a,"x");return b?b:a.F.lookup?
0:2},La:(a,b)=>{try{return N.V(a,b),20}catch(c){}return N.ba(a,"wx")},ta:(a,b,c)=>{try{var e=N.V(a,b)}catch(f){return f.O}if(a=N.ba(a,"wx"))return a;if(c){if(!N.L(e.mode))return 54;if(N.sa(e)||N.Y(e)===N.cwd())return 10}else if(N.L(e.mode))return 31;return 0},Qb:(a,b)=>a?N.ia(a.mode)?32:N.L(a.mode)&&("r"!==N.cb(b)||b&512)?31:N.ba(a,N.cb(b)):44,pb:4096,Ub:(a=0,b=N.pb)=>{for(;a<=b;a++)if(!N.streams[a])return a;throw new N.u(33);},da:a=>N.streams[a],Bb:(a,b,c)=>{N.xa||(N.xa=function(){},N.xa.prototype=
{object:{get:function(){return this.node},set:function(e){this.node=e}}});a=Object.assign(new N.xa,a);b=N.Ub(b,c);a.fd=b;return N.streams[b]=a},vb:a=>{N.streams[a]=null},ub:{open:a=>{a.H=N.Hb(a.node.rdev).H;a.H.open&&a.H.open(a)},S:()=>{throw new N.u(70);}},Ka:a=>a>>8,rc:a=>a&255,$:(a,b)=>a<<8|b,Pa:(a,b)=>{N.$a[a]={H:b}},Hb:a=>N.$a[a],gb:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.ma)}return b},oa:(a,b)=>{function c(h){N.va--;return b(h)}function e(h){if(h){if(!e.Cb)return e.Cb=
!0,c(h)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);N.va++;1<N.va&&y("warning: "+N.va+" FS.syncfs operations in flight at once, probably just doing extra work");var f=N.gb(N.root.J),g=0;f.forEach(h=>{if(!h.type.oa)return e(null);h.type.oa(h,a,e)})},J:(a,b,c)=>{var e="/"===c,f=!c;if(e&&N.root)throw new N.u(10);if(!e&&!f){var g=N.I(c,{Aa:!1});c=g.path;g=g.node;if(N.Z(g))throw new N.u(10);if(!N.L(g.mode))throw new N.u(54);}b={type:a,tc:b,la:c,ma:[]};a=a.J(b);a.J=b;b.root=a;e?N.root=a:
g&&(g.ka=b,g.J&&g.J.ma.push(b));return a},zc:a=>{a=N.I(a,{Aa:!1});if(!N.Z(a.node))throw new N.u(28);a=a.node;var b=a.ka,c=N.gb(b);Object.keys(N.T).forEach(e=>{for(e=N.T[e];e;){var f=e.aa;c.includes(e.J)&&N.za(e);e=f}});a.ka=null;a.J.ma.splice(a.J.ma.indexOf(b),1)},lookup:(a,b)=>a.F.lookup(a,b),W:(a,b,c)=>{var e=N.I(a,{parent:!0}).node;a=P(a);if(!a||"."===a||".."===a)throw new N.u(28);var f=N.La(e,a);if(f)throw new N.u(f);if(!e.F.W)throw new N.u(63);return e.F.W(e,a,b,c)},create:(a,b)=>N.W(a,(void 0!==
b?b:438)&4095|32768,0),mkdir:(a,b)=>N.W(a,(void 0!==b?b:511)&1023|16384,0),Rb:(a,b)=>{a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{N.mkdir(c,b)}catch(f){if(20!=f.O)throw f;}}},ua:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return N.W(a,b|8192,c)},symlink:(a,b)=>{if(!T(a))throw new N.u(44);var c=N.I(b,{parent:!0}).node;if(!c)throw new N.u(44);b=P(b);var e=N.La(c,b);if(e)throw new N.u(e);if(!c.F.symlink)throw new N.u(63);return c.F.symlink(c,b,a)},rename:(a,b)=>{var c=Qa(a),
e=Qa(b),f=P(a),g=P(b);var h=N.I(a,{parent:!0});var m=h.node;h=N.I(b,{parent:!0});h=h.node;if(!m||!h)throw new N.u(44);if(m.J!==h.J)throw new N.u(75);var p=N.V(m,f);a=Sa(a,e);if("."!==a.charAt(0))throw new N.u(28);a=Sa(b,c);if("."!==a.charAt(0))throw new N.u(55);try{var l=N.V(h,g)}catch(n){}if(p!==l){b=N.L(p.mode);if(f=N.ta(m,f,b))throw new N.u(f);if(f=l?N.ta(h,g,b):N.La(h,g))throw new N.u(f);if(!m.F.rename)throw new N.u(63);if(N.Z(p)||l&&N.Z(l))throw new N.u(10);if(h!==m&&(f=N.ba(m,"w")))throw new N.u(f);
N.lb(p);try{m.F.rename(p,h,g)}catch(n){throw n;}finally{N.kb(p)}}},rmdir:a=>{var b=N.I(a,{parent:!0}).node;a=P(a);var c=N.V(b,a),e=N.ta(b,a,!0);if(e)throw new N.u(e);if(!b.F.rmdir)throw new N.u(63);if(N.Z(c))throw new N.u(10);b.F.rmdir(b,a);N.za(c)},readdir:a=>{a=N.I(a,{P:!0}).node;if(!a.F.readdir)throw new N.u(54);return a.F.readdir(a)},unlink:a=>{var b=N.I(a,{parent:!0}).node;if(!b)throw new N.u(44);a=P(a);var c=N.V(b,a),e=N.ta(b,a,!1);if(e)throw new N.u(e);if(!b.F.unlink)throw new N.u(63);if(N.Z(c))throw new N.u(10);
b.F.unlink(b,a);N.za(c)},readlink:a=>{a=N.I(a).node;if(!a)throw new N.u(44);if(!a.F.readlink)throw new N.u(28);return T(N.Y(a.parent),a.F.readlink(a))},stat:(a,b)=>{a=N.I(a,{P:!b}).node;if(!a)throw new N.u(44);if(!a.F.R)throw new N.u(63);return a.F.R(a)},lstat:a=>N.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?N.I(a,{P:!c}).node:a;if(!a.F.M)throw new N.u(63);a.F.M(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{N.chmod(a,b,!0)},fchmod:(a,b)=>{a=N.da(a);if(!a)throw new N.u(8);
N.chmod(a.node,b)},chown:(a,b,c,e)=>{a="string"==typeof a?N.I(a,{P:!e}).node:a;if(!a.F.M)throw new N.u(63);a.F.M(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{N.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=N.da(a);if(!a)throw new N.u(8);N.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new N.u(28);a="string"==typeof a?N.I(a,{P:!0}).node:a;if(!a.F.M)throw new N.u(63);if(N.L(a.mode))throw new N.u(31);if(!N.isFile(a.mode))throw new N.u(28);var c=N.ba(a,"w");if(c)throw new N.u(c);a.F.M(a,{size:b,timestamp:Date.now()})},
oc:(a,b)=>{a=N.da(a);if(!a)throw new N.u(8);if(0===(a.flags&2097155))throw new N.u(28);N.truncate(a.node,b)},hc:(a,b,c)=>{a=N.I(a,{P:!0}).node;a.F.M(a,{timestamp:Math.max(b,c)})},open:(a,b,c,e,f)=>{if(""===a)throw new N.u(44);b="string"==typeof b?N.Sb(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var g=a;else{a=Pa(a);try{g=N.I(a,{P:!(b&131072)}).node}catch(m){}}var h=!1;if(b&64)if(g){if(b&128)throw new N.u(20);}else g=N.W(a,c,0),h=!0;if(!g)throw new N.u(44);N.ra(g.mode)&&
(b&=-513);if(b&65536&&!N.L(g.mode))throw new N.u(54);if(!h&&(c=N.Qb(g,b)))throw new N.u(c);b&512&&N.truncate(g,0);b&=-131713;e=N.Bb({node:g,path:N.Y(g),flags:b,seekable:!0,position:0,H:g.H,fc:[],error:!1},e,f);e.H.open&&e.H.open(e);!d.logReadFiles||b&1||(N.Na||(N.Na={}),a in N.Na||(N.Na[a]=1));return e},close:a=>{if(N.ha(a))throw new N.u(8);a.Da&&(a.Da=null);try{a.H.close&&a.H.close(a)}catch(b){throw b;}finally{N.vb(a.fd)}a.fd=null},ha:a=>null===a.fd,S:(a,b,c)=>{if(N.ha(a))throw new N.u(8);if(!a.seekable||
!a.H.S)throw new N.u(70);if(0!=c&&1!=c&&2!=c)throw new N.u(28);a.position=a.H.S(a,b,c);a.fc=[];return a.position},read:(a,b,c,e,f)=>{if(0>e||0>f)throw new N.u(28);if(N.ha(a))throw new N.u(8);if(1===(a.flags&2097155))throw new N.u(8);if(N.L(a.node.mode))throw new N.u(31);if(!a.H.read)throw new N.u(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new N.u(70);b=a.H.read(a,b,c,e,f);g||(a.position+=b);return b},write:(a,b,c,e,f,g)=>{if(0>e||0>f)throw new N.u(28);if(N.ha(a))throw new N.u(8);
if(0===(a.flags&2097155))throw new N.u(8);if(N.L(a.node.mode))throw new N.u(31);if(!a.H.write)throw new N.u(28);a.seekable&&a.flags&1024&&N.S(a,0,2);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new N.u(70);b=a.H.write(a,b,c,e,f,g);h||(a.position+=b);return b},fa:(a,b,c)=>{if(N.ha(a))throw new N.u(8);if(0>b||0>=c)throw new N.u(28);if(0===(a.flags&2097155))throw new N.u(8);if(!N.isFile(a.node.mode)&&!N.L(a.node.mode))throw new N.u(43);if(!a.H.fa)throw new N.u(138);a.H.fa(a,
b,c)},ja:(a,b,c,e,f,g)=>{if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new N.u(2);if(1===(a.flags&2097155))throw new N.u(2);if(!a.H.ja)throw new N.u(43);return a.H.ja(a,b,c,e,f,g)},na:(a,b,c,e,f)=>a&&a.H.na?a.H.na(a,b,c,e,f):0,sc:()=>0,Ga:(a,b,c)=>{if(!a.H.Ga)throw new N.u(59);return a.H.Ga(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=N.open(a,b.flags);
a=N.stat(a).size;var f=new Uint8Array(a);N.read(e,f,0,a,0);"utf8"===b.encoding?c=H(f,0):"binary"===b.encoding&&(c=f);N.close(e);return c},writeFile:(a,b,c={})=>{c.flags=c.flags||577;a=N.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(ta(b)+1);b=D(b,e,0,e.length);N.write(a,e,0,b,void 0,c.Va)}else if(ArrayBuffer.isView(b))N.write(a,b,0,b.byteLength,void 0,c.Va);else throw Error("Unsupported data type");N.close(a)},cwd:()=>N.Ya,chdir:a=>{a=N.I(a,{P:!0});if(null===a.node)throw new N.u(44);
if(!N.L(a.node.mode))throw new N.u(54);var b=N.ba(a.node,"x");if(b)throw new N.u(b);N.Ya=a.path},xb:()=>{N.mkdir("/tmp");N.mkdir("/home");N.mkdir("/home/web_user")},wb:()=>{N.mkdir("/dev");N.Pa(N.$(1,3),{read:()=>0,write:(b,c,e,f)=>f});N.ua("/dev/null",N.$(1,3));Ua(N.$(5,0),Xa);Ua(N.$(6,0),Ya);N.ua("/dev/tty",N.$(5,0));N.ua("/dev/tty1",N.$(6,0));var a=Ra();N.X("/dev","random",a);N.X("/dev","urandom",a);N.mkdir("/dev/shm");N.mkdir("/dev/shm/tmp")},zb:()=>{N.mkdir("/proc");var a=N.mkdir("/proc/self");
N.mkdir("/proc/self/fd");N.J({J:()=>{var b=N.createNode(a,"fd",16895,73);b.F={lookup:(c,e)=>{var f=N.da(+e);if(!f)throw new N.u(8);c={parent:null,J:{la:"fake"},F:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},Ab:()=>{d.stdin?N.X("/dev","stdin",d.stdin):N.symlink("/dev/tty","/dev/stdin");d.stdout?N.X("/dev","stdout",null,d.stdout):N.symlink("/dev/tty","/dev/stdout");d.stderr?N.X("/dev","stderr",null,d.stderr):N.symlink("/dev/tty1","/dev/stderr");N.open("/dev/stdin",0);N.open("/dev/stdout",
1);N.open("/dev/stderr",1)},ab:()=>{N.u||(N.u=function(a,b){this.node=b;this.bc=function(c){this.O=c};this.bc(a);this.message="FS error"},N.u.prototype=Error(),N.u.prototype.constructor=N.u,[44].forEach(a=>{N.Ba[a]=new N.u(a);N.Ba[a].stack="<generic error, no stack>"}))},cc:()=>{N.ab();N.T=Array(4096);N.J(U,{},"/");N.xb();N.wb();N.zb();N.Eb={MEMFS:U,IDBFS:O}},qa:(a,b,c)=>{N.qa.Fa=!0;N.ab();d.stdin=a||d.stdin;d.stdout=b||d.stdout;d.stderr=c||d.stderr;N.Ab()},vc:()=>{N.qa.Fa=!1;for(var a=0;a<N.streams.length;a++){var b=
N.streams[a];b&&N.close(b)}},Ca:(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},nc:(a,b)=>{a=N.ya(a,b);return a.exists?a.object:null},ya:(a,b)=>{try{var c=N.I(a,{P:!b});a=c.path}catch(f){}var e={sa:!1,exists:!1,error:0,name:null,path:null,object:null,Vb:!1,Xb:null,Wb:null};try{c=N.I(a,{parent:!0}),e.Vb=!0,e.Xb=c.path,e.Wb=c.node,e.name=P(a),c=N.I(a,{P:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.sa="/"===c.path}catch(f){e.error=f.O}return e},lc:(a,b)=>{a="string"==typeof a?
a:N.Y(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=Q(a,c);try{N.mkdir(e)}catch(f){}a=e}}return e},yb:(a,b,c,e,f)=>{a=Q("string"==typeof a?a:N.Y(a),b);return N.create(a,N.Ca(e,f))},Xa:(a,b,c,e,f,g)=>{var h=b;a&&(a="string"==typeof a?a:N.Y(a),h=b?Q(a,b):a);a=N.Ca(e,f);h=N.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(f=c.length;e<f;++e)b[e]=c.charCodeAt(e);c=b}N.chmod(h,a|146);b=N.open(h,577);N.write(b,c,0,c.length,0,g);N.close(b);N.chmod(h,a)}return h},
X:(a,b,c,e)=>{a=Q("string"==typeof a?a:N.Y(a),b);b=N.Ca(!!c,!!e);N.X.Ka||(N.X.Ka=64);var f=N.$(N.X.Ka++,0);N.Pa(f,{open:g=>{g.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(g,h,m,p)=>{for(var l=0,n=0;n<p;n++){try{var r=c()}catch(u){throw new N.u(29);}if(void 0===r&&0===l)throw new N.u(6);if(null===r||void 0===r)break;l++;h[m+n]=r}l&&(g.node.timestamp=Date.now());return l},write:(g,h,m,p)=>{for(var l=0;l<p;l++)try{e(h[m+l])}catch(n){throw new N.u(29);}p&&(g.node.timestamp=Date.now());
return l}});return N.ua(a,b,f)},eb:a=>{if(a.Ha||a.Mb||a.link||a.G)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(t)try{a.G=Wa(t(a.url)),a.K=a.G.length}catch(b){throw new N.u(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},kc:(a,b,c,e,f)=>{function g(){this.Ia=!1;this.wa=
[]}g.prototype.get=function(l){if(!(l>this.length-1||0>l)){var n=l%this.chunkSize;return this.ib(l/this.chunkSize|0)[n]}};g.prototype.nb=function(l){this.ib=l};g.prototype.Ta=function(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var n=Number(l.getResponseHeader("Content-length")),r,u=(r=l.getResponseHeader("Accept-Ranges"))&&"bytes"===r;l=(r=l.getResponseHeader("Content-Encoding"))&&
"gzip"===r;var w=1048576;u||(w=n);var x=this;x.nb(R=>{var aa=R*w,S=(R+1)*w-1;S=Math.min(S,n-1);if("undefined"==typeof x.wa[R]){var Ab=x.wa;if(aa>S)throw Error("invalid range ("+aa+", "+S+") or no bytes requested!");if(S>n-1)throw Error("only "+n+" bytes available! programmer error!");var z=new XMLHttpRequest;z.open("GET",c,!1);n!==w&&z.setRequestHeader("Range","bytes="+aa+"-"+S);z.responseType="arraybuffer";z.overrideMimeType&&z.overrideMimeType("text/plain; charset=x-user-defined");z.send(null);
if(!(200<=z.status&&300>z.status||304===z.status))throw Error("Couldn't load "+c+". Status: "+z.status);aa=void 0!==z.response?new Uint8Array(z.response||[]):Wa(z.responseText||"");Ab[R]=aa}if("undefined"==typeof x.wa[R])throw Error("doXHR failed!");return x.wa[R]});if(l||!n)w=n=1,w=n=this.ib(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.rb=n;this.qb=w;this.Ia=!0};if("undefined"!=typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new g;Object.defineProperties(h,{length:{get:function(){this.Ia||this.Ta();return this.rb}},chunkSize:{get:function(){this.Ia||this.Ta();return this.qb}}});h={Ha:!1,G:h}}else h={Ha:!1,url:c};var m=N.yb(a,b,h,e,f);h.G?m.G=h.G:h.url&&(m.G=null,m.url=h.url);Object.defineProperties(m,{K:{get:function(){return this.G.length}}});var p={};Object.keys(m.H).forEach(l=>{var n=m.H[l];p[l]=function(){N.eb(m);return n.apply(null,arguments)}});p.read=(l,n,r,u,w)=>{N.eb(m);l=l.node.G;if(w>=l.length)return 0;
u=Math.min(l.length-w,u);if(l.slice)for(var x=0;x<u;x++)n[r+x]=l[w+x];else for(x=0;x<u;x++)n[r+x]=l.get(w+x);return u};m.H=p;return m},mc:(a,b,c,e,f,g,h,m,p,l)=>{function n(u){function w(x){l&&l();m||N.Xa(a,b,x,e,f,p);g&&g();Fa()}V.pc(u,r,w,()=>{h&&h();Fa()})||w(u)}var r=b?T(Q(a,b)):a;Ea();"string"==typeof c?Za(c,u=>n(u),h):n(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Ra:()=>"EM_FS_"+window.location.pathname,pa:20,N:"FILE_DATA",wc:(a,b,c)=>
{b=b||(()=>{});c=c||(()=>{});var e=N.indexedDB();try{var f=e.open(N.Ra(),N.pa)}catch(g){return c(g)}f.onupgradeneeded=()=>{ka("creating db");f.result.createObjectStore(N.N)};f.onsuccess=()=>{var g=f.result.transaction([N.N],"readwrite"),h=g.objectStore(N.N),m=0,p=0,l=a.length;a.forEach(n=>{n=h.put(N.ya(n).object.G,n);n.onsuccess=()=>{m++;m+p==l&&(0==p?b():c())};n.onerror=()=>{p++;m+p==l&&(0==p?b():c())}});g.onerror=c};f.onerror=c},qc:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=N.indexedDB();try{var f=
e.open(N.Ra(),N.pa)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=()=>{var g=f.result;try{var h=g.transaction([N.N],"readonly")}catch(r){c(r);return}var m=h.objectStore(N.N),p=0,l=0,n=a.length;a.forEach(r=>{var u=m.get(r);u.onsuccess=()=>{N.ya(r).exists&&N.unlink(r);N.Xa(Qa(r),P(r),u.result,!0,!0,!0);p++;p+l==n&&(0==l?b():c())};u.onerror=()=>{l++;p+l==n&&(0==l?b():c())}});h.onerror=c};f.onerror=c}},$a=void 0;function W(){$a+=4;return I[$a-4>>2]}
function X(a){a=N.da(a);if(!a)throw new N.u(8);return a}var ab=[],bb=0;function cb(){for(var a=Y.length-1;0<=a;--a)db(a);Y=[];eb=[]}var eb=[];function fb(){if(bb&&gb.sb)for(var a=0;a<eb.length;++a){var b=eb[a];eb.splice(a,1);--a;b.xc.apply(null,b.jc)}}var Y=[];function db(a){var b=Y[a];b.target.removeEventListener(b.ga,b.Db,b.Qa);Y.splice(a,1)}
function hb(a){function b(e){++bb;gb=a;fb();a.jb(e);fb();--bb}if(a.Ua)a.Db=b,a.target.addEventListener(a.ga,b,a.Qa),Y.push(a),ib||(Aa.push(cb),ib=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].ga==a.ga&&db(c--)}var ib,gb,jb,kb,lb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function mb(a){a=2<a?oa(a):a;return lb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}
function nb(a,b,c,e){jb||(jb=ob(176));a={target:mb(a),sb:!0,ga:"keydown",Ua:e,jb:function(f){var g=jb;wa[g>>3]=f.timeStamp;var h=g>>2;I[h+2]=f.location;I[h+3]=f.ctrlKey;I[h+4]=f.shiftKey;I[h+5]=f.altKey;I[h+6]=f.metaKey;I[h+7]=f.repeat;I[h+8]=f.charCode;I[h+9]=f.keyCode;I[h+10]=f.which;D(f.key||"",E,g+44,32);D(f.code||"",E,g+76,32);D(f.char||"",E,g+108,32);D(f.locale||"",E,g+140,32);pb.apply(null,[e,2,g,b])&&f.preventDefault()},Qa:c};hb(a)}
function qb(a,b,c,e){kb||(kb=ob(36));a=mb(a);hb({target:a,ga:"resize",Ua:e,jb:function(f){f=f||event;if(f.target==a){var g=document.body;if(g){var h=kb;I[h>>2]=f.detail;I[h+4>>2]=g.clientWidth;I[h+8>>2]=g.clientHeight;I[h+12>>2]=innerWidth;I[h+16>>2]=innerHeight;I[h+20>>2]=outerWidth;I[h+24>>2]=outerHeight;I[h+28>>2]=pageXOffset;I[h+32>>2]=pageYOffset;pb.apply(null,[e,10,h,b])&&f.preventDefault()}}},Qa:c})}function rb(a){if(!C)try{a()}catch(b){Na(b)}}
function sb(a,b){return setTimeout(function(){rb(a)},b)}function tb(a){try{a()}catch(b){B(b)}}var Z=0,G=null,ub=[],vb={},wb={},xb=0,yb=null,zb=[];function Bb(a){var b={},c;for(c in a)(function(e){var f=a[e];b[e]="function"==typeof f?function(){ub.push(e);try{return f.apply(null,arguments)}finally{C||(ub.pop()===e||B(void 0),G&&1===Z&&0===ub.length&&(Z=0,tb(d._asyncify_stop_unwind),"undefined"!=typeof Fibers&&Fibers.yc()))}}:f})(c);return b}
function ra(){return new Promise((a,b)=>{yb={resolve:a,reject:b}})}function Cb(){var a=ob(4108),b=a+12;I[a>>2]=b;I[a+4>>2]=b+4096;b=ub[0];var c=vb[b];void 0===c&&(c=xb++,vb[b]=c,wb[c]=b);I[a+8>>2]=c;return a}
function Db(a){if(!C)if(0===Z){var b=!1,c=!1;a(()=>{if(!C&&(b=!0,c)){Z=2;tb(()=>d._asyncify_start_rewind(G));"undefined"!=typeof V&&V.Ja.fb&&V.Ja.resume();var e=!1;try{var f=(0,d.asm[wb[I[G+8>>2]]])()}catch(m){f=m,e=!0}var g=!1;if(!G){var h=yb;h&&(yb=null,(e?h.reject:h.resolve)(f),g=!0)}if(e&&!g)throw f;}});c=!0;b||(Z=1,G=Cb(),tb(()=>d._asyncify_start_unwind(G)),"undefined"!=typeof V&&V.Ja.fb&&V.Ja.pause())}else 2===Z?(Z=0,tb(d._asyncify_stop_rewind),Eb(G),G=null,zb.forEach(e=>rb(e))):B("invalid state: "+
Z)}function Fb(a,b,c,e){a||(a=this);this.parent=a;this.J=a.J;this.ka=null;this.id=N.Tb++;this.name=b;this.mode=c;this.F={};this.H={};this.rdev=e}Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Mb:{get:function(){return N.L(this.mode)}},Ha:{get:function(){return N.ra(this.mode)}}});N.ob=Fb;N.cc();var V;
function Wa(a){var b=Array(ta(a)+1);a=D(a,b,0,b.length);b.length=a;return b}
var Hb={d:function(a,b,c){$a=c;try{var e=X(a);switch(b){case 0:var f=W();return 0>f?-28:N.open(e.path,e.flags,0,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=W(),e.flags|=f,0;case 5:return f=W(),va[f+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return I[Gb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof N||!(g instanceof N.u))throw g;return-g.O}},h:function(a,b,c){$a=c;try{var e=X(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?
0:-59;case 21519:if(!e.tty)return-59;var f=W();return I[f>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return f=W(),N.Ga(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:B("bad ioctl syscall "+b)}}catch(g){if("undefined"==typeof N||!(g instanceof N.u))throw g;return-g.O}},i:function(a,b,c,e){$a=e;try{b=oa(b);var f=b;if("/"===f[0])b=f;else{if(-100===a)var g=N.cwd();else{var h=N.da(a);if(!h)throw new N.u(8);g=h.path}if(0==f.length)throw new N.u(44);b=Q(g,f)}var m=e?W():
0;return N.open(b,c,m).fd}catch(p){if("undefined"==typeof N||!(p instanceof N.u))throw p;return-p.O}},a:function(a,b,c){ab.length=0;var e;for(c>>=2;e=E[b++];)(e=105>e)&&c&1&&c++,ab.push(e?wa[c++>>1]:I[c]),++c;return La[a].apply(null,ab)},m:function(){return Math.random()},b:function(){B("OOM")},j:function(a,b,c,e){nb(a,b,c,e);return 0},k:function(a,b,c,e){qb(a,b,c,e);return 0},c:function(a){Db(b=>sb(b,a))},e:function(a){try{var b=X(a);N.close(b);return 0}catch(c){if("undefined"==typeof N||!(c instanceof
N.u))throw c;return c.O}},g:function(a,b,c,e){try{a:{for(var f=X(a),g=a=0;g<c;g++){var h=I[b+(8*g+4)>>2],m=N.read(f,F,I[b+8*g>>2],h,void 0);if(0>m){var p=-1;break a}a+=m;if(m<h)break}p=a}I[e>>2]=p;return 0}catch(l){if("undefined"==typeof N||!(l instanceof N.u))throw l;return l.O}},l:function(a,b,c,e,f){try{var g=X(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;N.S(g,a,e);Ka=[g.position>>>0,(M=g.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|
0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];I[f>>2]=Ka[0];I[f+4>>2]=Ka[1];g.Da&&0===a&&0===e&&(g.Da=null);return 0}catch(h){if("undefined"==typeof N||!(h instanceof N.u))throw h;return h.O}},f:function(a,b,c,e){try{a:{for(var f=X(a),g=a=0;g<c;g++){var h=N.write(f,F,I[b+8*g>>2],I[b+(8*g+4)>>2],void 0);if(0>h){var m=-1;break a}a+=h}m=a}I[e>>2]=m;return 0}catch(p){if("undefined"==typeof N||!(p instanceof N.u))throw p;return p.O}}};
(function(){function a(g){g=g.exports;g=Bb(g);d.asm=g;la=d.asm.n;ua=g=la.buffer;d.HEAP8=F=new Int8Array(g);d.HEAP16=va=new Int16Array(g);d.HEAP32=I=new Int32Array(g);d.HEAPU8=E=new Uint8Array(g);d.HEAPU16=new Uint16Array(g);d.HEAPU32=new Uint32Array(g);d.HEAPF32=new Float32Array(g);d.HEAPF64=wa=new Float64Array(g);ya.unshift(d.asm.o);Fa()}function b(g){a(g.instance)}function c(g){return Ja().then(function(h){return WebAssembly.instantiate(h,e)}).then(function(h){return h}).then(g,function(h){y("failed to asynchronously prepare wasm: "+
h);B(h)})}var e={a:Hb};Ea();if(d.instantiateWasm)try{var f=d.instantiateWasm(e,a);return f=Bb(f)}catch(g){return y("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return A||"function"!=typeof WebAssembly.instantiateStreaming||Ga()||L.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.o).apply(null,arguments)};d._initpers=function(){return(d._initpers=d.asm.p).apply(null,arguments)};d._main=function(){return(d._main=d.asm.q).apply(null,arguments)};
var Gb=d.___errno_location=function(){return(Gb=d.___errno_location=d.asm.r).apply(null,arguments)},Eb=d._free=function(){return(Eb=d._free=d.asm.s).apply(null,arguments)},ob=d._malloc=function(){return(ob=d._malloc=d.asm.t).apply(null,arguments)},qa=d.stackSave=function(){return(qa=d.stackSave=d.asm.v).apply(null,arguments)},na=d.stackRestore=function(){return(na=d.stackRestore=d.asm.w).apply(null,arguments)},pa=d.stackAlloc=function(){return(pa=d.stackAlloc=d.asm.x).apply(null,arguments)},pb=d.dynCall_iiii=
function(){return(pb=d.dynCall_iiii=d.asm.y).apply(null,arguments)},dynCall_v=d.dynCall_v=function(){return(dynCall_v=d.dynCall_v=d.asm.z).apply(null,arguments)};d._asyncify_start_unwind=function(){return(d._asyncify_start_unwind=d.asm.A).apply(null,arguments)};d._asyncify_stop_unwind=function(){return(d._asyncify_stop_unwind=d.asm.B).apply(null,arguments)};d._asyncify_start_rewind=function(){return(d._asyncify_start_rewind=d.asm.C).apply(null,arguments)};
d._asyncify_stop_rewind=function(){return(d._asyncify_stop_rewind=d.asm.D).apply(null,arguments)};d.ccall=ma;d.FS=N;var Ib;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Jb(){Ib||Kb();Ib||(K=Jb)};
function Kb(){function a(){if(!Ib&&(Ib=!0,d.calledRun=!0,!C)){d.noFSInit||N.qa.Fa||N.qa();N.mb=!1;Ma(ya);Ma(za);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Lb){var b=d._main;try{var c=b(0,0);if(!noExitRuntime){if(d.onExit)d.onExit(c);C=!0}ca(c,new ja(c))}catch(e){Na(e)}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)b=d.postRun.shift(),Ba.unshift(b);Ma(Ba)}}if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ca();
Ma(xa);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=Kb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Lb=!0;d.noInitialRun&&(Lb=!1);Kb();
