
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in g)g.hasOwnProperty(k)&&(aa[k]=g[k]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,l=!1,fa=!1,ha=!1;ea="object"===typeof window;l="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!l;var q="",ia,ja,ka,la,ma,na;
if(fa)q=l?require("path").dirname(q)+"/":__dirname+"/",ia=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",
r),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ka=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||l)l?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},la=function(a){document.title=a};var pa=g.print||console.log.bind(console),u=g.printErr||console.warn.bind(console);for(k in aa)aa.hasOwnProperty(k)&&(g[k]=aa[k]);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function qa(a){ra||(ra={});ra[a]||(ra[a]=1,u(a))}
var ra,sa;g.wasmBinary&&(sa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&r("no native wasm support detected");var ta,ua=!1,va;function assert(a,b){a||r("Assertion failed: "+b)}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function v(a,b){return a?xa(w,a,b):""}
function ya(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function x(a,b,c){return ya(a,w,b,c)}
function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Aa(a){var b=za(a)+1,c=y(b);c&&ya(a,Ca,c,b);return c}function Da(a){var b=za(a)+1,c=Ea(b);ya(a,Ca,c,b);return c}var Fa,Ca,w,Ga,Ha,A,Ia,B,C;
function Ja(){var a=ta.buffer;Fa=a;g.HEAP8=Ca=new Int8Array(a);g.HEAP16=Ga=new Int16Array(a);g.HEAP32=A=new Int32Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=Ha=new Uint16Array(a);g.HEAPU32=Ia=new Uint32Array(a);g.HEAPF32=B=new Float32Array(a);g.HEAPF64=C=new Float64Array(a)}var D,Ka=[],La=[],Ma=[],Na=[],Oa=[];function Pa(){var a=g.preRun.shift();Ka.unshift(a)}var Qa=0,Ra=null,Sa=null;g.preloadedImages={};g.preloadedAudios={};
function r(a){if(g.onAbort)g.onAbort(a);u(a);ua=!0;va=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ta(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="kidchess.wasm";if(!Ta()){var Ua=F;F=g.locateFile?g.locateFile(Ua,q):q+Ua}function Va(){var a=F;try{if(a==F&&sa)return new Uint8Array(sa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){r(b)}}
function Wa(){if(!sa&&(ea||l)){if("function"===typeof fetch&&!F.startsWith("file://"))return fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return Va()});if(ja)return new Promise(function(a,b){ja(F,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Va()})}
var Xa={317148:function(a,b,c){g.SDL2||(g.SDL2={});var d=g.SDL2;d.Ye!==g.canvas&&(d.xe=g.createContext(g.canvas,!1,!0),d.Ye=g.canvas);if(d.w!==a||d.ff!==b||d.hf!==d.xe)d.image=d.xe.createImageData(a,b),d.w=a,d.ff=b,d.hf=d.xe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=A[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.uf!==a&&(d.Ze=new Int32Array(a.buffer),d.$e=new Uint8Array(a.buffer)),
a=d.Ze,c=a.length,a.set(A.subarray(b,b+c)),a=d.$e,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.xe.putImageData(d.image,0,0);return 0},318603:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof
CanvasPixelArray)for(n=b.length;m<n;){var p=A[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(A.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=y(c.length+1);x(c,d,c.length+1);return d},319592:function(a){g.canvas&&(g.canvas.style.cursor=v(a));return 0},319685:function(){g.canvas&&(g.canvas.style.cursor="none")},319754:function(){return screen.width},
319779:function(){return screen.height},319805:function(){return window.innerWidth},319835:function(){return window.innerHeight},319866:function(a){"undefined"!==typeof la&&la(v(a));return 0}};function Ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ef;"number"===typeof c?void 0===b.Fe?D.get(c)():D.get(c)(b.Fe):c(void 0===b.Fe?null:b.Fe)}}}var Za;fa?Za=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Za=dateNow:Za=function(){return performance.now()};
function $a(a,b){ab=a;bb=b;if(cb)if(db||(db=!0),0==a)G=function(){var d=Math.max(0,eb+b-Za())|0;setTimeout(fb,d)};else if(1==a)G=function(){gb(fb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);l?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}G=function(){setImmediate(fb)}}}
function hb(a,b,c,d,e){function f(){if(h<ib){if(!noExitRuntime)try{jb(va)}catch(m){if(!(m instanceof oa))throw m;}return!1}return!0}assert(!cb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");cb=a;kb=d;var h=ib;db=!1;fb=function(){if(!ua)if(0<lb.length){var m=Date.now(),n=lb.shift();n.ef(n.Fe);if(mb){var p=mb,t=0==p%1?p-1:Math.floor(p);mb=n.tf?t:(8*p+(t+.5))/
9}console.log('main loop blocker "'+n.name+'" took '+(Date.now()-m)+" ms");g.setStatus&&(m=g.statusMessage||"Please wait...",n=mb,p=nb.vf,n?n<p?g.setStatus(m+" ("+(p-n)+"/"+p+")"):g.setStatus(m):g.setStatus(""));f()&&setTimeout(fb,0)}else f()&&(ob=ob+1|0,1==ab&&1<bb&&0!=ob%bb?G():(0==ab&&(eb=Za()),ua||g.preMainLoop&&!1===g.preMainLoop()||(pb(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.mf&&SDL.audio.mf(),G())))};e||(b&&0<b?$a(0,1E3/b):$a(1,1),G());if(c)throw"unwind";
}function pb(a){if(!ua)try{a()}catch(b){if(!(b instanceof oa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&u("exception thrown: "+[b,b.stack]),b;}}var db=!1,G=null,ib=0,cb=null,kb=0,ab=0,bb=0,ob=0,lb=[],nb={},eb,fb,mb,qb=!1,rb=!1,sb=[];
function tb(){function a(){rb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!ub){ub=!0;try{vb=!0}catch(c){vb=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}wb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:vb?null:console.log("warning: no BlobBuilder");
xb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Te||"undefined"!==typeof xb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Te=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Te&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(vb)try{h=new Blob([c],{type:zb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:zb(d)}))}catch(p){qa("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new wb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=xb.createObjectURL(h),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);g.preloadedImages[d]=p;xb.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});g.preloadPlugins.push({canHandle:function(c){return!g.Af&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(E){n||(n=!0,g.preloadedAudios[d]=E,e&&e(c))}function m(){n||(n=!0,g.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(vb){try{var p=new Blob([c],{type:zb(d)})}catch(E){return m()}p=xb.createObjectURL(p);var t=new Audio;t.addEventListener("canplaythrough",function(){h(t)},!1);t.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var E="",P=0,z=0,
Ba=0;Ba<c.length;Ba++)for(P=P<<8|c[Ba],z+=8;6<=z;){var yb=P>>z-6&63;z-=6;E+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[yb]}2==z?(E+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&3)<<4],E+="=="):4==z&&(E+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&15)<<2],E+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+E;h(t)}};t.src=p;Ab(function(){h(t)})}else return m()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||
b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,
!1),g.elementPointerLock&&b.addEventListener("click",function(c){!rb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Bb(a,b,c,d){if(b&&g.xe&&a==g.canvas)return g.xe;var e;if(b){var f={antialias:!1,alpha:!1,Se:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof Cb&&(e=Db(a,f)))var m=H[e].Be}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof I,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.xe=m,b&&Eb(e),g.qf=b,sb.forEach(function(n){n()}),tb());return m}var Fb=!1,Gb=void 0,Hb=void 0;
function Ib(a,b){function c(){qb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Jb,Gb&&d.requestPointerLock(),qb=!0,Hb?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Ia[SDL.screen>>2]|8388608),Kb(g.canvas),Lb()):Kb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Hb?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Ia[SDL.screen>>2]&
-8388609),Kb(g.canvas),Lb()):Kb(d));if(g.onFullScreen)g.onFullScreen(qb);if(g.onFullscreen)g.onFullscreen(qb)}Gb=a;Hb=b;"undefined"===typeof Gb&&(Gb=!0);"undefined"===typeof Hb&&(Hb=!1);var d=g.canvas;Fb||(Fb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Jb(){if(!qb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Mb=0;function gb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Mb)Mb=b+1E3/60;else for(;b+2>=Mb;)Mb+=1E3/60;setTimeout(a,Math.max(Mb-b,0))}}function Ab(a){setTimeout(function(){pb(a)},1E4)}
function zb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Nb=[];function Lb(){var a=g.canvas;Nb.forEach(function(b){b(a.width,a.height)})}
function Kb(a,b,c){b&&c?(a.rf=b,a.gf=c):(b=a.rf,c=a.gf);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Hb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ub,vb,wb,xb,J=12288,Ob=!1,Pb=0,Qb=0,Rb=0,K={alpha:!1,depth:!1,stencil:!1,antialias:!1},Sb={},Tb;function Ub(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Vb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Wb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Xb=1,L=[],M=[],Yb=[],Zb=[],N=[],O=[],Q=[],H=[],R=[],$b={},ac=4;
function S(a){bc||(bc=a)}function cc(a){for(var b=Xb++,c=a.length;c<b;c++)a[c]=null;return b}function dc(a,b,c){for(var d="",e=0;e<a;++e){var f=c?A[c+4*e>>2]:-1;d+=v(A[b+4*e>>2],0>f?void 0:f)}return d}function Db(a,b){a.Qe||(a.Qe=a.getContext,a.getContext=function(d,e){e=a.Qe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ec(c,b):0}
function ec(a,b){var c=cc(H),d={wf:c,attributes:b,version:b.Se,Be:a};a.canvas&&(a.canvas.Ee=d);H[c]=d;("undefined"===typeof b.bf||b.bf)&&fc(d);return c}function Eb(a){hc=H[a];g.xe=I=hc&&hc.Be}function fc(a){a||(a=hc);if(!a.jf){a.jf=!0;var b=a.Be;Ub(b);Vb(b);Wb(b);b.ve=b.getExtension("EXT_disjoint_timer_query");b.zf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Cb={},bc,hc,ic=[],jc=0;
function kc(){for(var a=T.length-1;0<=a;--a)lc(a);T=[];U=[]}var U=[];function mc(a,b,c){function d(h,m){if(h.length!=m.length)return!1;for(var n in h)if(h[n]!=m[n])return!1;return!0}for(var e in U){var f=U[e];if(f.Me==a&&d(f.Ne,c))return}U.push({Me:a,Ue:b,Ne:c});U.sort(function(h,m){return h.Ue<m.Ue})}function nc(a){for(var b=0;b<U.length;++b)U[b].Me==a&&(U.splice(b,1),--b)}function oc(){if(jc&&pc.Ce)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.Me.apply(null,b.Ne)}}var T=[];
function lc(a){var b=T[a];b.target.removeEventListener(b.se,b.cf,b.te);T.splice(a,1)}function V(a){function b(d){++jc;pc=a;oc();a.we(d);oc();--jc}if(a.ue)a.cf=b,a.target.addEventListener(a.se,b,a.te),T.push(a),qc||(Na.push(kc),qc=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].se==a.se&&lc(c--)}function rc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function sc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var tc={},qc,pc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc={},Hc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function W(a){a=2<a?v(a):a;return Hc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function Ic(a){var b=Jc(),c=Ea(8),d=c+4,e=Ea(a.id.length+1);x(a.id,e,a.id.length+1);if(a=W(e))A[c>>2]=a.width,A[d>>2]=a.height;c=[A[c>>2],A[d>>2]];Kc(b);return c}function Lc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Mc(a,b,c){if(a.sf){var d=Jc(),e=Ea(a.id.length+1);x(a.id,e,a.id.length+1);Lc(e,b,c);Kc(d)}else a.width=b,a.height=c}
function Nc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Mc(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=t,a.style.paddingTop=E,a.style.paddingBottom=P,a.style.marginLeft=z,a.style.marginRight=
Ba,a.style.marginTop=yb,a.style.marginBottom=vd,document.body.style.margin=wd,document.documentElement.style.overflow=xd,document.body.scroll=yd,a.style.Re=zd,a.Ee&&a.Ee.Be.viewport(0,0,d,e),Gc.Ge&&D.get(Gc.Ge)(37,0,Gc.Oe))}var c=Ic(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,E=a.style.paddingTop,P=a.style.paddingBottom,z=a.style.marginLeft,Ba=a.style.marginRight,yb=a.style.marginTop,
vd=a.style.marginBottom,wd=document.body.style.margin,xd=document.documentElement.style.overflow,yd=document.body.scroll,zd=a.style.Re;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Oc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Pc(a){return 0>Hc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Qc(a,b){if(0!=b.Le||0!=b.Ke){Nc(a);var c=b.nf?innerWidth:screen.width,d=b.nf?innerHeight:screen.height,e=Pc(a),f=e.width;e=e.height;var h=Ic(a),m=h[0];h=h[1];3==b.Le?(Oc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Le&&(c*h<m*d?(f=h*c/m,Oc(a,(d-f)/2,0),d=f):(f=m*d/h,Oc(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.df&&(a.style.Re="pixelated");
f=2==b.Ke?devicePixelRatio:1;0!=b.Ke&&(c=c*f|0,d=d*f|0,Mc(a,c,d),a.Ee&&a.Ee.Be.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return sc()?-3:-1;Gc=b;b.Ge&&D.get(b.Ge)(37,0,b.Oe);return 0}function Rc(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.He)a.He();else return document.body.requestPointerLock||document.body.He?-3:-1;return 0}
function Sc(a,b){C[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)C[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)C[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)A[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];A[a+1296>>2]=b.connected;A[a+1300>>2]=b.index;A[a+8>>2]=b.axes.length;A[a+12>>2]=b.buttons.length;x(b.id,a+1304,64);x(b.mapping,a+1368,64)}var Tc=[];
function Uc(a,b,c,d){for(var e=0;e<a;e++){var f=I[c](),h=f&&cc(d);f?(f.name=h,d[h]=f):S(1282);A[b+4*e>>2]=h}}function Vc(a,b,c,d,e,f,h,m){b=M[b];if(a=I[a](b,c))d=m&&x(a.name,m,d),e&&(A[e>>2]=d),f&&(A[f>>2]=a.size),h&&(A[h>>2]=a.type)}function Wc(a,b){Ia[a>>2]=b;Ia[a+4>>2]=(b-Ia[a>>2])/4294967296}
function Xc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&S(1280);return;case 36345:d=0;break;case 34466:var e=I.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=I.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":S(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:S(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:A[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:Ca[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){S(1280);u("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:S(1280);u("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Wc(b,
d);break;case 0:A[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:Ca[b>>0]=d?1:0}}else S(1281)}function Yc(a){var b=za(a)+1,c=y(b);x(a,c,b);return c}function Zc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function $c(a){var b=a.De,c=a.Je,d;if(!b)for(a.De=b={},a.Xe={},d=0;d<I.getProgramParameter(a,35718);++d){var e=I.getActiveUniform(a,d);var f=e.name;e=e.size;var h=Zc(f);h=0<h?f.slice(0,h):f;var m=a.Ie;a.Ie+=e;c[h]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Xe[m++]=h}}
function X(a){var b=I.Pe;if(b){var c=b.De[a];"number"===typeof c&&(b.De[a]=c=I.getUniformLocation(b,b.Xe[a]+(0<c?"["+c+"]":"")));return c}S(1282)}function ad(a,b,c,d){if(c)if(a=M[a],$c(a),a=I.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:A[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:A[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else S(1281)}
function bd(a,b,c,d){if(c)if(a=I.getVertexAttrib(a,b),34975==b)A[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:A[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:A[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:A[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:A[c+4*b>>2]=Math.fround(a[b])}else S(1281)}
function cd(a,b,c,d,e){a-=5120;a=1==a?w:4==a?A:6==a?B:5==a||28922==a?Ia:Ha;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=ac;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var Y=[],dd=[];function ed(a,b){if(!sc())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?jc&&pc.Ce?Qc(a,b):b.af?(mc(Qc,1,[a,b]),1):-2:-3:-4}
function fd(a,b){var c={target:W(2),se:"beforeunload",ue:b,we:function(d){d=d||event;var e=D.get(b)(28,0,a);e&&(e=v(e));if(e)return d.preventDefault(),d.returnValue=e},te:!0};V(c)}function gd(a,b,c,d,e,f){vc||(vc=y(256));a={target:W(a),se:f,ue:d,we:function(h){h=h||event;var m=h.target.id?h.target.id:"",n=vc;x(rc(h.target),n+0,128);x(m,n+128,128);D.get(d)(e,n,b)&&h.preventDefault()},te:c};V(a)}
function hd(a,b,c,d,e){xc||(xc=y(280));V({target:a,se:e,ue:d,we:function(f){f=f||event;var h=xc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;A[h>>2]=n;A[h+4>>2]=sc();var p=n?m:wc,t=p&&p.id?p.id:"";x(rc(p),h+8,128);x(t,h+136,128);A[h+264>>2]=p?p.clientWidth:0;A[h+268>>2]=p?p.clientHeight:0;A[h+272>>2]=screen.width;A[h+276>>2]=screen.height;n&&(wc=m);D.get(d)(19,h,b)&&f.preventDefault()},te:c})}
function jd(a,b,c,d,e){yc||(yc=y(1432));b={target:W(2),Ce:!0,se:e,ue:c,we:function(f){f=f||event;var h=yc;Sc(h,f.gamepad);D.get(c)(d,h,a)&&f.preventDefault()},te:b};V(b)}
function kd(a,b,c,d,e,f){zc||(zc=y(164));a={target:W(a),Ce:!0,se:f,ue:d,we:function(h){var m=zc,n=m>>2;A[n]=h.location;A[n+1]=h.ctrlKey;A[n+2]=h.shiftKey;A[n+3]=h.altKey;A[n+4]=h.metaKey;A[n+5]=h.repeat;A[n+6]=h.charCode;A[n+7]=h.keyCode;A[n+8]=h.which;x(h.key||"",m+36,32);x(h.code||"",m+68,32);x(h.char||"",m+100,32);x(h.locale||"",m+132,32);D.get(d)(e,m,b)&&h.preventDefault()},te:c};V(a)}
function ld(a,b,c){a>>=2;A[a]=b.screenX;A[a+1]=b.screenY;A[a+2]=b.clientX;A[a+3]=b.clientY;A[a+4]=b.ctrlKey;A[a+5]=b.shiftKey;A[a+6]=b.altKey;A[a+7]=b.metaKey;Ga[2*a+16]=b.button;Ga[2*a+17]=b.buttons;A[a+9]=b.movementX;A[a+10]=b.movementY;c=Pc(c);A[a+11]=b.clientX-c.left;A[a+12]=b.clientY-c.top}function md(a,b,c,d,e,f){Ac||(Ac=y(64));a=W(a);V({target:a,Ce:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,se:f,ue:d,we:function(h){h=h||event;ld(Ac,h,a);D.get(d)(e,Ac,b)&&h.preventDefault()},te:c})}
function nd(a,b,c,d,e){Bc||(Bc=y(260));V({target:a,se:e,ue:d,we:function(f){f=f||event;var h=Bc,m=document.pointerLockElement||document.pf||document.Cf||document.Bf;A[h>>2]=!!m;var n=m&&m.id?m.id:"";x(rc(m),h+4,128);x(n,h+132,128);D.get(d)(20,h,b)&&f.preventDefault()},te:c})}
function od(a,b,c,d){Cc||(Cc=y(36));a=W(a);V({target:a,se:"resize",ue:d,we:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var h=Cc;A[h>>2]=e.detail;A[h+4>>2]=f.clientWidth;A[h+8>>2]=f.clientHeight;A[h+12>>2]=innerWidth;A[h+16>>2]=innerHeight;A[h+20>>2]=outerWidth;A[h+24>>2]=outerHeight;A[h+28>>2]=pageXOffset;A[h+32>>2]=pageYOffset;D.get(d)(10,h,b)&&e.preventDefault()}}},te:c})}
function pd(a,b,c,d,e,f){Dc||(Dc=y(1684));a=W(a);V({target:a,Ce:"touchstart"==f||"touchend"==f,se:f,ue:d,we:function(h){for(var m={},n=h.touches,p=0;p<n.length;++p){var t=n[p];m[t.identifier]=t}n=h.changedTouches;for(p=0;p<n.length;++p)t=n[p],t.kf=1,m[t.identifier]=t;n=h.targetTouches;for(p=0;p<n.length;++p)m[n[p].identifier].lf=1;n=Dc;t=n>>2;A[t+1]=h.ctrlKey;A[t+2]=h.shiftKey;A[t+3]=h.altKey;A[t+4]=h.metaKey;t+=5;var E=Pc(a),P=0;for(p in m){var z=m[p];A[t]=z.identifier;A[t+1]=z.screenX;A[t+2]=z.screenY;
A[t+3]=z.clientX;A[t+4]=z.clientY;A[t+5]=z.pageX;A[t+6]=z.pageY;A[t+7]=z.kf;A[t+8]=z.lf;A[t+9]=z.clientX-E.left;A[t+10]=z.clientY-E.top;t+=13;if(31<++P)break}A[n>>2]=P;D.get(d)(e,n,b)&&h.preventDefault()},te:c})}function qd(a,b,c){var d=Hc[1];Ec||(Ec=y(8));V({target:d,se:"visibilitychange",ue:c,we:function(e){e=e||event;var f=Ec,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);A[f>>2]=document.hidden;A[f+4>>2]=h;D.get(c)(21,f,a)&&e.preventDefault()},te:b})}
function rd(a,b,c,d){Fc||(Fc=y(96));V({target:a,Ce:!0,se:"wheel",ue:d,we:function(e){e=e||event;var f=Fc;ld(f,e,a);C[f+64>>3]=e.deltaX;C[f+72>>3]=e.deltaY;C[f+80>>3]=e.deltaZ;A[f+88>>2]=e.deltaMode;D.get(d)(9,f,b)&&e.preventDefault()},te:c})}var sd={};
function td(){if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in sd)void 0===sd[b]?delete a[b]:a[b]=sd[b];var c=[];for(b in a)c.push(b+"="+a[b]);ud=c}return ud}var ud,Ad=[null,[],[]];
function Bd(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){r("randomDevice")}}function Cd(a,b){Cd.Ve||(Cd.Ve=Bd());for(var c=0;c<b;c++)Ca[a+c>>0]=Cd.Ve();return 0}g.requestFullscreen=function(a,b){Ib(a,b)};g.requestAnimationFrame=function(a){gb(a)};
g.setCanvasSize=function(a,b,c){Kb(g.canvas,a,b);c||Lb()};g.pauseMainLoop=function(){G=null;ib++};g.resumeMainLoop=function(){ib++;var a=ab,b=bb,c=cb;cb=null;hb(c,0,!1,kb,!0);$a(a,b);G()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Bb(a,b,c,d)};for(var I,Z=0;32>Z;++Z)Tc.push(Array(Z));var Dd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Dd.subarray(0,Z+1);
var Ed=new Int32Array(288);for(Z=0;288>Z;++Z)dd[Z]=Ed.subarray(0,Z+1);
var Gd={a:function(a,b,c,d){r("Assertion failed: "+v(a)+", at: "+[b?v(b):"unknown filename",c,d?v(d):"unknown function"])},qa:function(){r()},i:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Za();else return A[Fd()>>2]=28,-1;A[b>>2]=a/1E3|0;A[b+4>>2]=a%1E3*1E6|0;return 0},oa:function(){r("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},wa:function(a){if(12448==a)return J=12288,1;J=12300;return 0},Ia:function(a,
b,c,d,e){if(62E3!=a)J=12296,c=0;else{if(b)for(;;){a=A[b>>2];if(12321==a)K.alpha=0<A[b+4>>2];else if(12325==a)K.depth=0<A[b+4>>2];else if(12326==a)K.stencil=0<A[b+4>>2];else if(12337==a)a=A[b+4>>2],K.antialias=0<a;else if(12338==a)a=A[b+4>>2],K.antialias=1==a;else if(12544==a)K.xf=12547!=A[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(A[e>>2]=1),c&&0<d&&(A[c>>2]=62002),J=12288,c=1):(J=12300,c=0)}return c},Ga:function(a,b,c,d){if(62E3!=a)return J=12296,0;for(a=1;;){b=A[d>>2];if(12440==b)a=A[d+4>>
2];else if(12344==b)break;else return J=12292,0;d+=8}if(2!=a)return J=12293,0;K.Se=a-1;K.yf=0;Tb=Db(g.canvas,K);if(0!=Tb)return J=12288,Eb(Tb),g.qf=!0,sb.forEach(function(e){e()}),Eb(null),62004;J=12297;return 0},Ea:function(a,b){if(62E3!=a)return J=12296,0;if(62002!=b)return J=12293,0;J=12288;return 62006},Fa:function(a,b){if(62E3!=a)return J=12296,0;if(62004!=b)return J=12294,0;a=Tb;hc===H[a]&&(hc=null);if("object"===typeof tc)for(var c=H[a].Be.canvas,d=0;d<T.length;++d)T[d].target!=c||lc(d--);
H[a]&&H[a].Be.canvas&&(H[a].Be.canvas.Ee=void 0);H[a]=null;J=12288;Pb==b&&(Pb=0);return 1},Da:function(a,b){if(62E3!=a)return J=12296,0;if(62006!=b)return J=12301,1;Qb==b&&(Qb=0);Rb==b&&(Rb=0);J=12288;return 1},Ha:function(a,b,c,d){if(62E3!=a)return J=12296,0;if(62002!=b)return J=12293,0;if(!d)return J=12300,0;J=12288;switch(c){case 12320:return A[d>>2]=K.alpha?32:24,1;case 12321:return A[d>>2]=K.alpha?8:0,1;case 12322:return A[d>>2]=8,1;case 12323:return A[d>>2]=8,1;case 12324:return A[d>>2]=8,1;
case 12325:return A[d>>2]=K.depth?24:0,1;case 12326:return A[d>>2]=K.stencil?8:0,1;case 12327:return A[d>>2]=12344,1;case 12328:return A[d>>2]=62002,1;case 12329:return A[d>>2]=0,1;case 12330:return A[d>>2]=4096,1;case 12331:return A[d>>2]=16777216,1;case 12332:return A[d>>2]=4096,1;case 12333:return A[d>>2]=0,1;case 12334:return A[d>>2]=0,1;case 12335:return A[d>>2]=12344,1;case 12337:return A[d>>2]=K.antialias?4:0,1;case 12338:return A[d>>2]=K.antialias?1:0,1;case 12339:return A[d>>2]=4,1;case 12340:return A[d>>
2]=12344,1;case 12341:case 12342:case 12343:return A[d>>2]=-1,1;case 12345:case 12346:return A[d>>2]=0,1;case 12347:return A[d>>2]=0,1;case 12348:return A[d>>2]=1;case 12349:case 12350:return A[d>>2]=0,1;case 12351:return A[d>>2]=12430,1;case 12352:return A[d>>2]=4,1;case 12354:return A[d>>2]=0,1;default:return J=12292,0}},V:function(){J=12288;return 62E3},ua:function(){return J},Ka:function(a,b,c){if(62E3==a)return b&&(A[b>>2]=1),c&&(A[c>>2]=4),Ob=!0,J=12288,1;J=12296;return 0},Ca:function(a,b,c,
d){if(62E3!=a)return J=12296,0;if(0!=d&&62004!=d)return J=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return J=12301,0;Eb(d?Tb:null);Pb=d;Rb=b;Qb=c;J=12288;return 1},va:function(a,b){if(62E3!=a)return J=12296,0;J=12288;if(Sb[b])return Sb[b];switch(b){case 12371:a=Aa("Emscripten");break;case 12372:a=Aa("1.4 Emscripten EGL");break;case 12373:a=Aa("");break;case 12429:a=Aa("OpenGL_ES");break;default:return J=12300,0}return Sb[b]=a},Ba:function(){if(Ob)if(g.xe)if(g.xe.isContextLost())J=12302;else return J=
12288,1;else J=12290;else J=12289;return 0},Aa:function(a,b){if(62E3!=a)return J=12296,0;0==b?$a(0,0):$a(1,b);J=12288;return 1},Ja:function(a){if(62E3!=a)return J=12296,0;Rb=Qb=Pb=0;Ob=!1;J=12288;return 1},xa:function(){J=12288;return 1},za:function(){J=12288;return 1},c:function(a,b,c){ic.length=0;var d;for(c>>=2;d=w[b++];)(d=105>d)&&c&1&&c++,ic.push(d?C[c++>>1]:A[c]),++c;return Xa[a].apply(null,ic)},Na:function(){G=null;ib++;cb=null},he:function(){if(!sc())return-1;nc(Qc);var a=Hc[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ta:function(){nc(Rc);if(document.exitPointerLock)document.exitPointerLock();else if(document.We)document.We();else return-1;return 0},m:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},g:function(a,b,c){a=W(a);if(!a)return-4;a=Pc(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},ma:function(a,b){if(0>a||a>=uc.length)return-5;if(!uc[a])return-7;Sc(b,uc[a]);
return 0},ge:function(){return uc.length},Od:function(a){I.activeTexture(a)},Md:function(a,b){I.attachShader(M[a],O[b])},ce:function(a,b){I.ve.beginQueryEXT(a,R[b])},Ld:function(a,b,c){I.bindAttribLocation(M[a],b,v(c))},Kd:function(a,b){I.bindBuffer(a,L[b])},Jd:function(a,b){I.bindFramebuffer(a,Yb[b])},Id:function(a,b){I.bindRenderbuffer(a,Zb[b])},Hd:function(a,b){I.bindTexture(a,N[b])},Wd:function(a){I.bindVertexArray(Q[a])},Gd:function(a,b,c,d){I.blendColor(a,b,c,d)},Fd:function(a){I.blendEquation(a)},
Ed:function(a,b){I.blendEquationSeparate(a,b)},Dd:function(a,b){I.blendFunc(a,b)},Cd:function(a,b,c,d){I.blendFuncSeparate(a,b,c,d)},Bd:function(a,b,c,d){I.bufferData(a,c?w.subarray(c,c+b):b,d)},Ad:function(a,b,c,d){I.bufferSubData(a,b,w.subarray(d,d+c))},zd:function(a){return I.checkFramebufferStatus(a)},yd:function(a){I.clear(a)},xd:function(a,b,c,d){I.clearColor(a,b,c,d)},wd:function(a){I.clearDepth(a)},vd:function(a){I.clearStencil(a)},ud:function(a,b,c,d){I.colorMask(!!a,!!b,!!c,!!d)},td:function(a){I.compileShader(O[a])},
sd:function(a,b,c,d,e,f,h,m){I.compressedTexImage2D(a,b,c,d,e,f,m?w.subarray(m,m+h):null)},rd:function(a,b,c,d,e,f,h,m,n){I.compressedTexSubImage2D(a,b,c,d,e,f,h,n?w.subarray(n,n+m):null)},qd:function(a,b,c,d,e,f,h,m){I.copyTexImage2D(a,b,c,d,e,f,h,m)},pd:function(a,b,c,d,e,f,h,m){I.copyTexSubImage2D(a,b,c,d,e,f,h,m)},od:function(){var a=cc(M),b=I.createProgram();b.name=a;b.Ae=b.ye=b.ze=0;b.Ie=1;M[a]=b;return a},nd:function(a){var b=cc(O);O[b]=I.createShader(a);return b},md:function(a){I.cullFace(a)},
ld:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=L[d];e&&(I.deleteBuffer(e),e.name=0,L[d]=null)}},kd:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=Yb[d];e&&(I.deleteFramebuffer(e),e.name=0,Yb[d]=null)}},jd:function(a){if(a){var b=M[a];b?(I.deleteProgram(b),b.name=0,M[a]=null):S(1281)}},ee:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=R[d];e&&(I.ve.deleteQueryEXT(e),R[d]=null)}},id:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Zb[d];e&&(I.deleteRenderbuffer(e),e.name=
0,Zb[d]=null)}},hd:function(a){if(a){var b=O[a];b?(I.deleteShader(b),O[a]=null):S(1281)}},gd:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=N[d];e&&(I.deleteTexture(e),e.name=0,N[d]=null)}},Vd:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];I.deleteVertexArray(Q[d]);Q[d]=null}},fd:function(a){I.depthFunc(a)},ed:function(a){I.depthMask(!!a)},dd:function(a,b){I.depthRange(a,b)},cd:function(a,b){I.detachShader(M[a],O[b])},bd:function(a){I.disable(a)},ad:function(a){I.disableVertexAttribArray(a)},
$c:function(a,b,c){I.drawArrays(a,b,c)},Rd:function(a,b,c,d){I.drawArraysInstanced(a,b,c,d)},Sd:function(a,b){for(var c=Tc[a],d=0;d<a;d++)c[d]=A[b+4*d>>2];I.drawBuffers(c)},_c:function(a,b,c,d){I.drawElements(a,b,c,d)},Qd:function(a,b,c,d,e){I.drawElementsInstanced(a,b,c,d,e)},Zc:function(a){I.enable(a)},Yc:function(a){I.enableVertexAttribArray(a)},be:function(a){I.ve.endQueryEXT(a)},Xc:function(){I.finish()},Wc:function(){I.flush()},Vc:function(a,b,c,d){I.framebufferRenderbuffer(a,b,c,Zb[d])},Uc:function(a,
b,c,d,e){I.framebufferTexture2D(a,b,c,N[d],e)},Tc:function(a){I.frontFace(a)},Sc:function(a,b){Uc(a,b,"createBuffer",L)},Qc:function(a,b){Uc(a,b,"createFramebuffer",Yb)},fe:function(a,b){for(var c=0;c<a;c++){var d=I.ve.createQueryEXT();if(!d){for(S(1282);c<a;)A[b+4*c++>>2]=0;break}var e=cc(R);d.name=e;R[e]=d;A[b+4*c>>2]=e}},Pc:function(a,b){Uc(a,b,"createRenderbuffer",Zb)},Oc:function(a,b){Uc(a,b,"createTexture",N)},Ud:function(a,b){Uc(a,b,"createVertexArray",Q)},Rc:function(a){I.generateMipmap(a)},
Nc:function(a,b,c,d,e,f,h){Vc("getActiveAttrib",a,b,c,d,e,f,h)},Mc:function(a,b,c,d,e,f,h){Vc("getActiveUniform",a,b,c,d,e,f,h)},Lc:function(a,b,c,d){a=I.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);A[c>>2]=e;for(b=0;b<e;++b)A[d+4*b>>2]=O.indexOf(a[b])},Kc:function(a,b){return I.getAttribLocation(M[a],v(b))},Jc:function(a,b){Xc(a,b,4)},Ic:function(a,b,c){c?A[c>>2]=I.getBufferParameter(a,b):S(1281)},Hc:function(){var a=I.getError()||bc;bc=0;return a},Fc:function(a,b){Xc(a,b,2)},Ec:function(a,
b,c,d){a=I.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;A[d>>2]=a},Dc:function(a,b){Xc(a,b,0)},Bc:function(a,b,c,d){a=I.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,d,b):0;c&&(A[c>>2]=b)},Cc:function(a,b,c){if(c)if(a>=Xb)S(1281);else if(a=M[a],35716==b)a=I.getProgramInfoLog(a),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.Ae)for(b=0;b<I.getProgramParameter(a,35718);++b)a.Ae=Math.max(a.Ae,
I.getActiveUniform(a,b).name.length+1);A[c>>2]=a.Ae}else if(35722==b){if(!a.ye)for(b=0;b<I.getProgramParameter(a,35721);++b)a.ye=Math.max(a.ye,I.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.ye}else if(35381==b){if(!a.ze)for(b=0;b<I.getProgramParameter(a,35382);++b)a.ze=Math.max(a.ze,I.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.ze}else A[c>>2]=I.getProgramParameter(a,b);else S(1281)},Yd:function(a,b,c){if(c){a=I.ve.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Wc(c,d)}else S(1281)},
_d:function(a,b,c){if(c){a=I.ve.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;A[c>>2]=d}else S(1281)},Xd:function(a,b,c){if(c){a=I.ve.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Wc(c,d)}else S(1281)},Zd:function(a,b,c){if(c){a=I.ve.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;A[c>>2]=d}else S(1281)},$d:function(a,b,c){c?A[c>>2]=I.ve.getQueryEXT(a,b):S(1281)},Ac:function(a,b,c){c?A[c>>2]=I.getRenderbufferParameter(a,b):S(1281)},yc:function(a,
b,c,d){a=I.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,d,b):0;c&&(A[c>>2]=b)},xc:function(a,b,c,d){a=I.getShaderPrecisionFormat(a,b);A[c>>2]=a.rangeMin;A[c+4>>2]=a.rangeMax;A[d>>2]=a.precision},wc:function(a,b,c,d){if(a=I.getShaderSource(O[a]))b=0<b&&d?x(a,d,b):0,c&&(A[c>>2]=b)},zc:function(a,b,c){c?35716==b?(a=I.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=I.getShaderSource(O[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=I.getShaderParameter(O[a],
b):S(1281)},vc:function(a){var b=$b[a];if(!b){switch(a){case 7939:b=I.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Yc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=I.getParameter(a))||S(1280);b=b&&Yc(b);break;case 7938:b=Yc("OpenGL ES 2.0 ("+I.getParameter(7938)+")");break;case 35724:b=I.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=
Yc(b);break;default:S(1280)}$b[a]=b}return b},uc:function(a,b,c){c?B[c>>2]=I.getTexParameter(a,b):S(1281)},tc:function(a,b,c){c?A[c>>2]=I.getTexParameter(a,b):S(1281)},qc:function(a,b){b=v(b);if(a=M[a]){$c(a);var c=a.De,d=0,e=b,f=Zc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Je[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||I.getUniformLocation(a,b)))return d}else S(1281);return-1},sc:function(a,b,c){ad(a,b,c,2)},rc:function(a,b,c){ad(a,b,c,0)},nc:function(a,b,c){c?A[c>>2]=I.getVertexAttribOffset(a,
b):S(1281)},pc:function(a,b,c){bd(a,b,c,2)},oc:function(a,b,c){bd(a,b,c,5)},mc:function(a,b){I.hint(a,b)},lc:function(a){return(a=L[a])?I.isBuffer(a):0},kc:function(a){return I.isEnabled(a)},jc:function(a){return(a=Yb[a])?I.isFramebuffer(a):0},ic:function(a){return(a=M[a])?I.isProgram(a):0},de:function(a){return(a=R[a])?I.ve.isQueryEXT(a):0},hc:function(a){return(a=Zb[a])?I.isRenderbuffer(a):0},gc:function(a){return(a=O[a])?I.isShader(a):0},fc:function(a){return(a=N[a])?I.isTexture(a):0},Td:function(a){return(a=
Q[a])?I.isVertexArray(a):0},ec:function(a){I.lineWidth(a)},dc:function(a){a=M[a];I.linkProgram(a);a.De=0;a.Je={}},cc:function(a,b){3317==a&&(ac=b);I.pixelStorei(a,b)},ac:function(a,b){I.polygonOffset(a,b)},ae:function(a,b){I.ve.queryCounterEXT(R[a],b)},$b:function(a,b,c,d,e,f,h){(h=cd(f,e,c,d,h))?I.readPixels(a,b,c,d,e,f,h):S(1280)},_b:function(){},Zb:function(a,b,c,d){I.renderbufferStorage(a,b,c,d)},Yb:function(a,b){I.sampleCoverage(a,!!b)},Xb:function(a,b,c,d){I.scissor(a,b,c,d)},Wb:function(){S(1280)},
Vb:function(a,b,c,d){b=dc(b,c,d);I.shaderSource(O[a],b)},Ub:function(a,b,c){I.stencilFunc(a,b,c)},Tb:function(a,b,c,d){I.stencilFuncSeparate(a,b,c,d)},Rb:function(a){I.stencilMask(a)},Qb:function(a,b){I.stencilMaskSeparate(a,b)},Pb:function(a,b,c){I.stencilOp(a,b,c)},Ob:function(a,b,c,d){I.stencilOpSeparate(a,b,c,d)},Nb:function(a,b,c,d,e,f,h,m,n){I.texImage2D(a,b,c,d,e,f,h,m,n?cd(m,h,d,e,n):null)},Mb:function(a,b,c){I.texParameterf(a,b,c)},Lb:function(a,b,c){I.texParameterf(a,b,B[c>>2])},Kb:function(a,
b,c){I.texParameteri(a,b,c)},Jb:function(a,b,c){I.texParameteri(a,b,A[c>>2])},Ib:function(a,b,c,d,e,f,h,m,n){var p=null;n&&(p=cd(m,h,e,f,n));I.texSubImage2D(a,b,c,d,e,f,h,m,p)},Hb:function(a,b){I.uniform1f(X(a),b)},Gb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);I.uniform1fv(X(a),d)},Fb:function(a,b){I.uniform1i(X(a),b)},Eb:function(a,b,c){if(288>=b)for(var d=dd[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);I.uniform1iv(X(a),
d)},Db:function(a,b,c){I.uniform2f(X(a),b,c)},Cb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);I.uniform2fv(X(a),d)},Bb:function(a,b,c){I.uniform2i(X(a),b,c)},Ab:function(a,b,c){if(144>=b)for(var d=dd[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);I.uniform2iv(X(a),d)},zb:function(a,b,c,d){I.uniform3f(X(a),b,c,d)},yb:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<
3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);I.uniform3fv(X(a),d)},xb:function(a,b,c,d){I.uniform3i(X(a),b,c,d)},wb:function(a,b,c){if(96>=b)for(var d=dd[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);I.uniform3iv(X(a),d)},vb:function(a,b,c,d,e){I.uniform4f(X(a),b,c,d,e)},ub:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=B;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];
d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=B.subarray(c>>2,c+16*b>>2);I.uniform4fv(X(a),d)},tb:function(a,b,c,d,e){I.uniform4i(X(a),b,c,d,e)},sb:function(a,b,c){if(72>=b)for(var d=dd[4*b-1],e=0;e<4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);I.uniform4iv(X(a),d)},rb:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>
2];else e=B.subarray(d>>2,d+16*b>>2);I.uniformMatrix2fv(X(a),!!c,e)},qb:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=9)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);I.uniformMatrix3fv(X(a),!!c,e)},pb:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=B;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=
f[m];e[h+1]=f[m+1];e[h+2]=f[m+2];e[h+3]=f[m+3];e[h+4]=f[m+4];e[h+5]=f[m+5];e[h+6]=f[m+6];e[h+7]=f[m+7];e[h+8]=f[m+8];e[h+9]=f[m+9];e[h+10]=f[m+10];e[h+11]=f[m+11];e[h+12]=f[m+12];e[h+13]=f[m+13];e[h+14]=f[m+14];e[h+15]=f[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);I.uniformMatrix4fv(X(a),!!c,e)},ob:function(a){a=M[a];I.useProgram(a);I.Pe=a},nb:function(a){I.validateProgram(M[a])},mb:function(a,b){I.vertexAttrib1f(a,b)},lb:function(a,b){I.vertexAttrib1f(a,B[b>>2])},kb:function(a,b,c){I.vertexAttrib2f(a,
b,c)},jb:function(a,b){I.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},ib:function(a,b,c,d){I.vertexAttrib3f(a,b,c,d)},hb:function(a,b){I.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},gb:function(a,b,c,d,e){I.vertexAttrib4f(a,b,c,d,e)},fb:function(a,b){I.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},Pd:function(a,b){I.vertexAttribDivisor(a,b)},eb:function(a,b,c,d,e,f){I.vertexAttribPointer(a,b,c,!!d,e,f)},cb:function(a,b,c,d){I.viewport(a,b,c,d)},u:function(){return 0},ie:function(a,b,c){return ed(a,
{Le:A[c>>2],Ke:A[c+4>>2],df:A[c+8>>2],af:b,Ge:A[c+12>>2],Oe:A[c+16>>2]})},U:function(a,b){a=W(a);return a?a.requestPointerLock||a.He?jc&&pc.Ce?Rc(a):b?(mc(Rc,2,[a]),1):-2:-1:-4},y:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ta.grow(Math.min(2147483648,d)-Fa.byteLength+65535>>>16);Ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},na:function(){return(uc=
navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},A:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;fd(a,b);return 0},M:function(a,b,c,d){gd(a,b,c,d,12,"blur");return 0},k:Lc,r:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},N:function(a,b,c,d){gd(a,b,c,d,13,"focus");return 0},D:function(a,b,c,d){if(!sc())return-1;a=W(a);if(!a)return-4;hd(a,b,c,d,"fullscreenchange");
hd(a,b,c,d,"webkitfullscreenchange");return 0},q:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;jd(a,b,c,26,"gamepadconnected");return 0},p:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;jd(a,b,c,27,"gamepaddisconnected");return 0},G:function(a,b,c,d){kd(a,b,c,d,2,"keydown");return 0},E:function(a,b,c,d){kd(a,b,c,d,1,"keypress");return 0},F:function(a,b,c,d){kd(a,b,c,d,3,"keyup");return 0},Ta:function(a,b,c){a=D.get(a);hb(a,b,c)},
S:function(a,b,c,d){md(a,b,c,d,5,"mousedown");return 0},Q:function(a,b,c,d){md(a,b,c,d,33,"mouseenter");return 0},P:function(a,b,c,d){md(a,b,c,d,34,"mouseleave");return 0},T:function(a,b,c,d){md(a,b,c,d,8,"mousemove");return 0},R:function(a,b,c,d){md(a,b,c,d,6,"mouseup");return 0},H:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.We||document.body.pf||document.body.He))return-1;a=W(a);if(!a)return-4;nd(a,b,c,d,"pointerlockchange");nd(a,b,c,d,"mozpointerlockchange");
nd(a,b,c,d,"webkitpointerlockchange");nd(a,b,c,d,"mspointerlockchange");return 0},C:function(a,b,c,d){od(a,b,c,d);return 0},I:function(a,b,c,d){pd(a,b,c,d,25,"touchcancel");return 0},K:function(a,b,c,d){pd(a,b,c,d,23,"touchend");return 0},J:function(a,b,c,d){pd(a,b,c,d,24,"touchmove");return 0},L:function(a,b,c,d){pd(a,b,c,d,22,"touchstart");return 0},B:function(a,b,c){if(!Hc[1])return-4;qd(a,b,c);return 0},O:function(a,b,c,d){a=W(a);return"undefined"!==typeof a.onwheel?(rd(a,b,c,d),0):-1},t:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},$a:function(a){for(var b=Za();Za()-b<a;);},Za:function(a,b){var c=0;td().forEach(function(d,e){var f=b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)Ca[e++>>0]=d.charCodeAt(f);Ca[e>>0]=0;c+=d.length+1});return 0},_a:function(a,b){var c=td();A[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A[b>>2]=d;return 0},bb:function(){return 0},Xa:function(){},ab:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var h=A[b+8*f>>2],m=A[b+(8*f+4)>>2],n=0;n<m;n++){var p=w[h+n],t=Ad[a];0===p||10===p?((1===
a?pa:u)(xa(t,0)),t.length=0):t.push(p)}e+=m}A[d>>2]=e;return 0},Ya:Cd,h:function(a){var b=Date.now();A[a>>2]=b/1E3|0;A[a+4>>2]=b%1E3*1E3|0;return 0},ja:function(a){I.activeTexture(a)},ba:function(a,b){I.attachShader(M[a],O[b])},n:function(a,b){I.bindBuffer(a,L[b])},j:function(a,b){I.bindTexture(a,N[b])},z:function(a){I.bindVertexArray(Q[a])},Ra:function(a){I.blendEquation(a)},db:function(a,b){I.blendEquationSeparate(a,b)},Wa:function(a,b){I.blendFunc(a,b)},fa:function(a,b,c,d){I.blendFuncSeparate(a,
b,c,d)},ia:function(a,b,c,d){I.bufferData(a,c?w.subarray(c,c+b):b,d)},sa:function(a){I.clear(a)},ya:function(a,b,c,d){I.clearColor(a,b,c,d)},ca:function(a){I.compileShader(O[a])},Va:function(){var a=cc(M),b=I.createProgram();b.name=a;b.Ae=b.ye=b.ze=0;b.Ie=1;M[a]=b;return a},ea:function(a){var b=cc(O);O[b]=I.createShader(a);return b},Y:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=L[d];e&&(I.deleteBuffer(e),e.name=0,L[d]=null)}},Sa:function(a){if(a){var b=M[a];b?(I.deleteProgram(b),b.name=
0,M[a]=null):S(1281)}},$:function(a){if(a){var b=O[a];b?(I.deleteShader(b),O[a]=null):S(1281)}},ka:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=N[d];e&&(I.deleteTexture(e),e.name=0,N[d]=null)}},Sb:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];I.deleteVertexArray(Q[d]);Q[d]=null}},aa:function(a,b){I.detachShader(M[a],O[b])},e:function(a){I.disable(a)},bc:function(a,b,c,d){I.drawElements(a,b,c,d)},f:function(a){I.enable(a)},w:function(a){I.enableVertexAttribArray(a)},Z:function(a,b){Uc(a,
b,"createBuffer",L)},pa:function(a,b){Uc(a,b,"createTexture",N)},Gc:function(a,b){Uc(a,b,"createVertexArray",Q)},Nd:function(a){I.generateMipmap(a)},x:function(a,b){return I.getAttribLocation(M[a],v(b))},b:function(a,b){Xc(a,b,0)},Ma:function(a,b,c,d){a=I.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,d,b):0;c&&(A[c>>2]=b)},W:function(a,b,c){if(c)if(a>=Xb)S(1281);else if(a=M[a],35716==b)a=I.getProgramInfoLog(a),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==
b){if(!a.Ae)for(b=0;b<I.getProgramParameter(a,35718);++b)a.Ae=Math.max(a.Ae,I.getActiveUniform(a,b).name.length+1);A[c>>2]=a.Ae}else if(35722==b){if(!a.ye)for(b=0;b<I.getProgramParameter(a,35721);++b)a.ye=Math.max(a.ye,I.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.ye}else if(35381==b){if(!a.ze)for(b=0;b<I.getProgramParameter(a,35382);++b)a.ze=Math.max(a.ze,I.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.ze}else A[c>>2]=I.getProgramParameter(a,b);else S(1281)},Oa:function(a,b,c,d){a=I.getShaderInfoLog(O[a]);
null===a&&(a="(unknown error)");b=0<b&&d?x(a,d,b):0;c&&(A[c>>2]=b)},X:function(a,b,c){c?35716==b?(a=I.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=I.getShaderSource(O[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=I.getShaderParameter(O[a],b):S(1281)},_:function(a,b){b=v(b);if(a=M[a]){$c(a);var c=a.De,d=0,e=b,f=Zc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Je[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||I.getUniformLocation(a,b)))return d}else S(1281);return-1},
ra:function(a,b){I.hint(a,b)},l:function(a){return I.isEnabled(a)},Ua:function(a){a=M[a];I.linkProgram(a);a.De=0;a.Je={}},ha:function(a,b,c,d){I.scissor(a,b,c,d)},da:function(a,b,c,d){b=dc(b,c,d);I.shaderSource(O[a],b)},la:function(a,b,c,d,e,f,h,m,n){I.texImage2D(a,b,c,d,e,f,h,m,n?cd(m,h,d,e,n):null)},o:function(a,b,c){I.texParameteri(a,b,c)},Qa:function(a,b){I.uniform1i(X(a),b)},Pa:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=B;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=f[m];e[h+1]=f[m+1];e[h+
2]=f[m+2];e[h+3]=f[m+3];e[h+4]=f[m+4];e[h+5]=f[m+5];e[h+6]=f[m+6];e[h+7]=f[m+7];e[h+8]=f[m+8];e[h+9]=f[m+9];e[h+10]=f[m+10];e[h+11]=f[m+11];e[h+12]=f[m+12];e[h+13]=f[m+13];e[h+14]=f[m+14];e[h+15]=f[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);I.uniformMatrix4fv(X(a),!!c,e)},ga:function(a){a=M[a];I.useProgram(a);I.Pe=a},v:function(a,b,c,d,e,f){I.vertexAttribPointer(a,b,c,!!d,e,f)},s:function(a,b,c,d){I.viewport(a,b,c,d)},d:function(){return 0},La:function(){return 0}};
(function(){function a(e){g.asm=e.exports;ta=g.asm.je;Ja();D=g.asm.re;La.unshift(g.asm.ke);Qa--;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa&&(e=Sa,Sa=null,e()))}function b(e){a(e.instance)}function c(e){return Wa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){u("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:Gd};Qa++;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return u("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return sa||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||F.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){u("wasm streaming compile failed: "+f);u("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.ke).apply(null,arguments)};var y=g._malloc=function(){return(y=g._malloc=g.asm.le).apply(null,arguments)};g._main=function(){return(g._main=g.asm.me).apply(null,arguments)};
var Fd=g.___errno_location=function(){return(Fd=g.___errno_location=g.asm.ne).apply(null,arguments)},Jc=g.stackSave=function(){return(Jc=g.stackSave=g.asm.oe).apply(null,arguments)},Kc=g.stackRestore=function(){return(Kc=g.stackRestore=g.asm.pe).apply(null,arguments)},Ea=g.stackAlloc=function(){return(Ea=g.stackAlloc=g.asm.qe).apply(null,arguments)},Hd;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function Id(){Hd||Jd();Hd||(Sa=Id)};
function Jd(a){function b(){if(!Hd&&(Hd=!0,g.calledRun=!0,!ua)){Ya(La);Ya(Ma);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Kd){var c=a,d=g._main;c=c||[];var e=c.length+1,f=Ea(4*(e+1));A[f>>2]=Da(ca);for(var h=1;h<e;h++)A[(f>>2)+h]=Da(c[h-1]);A[(f>>2)+e]=0;try{var m=d(e,f);jb(m,!0)}catch(n){n instanceof oa||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),u("exception thrown: "+c),da(1,n))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=
g.postRun.shift(),Oa.unshift(c);Ya(Oa)}}a=a||ba;if(!(0<Qa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Pa();Ya(Ka);0<Qa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Jd;function jb(a,b){va=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ua=!0}da(a,new oa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();
var Kd=!0;g.noInitialRun&&(Kd=!1);Jd();
