
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var k="",ka,la,ma,na,oa,pa;
if(ia)k=ha?require("path").dirname(k)+"/":__dirname+"/",ka=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?k=self.location.href:"undefined"!==typeof document&&document.currentScript&&(k=document.currentScript.src),k=0!==k.indexOf("blob:")?k.substr(0,k.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},na=function(a){document.title=a};var ra=h.print||console.log.bind(console),p=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function sa(a){ta||(ta={});ta[a]||(ta[a]=1,p(a))}var ta,ua;h.wasmBinary&&(ua=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&l("no native wasm support detected");
function va(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":r[a>>0]=b;break;case "i8":r[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":xa=[b>>>0,(v=b,1<=+Math.abs(v)?0<v?(Math.min(+Math.floor(v/4294967296),4294967295)|0)>>>0:~~+Math.ceil((v-+(~~v>>>0))/4294967296)>>>0:0)];u[a>>2]=xa[0];u[a+4>>2]=xa[1];break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;default:l("invalid type for setValue: "+c)}}var ya,za=!1,Aa;
function assert(a,b){a||l("Assertion failed: "+b)}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?Ca(B,a,b):""}
function Da(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function C(a,b,c){return Da(a,B,b,c)}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Fa(a){var b=Ea(a)+1,c=D(b);c&&Da(a,r,c,b);return c}function Ga(a){var b=Ea(a)+1,c=Ha(b);Da(a,r,c,b);return c}var Ia,r,B,wa,Ja,u,Ka,w,x;
function La(){var a=ya.buffer;Ia=a;h.HEAP8=r=new Int8Array(a);h.HEAP16=wa=new Int16Array(a);h.HEAP32=u=new Int32Array(a);h.HEAPU8=B=new Uint8Array(a);h.HEAPU16=Ja=new Uint16Array(a);h.HEAPU32=Ka=new Uint32Array(a);h.HEAPF32=w=new Float32Array(a);h.HEAPF64=x=new Float64Array(a)}var E,Ma=[],Na=[],Oa=[],Pa=[],Qa=[];function Ra(){var a=h.preRun.shift();Ma.unshift(a)}var Sa=0,Ta=null,Ua=null;h.preloadedImages={};h.preloadedAudios={};
function l(a){if(h.onAbort)h.onAbort(a);p(a);za=!0;Aa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Va(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="kidchess.wasm";if(!Va()){var Wa=G;G=h.locateFile?h.locateFile(Wa,k):k+Wa}function Xa(){var a=G;try{if(a==G&&ua)return new Uint8Array(ua);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){l(b)}}
function Ya(){if(!ua&&(fa||ha)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Xa()});if(la)return new Promise(function(a,b){la(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Xa()})}
var v,xa,bb={382400:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.Pf!==h.canvas&&(d.Le=h.createContext(h.canvas,!1,!0),d.Pf=h.canvas);if(d.w!==a||d.Xf!==b||d.Zf!==d.Le)d.image=d.Le.createImageData(a,b),d.w=a,d.Xf=b,d.Zf=d.Le;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.rg!==a&&(d.Qf=new Int32Array(a.buffer),d.Rf=new Uint8Array(a.buffer)),
a=d.Qf,c=a.length,a.set(u.subarray(b,b+c)),a=d.Rf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Le.putImageData(d.image,0,0);return 0},383855:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof
CanvasPixelArray)for(n=b.length;m<n;){var q=u[e];b[m]=q&255;b[m+1]=q>>8&255;b[m+2]=q>>16&255;b[m+3]=q>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);C(c,d,c.length+1);return d},384844:function(a){h.canvas&&(h.canvas.style.cursor=y(a));return 0},384937:function(){h.canvas&&(h.canvas.style.cursor="none")},385006:function(){return screen.width},
385031:function(){return screen.height},385057:function(){return window.innerWidth},385087:function(){return window.innerHeight},385118:function(a){"undefined"!==typeof na&&na(y(a));return 0},385213:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},385350:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},385574:function(a){"undefined"===
typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Ee||("undefined"!==typeof AudioContext?b.Ee=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Ee=new webkitAudioContext),b.Ee&&Za(b.Ee));return void 0===b.Ee?-1:0},386067:function(){return h.SDL2.Ee.sampleRate},386135:function(a,b,c,d){function e(){}function f(m){void 0!==g.capture.$e&&(clearTimeout(g.capture.$e),g.capture.$e=void 0);g.capture.df=g.Ee.createMediaStreamSource(m);g.capture.Ge=g.Ee.createScriptProcessor(b,
a,1);g.capture.Ge.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.mf=n.inputBuffer,$a(c,[d]))};g.capture.df.connect(g.capture.Ge);g.capture.Ge.connect(g.Ee.destination);g.capture.stream=m}var g=h.SDL2;g.capture.hf=g.Ee.createBuffer(a,b,g.Ee.sampleRate);g.capture.hf.getChannelData(0).fill(0);g.capture.$e=setTimeout(function(){g.capture.mf=g.capture.hf;$a(c,[d])},b/g.Ee.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},387787:function(a,b,c,d){var e=h.SDL2;e.audio.Ge=e.Ee.createScriptProcessor(b,0,a);e.audio.Ge.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.xf=f.outputBuffer,$a(c,[d]))};e.audio.Ge.connect(e.Ee.destination)},388197:function(a,b){for(var c=h.SDL2,d=c.capture.mf.numberOfChannels,e=0;e<d;++e){var f=c.capture.mf.getChannelData(e);
if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)va(a+4*g,f[g]);else for(g=0;g<b;++g)va(a+4*(g*d+e),f[g])}},388802:function(a,b){for(var c=h.SDL2,d=c.audio.xf.numberOfChannels,e=0;e<d;++e){var f=c.audio.xf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e<<2)>>
2]}},389282:function(a){var b=h.SDL2;if(a){void 0!==b.capture.$e&&clearTimeout(b.capture.$e);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.Ge&&(b.capture.Ge.onaudioprocess=function(){},b.capture.Ge.disconnect(),b.capture.Ge=void 0);void 0!==b.capture.df&&(b.capture.df.disconnect(),b.capture.df=void 0);void 0!==b.capture.hf&&(b.capture.hf=void 0);b.capture=void 0}else void 0!=
b.audio.Ge&&(b.audio.Ge.disconnect(),b.audio.Ge=void 0),b.audio=void 0;void 0!==b.Ee&&void 0===b.audio&&void 0===b.capture&&(b.Ee.close(),b.Ee=void 0)}};function cb(a,b,c){a.addEventListener(b,c,{once:!0})}function Za(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&cb(d,c,function(){"suspended"===a.state&&a.resume()})})})}
function db(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Wf;"number"===typeof c?void 0===b.bf?E.get(c)():E.get(c)(b.bf):c(void 0===b.bf?null:b.bf)}}}function $a(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else E.get(a).apply(null,b)}
function eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){l("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],Ye:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ye.flush(a.tty)},flush:function(a){a.tty.Ye.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ye.Df)throw new H(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ye.Df(a.tty)}catch(m){throw new H(29);}if(void 0===g&&0===e)throw new H(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ye.pf)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.Ye.pf(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},ob={Df:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.af?Buffer.af(256):new Buffer(256),d=0;try{d=oa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(Ea(b)+1);b=Da(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},pf:function(a,b){null===b||10===b?(ra(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(Ca(a.output,0)),a.output=[])}},pb={pf:function(a,b){null===b||10===b?(p(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(p(Ca(a.output,0)),a.output=[])}},
I={Me:null,Se:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.Me||(I.Me={dir:{node:{Ue:I.Be.Ue,Ne:I.Be.Ne,lookup:I.Be.lookup,ef:I.Be.ef,rename:I.Be.rename,unlink:I.Be.unlink,rmdir:I.Be.rmdir,readdir:I.Be.readdir,symlink:I.Be.symlink},stream:{We:I.Ce.We}},file:{node:{Ue:I.Be.Ue,Ne:I.Be.Ne},stream:{We:I.Ce.We,read:I.Ce.read,write:I.Ce.write,tf:I.Ce.tf,Gf:I.Ce.Gf,If:I.Ce.If}},link:{node:{Ue:I.Be.Ue,Ne:I.Be.Ne,readlink:I.Be.readlink},
stream:{}},wf:{node:{Ue:I.Be.Ue,Ne:I.Be.Ne},stream:qb}});c=rb(a,b,c,d);16384===(c.mode&61440)?(c.Be=I.Me.dir.node,c.Ce=I.Me.dir.stream,c.Ae={}):32768===(c.mode&61440)?(c.Be=I.Me.file.node,c.Ce=I.Me.file.stream,c.De=0,c.Ae=null):40960===(c.mode&61440)?(c.Be=I.Me.link.node,c.Ce=I.Me.link.stream):8192===(c.mode&61440)&&(c.Be=I.Me.wf.node,c.Ce=I.Me.wf.stream);c.timestamp=Date.now();a&&(a.Ae[b]=c,a.timestamp=c.timestamp);return c},tg:function(a){return a.Ae?a.Ae.subarray?a.Ae.subarray(0,a.De):new Uint8Array(a.Ae):
new Uint8Array(0)},zf:function(a,b){var c=a.Ae?a.Ae.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ae,a.Ae=new Uint8Array(b),0<a.De&&a.Ae.set(c.subarray(0,a.De),0))},gg:function(a,b){if(a.De!=b)if(0==b)a.Ae=null,a.De=0;else{var c=a.Ae;a.Ae=new Uint8Array(b);c&&a.Ae.set(c.subarray(0,Math.min(b,a.De)));a.De=b}},Be:{Ue:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?
b.size=4096:32768===(a.mode&61440)?b.size=a.De:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Of=4096;b.blocks=Math.ceil(b.size/b.Of);return b},Ne:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.gg(a,b.size)},lookup:function(){throw sb[44];},ef:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=
tb(b,c)}catch(f){}if(d)for(var e in d.Ae)throw new H(55);}delete a.parent.Ae[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ae[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ae[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=tb(a,b),d;for(d in c.Ae)throw new H(55);delete a.Ae[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ae)a.Ae.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},Ce:{read:function(a,b,c,d,e){var f=a.node.Ae;if(e>=a.node.De)return 0;a=Math.min(a.node.De-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===r.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ae||a.Ae.subarray)){if(f)return a.Ae=b.subarray(c,c+d),a.De=d;if(0===a.De&&0===e)return a.Ae=b.slice(c,c+d),a.De=
d;if(e+d<=a.De)return a.Ae.set(b.subarray(c,c+d),e),d}I.zf(a,e+d);if(a.Ae.subarray&&b.subarray)a.Ae.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ae[e+f]=b[c+f];a.De=Math.max(a.De,e+d);return d},We:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.De);if(0>b)throw new H(28);return b},tf:function(a,b,c){I.zf(a.node,b+c);a.node.De=Math.max(a.node.De,b+c)},Gf:function(a,b,c,d,e,f){if(0!==b)throw new H(28);if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.Ae;if(f&
2||a.buffer!==Ia){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);for(b=D(f);c<f;)r[b+c++]=0;c=b;if(!c)throw new H(48);r.set(a,c)}else d=!1,c=a.byteOffset;return{Ag:c,og:d}},If:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.Ce.write(a,b,0,d,c,!1);return 0}}},ub=null,vb={},wb=[],xb=1,yb=null,zb=!0,Ab={},H=null,sb={};
function Bb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Bf:!0,qf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.qf)throw new H(32);a=eb(a.split("/").filter(function(g){return!!g}),!1);var e=ub;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=tb(e,a[d]);c=fb(c+"/"+a[d]);e.ff&&(!f||f&&b.Bf)&&(e=e.ff.root);if(!f||b.Af)for(f=0;40960===(e.mode&61440);)if(e=Cb(c),c=jb(gb(c),e),e=Bb(c,{qf:b.qf}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Db(a){for(var b;;){if(a===a.parent)return a=a.Se.Hf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yb.length}function tb(a,b){var c;if(c=(c=Fb(a,"x"))?c:a.Be.lookup?0:2)throw new H(c,a);for(c=yb[Eb(a.id,b)];c;c=c.dg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Be.lookup(a,b)}
function rb(a,b,c,d){a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.dg=yb[b];return yb[b]=a}var Hb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Fb(a,b){if(zb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Jb(a,b){try{return tb(a,b),20}catch(c){}return Fb(a,"wx")}
function Kb(a){var b=4096;for(a=a||0;a<=b;a++)if(!wb[a])return a;throw new H(33);}function Lb(a,b){Mb||(Mb=function(){},Mb.prototype={});var c=new Mb,d;for(d in a)c[d]=a[d];a=c;b=Kb(b);a.fd=b;return wb[b]=a}var qb={open:function(a){a.Ce=vb[a.node.rdev].Ce;a.Ce.open&&a.Ce.open(a)},We:function(){throw new H(70);}};function mb(a,b){vb[a]={Ce:b}}
function Nb(a,b){var c="/"===b,d=!b;if(c&&ub)throw new H(10);if(!c&&!d){var e=Bb(b,{Bf:!1});b=e.path;e=e.node;if(e.ff)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,zg:{},Hf:b,cg:[]};a=a.Se(b);a.Se=b;b.root=a;c?ub=a:e&&(e.ff=b,e.Se&&e.Se.cg.push(b))}function Ob(a,b,c){var d=Bb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Jb(d,a);if(e)throw new H(e);if(!d.Be.ef)throw new H(63);return d.Be.ef(d,a,b,c)}function Pb(a){return Ob(a,16895,0)}
function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ob(a,b|8192,c)}function Rb(a,b){if(!jb(a))throw new H(44);var c=Bb(b,{parent:!0}).node;if(!c)throw new H(44);b=hb(b);var d=Jb(c,b);if(d)throw new H(d);if(!c.Be.symlink)throw new H(63);c.Be.symlink(c,b,a)}function Cb(a){a=Bb(a).node;if(!a)throw new H(44);if(!a.Be.readlink)throw new H(28);return jb(Db(a.parent),a.Be.readlink(a))}
function Sb(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Hb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=fb(a);try{f=Bb(a,{Af:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=Ob(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(f,Ib(b)):44))throw new H(c);if(b&512){c=f;c="string"===typeof c?Bb(c,{Af:!0}).node:c;if(!c.Be.Ne)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(e=Fb(c,"w"))throw new H(e);c.Be.Ne(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Lb({node:f,path:Db(f),flags:b,seekable:!0,position:0,Ce:f.Ce,jg:[],error:!1},d);d.Ce.open&&d.Ce.open(d);!h.logReadFiles||b&1||(Tb||(Tb={}),a in Tb||(Tb[a]=1,p("FS.trackingDelegate error on read file: "+
a)));try{Ab.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Ab.onOpenFile(a,f))}catch(g){p("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return d}function Ub(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.Ce.We)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.Ce.We(a,b,c);a.jg=[]}
function Vb(){H||(H=function(a,b){this.node=b;this.hg=function(c){this.Oe=c};this.hg(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){sb[a]=new H(a);sb[a].stack="<generic error, no stack>"}))}var Wb;function Xb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Yb(a,b,c){a=fb("/dev/"+a);var d=Xb(!!b,!!c);Zb||(Zb=64);var e=Zb++<<8|0;mb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,m,n){for(var q=0,t=0;t<n;t++){try{var A=b()}catch(F){throw new H(29);}if(void 0===A&&0===q)throw new H(6);if(null===A||void 0===A)break;q++;g[m+t]=A}q&&(f.node.timestamp=Date.now());return q},write:function(f,g,m,n){for(var q=0;q<n;q++)try{c(g[m+q])}catch(t){throw new H(29);}n&&(f.node.timestamp=Date.now());return q}});
Qb(a,d,e)}var Zb,$b={},Mb,Tb,ac=void 0;function bc(){ac+=4;return u[ac-4>>2]}function cc(a){a=wb[a];if(!a)throw new H(8);return a}var dc;ia?dc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?dc=dateNow:dc=function(){return performance.now()};
function ec(a,b){fc=a;hc=b;if(ic)if(jc||(jc=!0),0==a)kc=function(){var d=Math.max(0,lc+b-dc())|0;setTimeout(mc,d)};else if(1==a)kc=function(){nc(mc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}kc=function(){setImmediate(mc)}}}
function oc(a,b,c,d,e){function f(){if(g<pc){if(!noExitRuntime)try{qc(Aa)}catch(m){if(!(m instanceof qa))throw m;}return!1}return!0}assert(!ic,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ic=a;rc=d;var g=pc;jc=!1;mc=function(){if(!za)if(0<sc.length){var m=Date.now(),n=sc.shift();n.Wf(n.bf);if(tc){var q=tc,t=0==q%1?q-1:Math.floor(q);tc=n.qg?t:(8*q+(t+.5))/
9}console.log('main loop blocker "'+n.name+'" took '+(Date.now()-m)+" ms");h.setStatus&&(m=h.statusMessage||"Please wait...",n=tc,q=uc.sg,n?n<q?h.setStatus(m+" ("+(q-n)+"/"+q+")"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(mc,0)}else f()&&(vc=vc+1|0,1==fc&&1<hc&&0!=vc%hc?kc():(0==fc&&(lc=dc()),za||h.preMainLoop&&!1===h.preMainLoop()||(wc(a),h.postMainLoop&&h.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.fg&&SDL.audio.fg(),kc())))};e||(b&&0<b?ec(0,1E3/b):ec(1,1),kc());if(c)throw"unwind";
}function wc(a){if(!za)try{a()}catch(b){if(!(b instanceof qa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&p("exception thrown: "+[b,b.stack]),b;}}var jc=!1,kc=null,pc=0,ic=null,rc=0,fc=0,hc=0,vc=0,sc=[],uc={},lc,mc,tc,xc=!1,yc=!1,zc=[];
function Ac(){function a(){yc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Bc){Bc=!0;try{Cc=!0}catch(c){Cc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Dc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Cc?null:console.log("warning: no BlobBuilder");
Ec="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Jf||"undefined"!==typeof Ec||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Jf=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Jf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Cc)try{g=new Blob([c],{type:Fc(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Fc(d)}))}catch(q){sa("Blob constructor present but fails: "+
q+"; falling back to blob builder")}g||(g=new Dc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=Ec.createObjectURL(g),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=q;Ec.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.yg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(A){n||(n=!0,h.preloadedAudios[d]=A,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(Cc){try{var q=new Blob([c],{type:Fc(d)})}catch(A){return m()}q=Ec.createObjectURL(q);var t=new Audio;t.addEventListener("canplaythrough",function(){g(t)},!1);t.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var A="",F=0,z=0,
P=0;P<c.length;P++)for(F=F<<8|c[P],z+=8;6<=z;){var Q=F>>z-6&63;z-=6;A+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Q]}2==z?(A+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(F&3)<<4],A+="=="):4==z&&(A+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(F&15)<<2],A+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+A;g(t)}};t.src=q;Gc(function(){g(t)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!yc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Hc(a,b,c,d){if(b&&h.Le&&a==h.canvas)return h.Le;var e;if(b){var f={antialias:!1,alpha:!1,Ff:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof Ic&&(e=Jc(a,f)))var m=J[e].Te}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof K,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.Le=m,b&&Kc(e),h.kg=b,zc.forEach(function(n){n()}),Ac());return m}var Lc=!1,Mc=void 0,Nc=void 0;
function Oc(a,b){function c(){xc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Pc,Mc&&d.requestPointerLock(),xc=!0,Nc?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=Ka[SDL.screen>>2]|8388608),Qc(h.canvas),Rc()):Qc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Nc?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=Ka[SDL.screen>>2]&
-8388609),Qc(h.canvas),Rc()):Qc(d));if(h.onFullScreen)h.onFullScreen(xc);if(h.onFullscreen)h.onFullscreen(xc)}Mc=a;Nc=b;"undefined"===typeof Mc&&(Mc=!0);"undefined"===typeof Nc&&(Nc=!1);var d=h.canvas;Lc||(Lc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Pc(){if(!xc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Sc=0;function nc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Sc)Sc=b+1E3/60;else for(;b+2>=Sc;)Sc+=1E3/60;setTimeout(a,Math.max(Sc-b,0))}}function Gc(a){setTimeout(function(){wc(a)},1E4)}
function Fc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Tc=[];function Rc(){var a=h.canvas;Tc.forEach(function(b){b(a.width,a.height)})}
function Qc(a,b,c){b&&c?(a.lg=b,a.Yf=c):(b=a.lg,c=a.Yf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Nc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Bc,Cc,Dc,Ec,L=12288,Uc=!1,Vc=0,Wc=0,Xc=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Yc={},Zc;function $c(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function ad(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function bd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var cd=1,dd=[],N=[],ed=[],fd=[],O=[],R=[],gd=[],J=[],S=[],hd={},jd=4;
function T(a){kd||(kd=a)}function ld(a){for(var b=cd++,c=a.length;c<b;c++)a[c]=null;return b}function md(a,b,c){for(var d="",e=0;e<a;++e){var f=c?u[c+4*e>>2]:-1;d+=y(u[b+4*e>>2],0>f?void 0:f)}return d}function Jc(a,b){a.Cf||(a.Cf=a.getContext,a.getContext=function(d,e){e=a.Cf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?nd(c,b):0}
function nd(a,b){var c=ld(J),d={ug:c,attributes:b,version:b.Ff,Te:a};a.canvas&&(a.canvas.Ze=d);J[c]=d;("undefined"===typeof b.Tf||b.Tf)&&od(d);return c}function Kc(a){pd=J[a];h.Le=K=pd&&pd.Te}function od(a){a||(a=pd);if(!a.$f){a.$f=!0;var b=a.Te;$c(b);ad(b);bd(b);b.Je=b.getExtension("EXT_disjoint_timer_query");b.xg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ic={},kd,pd,qd=[],rd=0;
function sd(){for(var a=U.length-1;0<=a;--a)td(a);U=[];V=[]}var V=[];function ud(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in V){var f=V[e];if(f.sf==a&&d(f.uf,c))return}V.push({sf:a,Kf:b,uf:c});V.sort(function(g,m){return g.Kf<m.Kf})}function vd(a){for(var b=0;b<V.length;++b)V[b].sf==a&&(V.splice(b,1),--b)}function wd(){if(rd&&xd.Ve)for(var a=0;a<V.length;++a){var b=V[a];V.splice(a,1);--a;b.sf.apply(null,b.uf)}}var U=[];
function td(a){var b=U[a];b.target.removeEventListener(b.Fe,b.Uf,b.He);U.splice(a,1)}function W(a){function b(d){++rd;xd=a;wd();a.Ke(d);wd();--rd}if(a.Ie)a.Uf=b,a.target.addEventListener(a.Fe,b,a.He),U.push(a),yd||(Pa.push(sd),yd=!0);else for(var c=0;c<U.length;++c)U[c].target==a.target&&U[c].Fe==a.Fe&&td(c--)}function zd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Ad(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Bd={},yd,xd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od={},Pd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function X(a){a=2<a?y(a):a;return Pd[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function Qd(a){var b=Rd(),c=Ha(8),d=c+4,e=Ha(a.id.length+1);C(a.id,e,a.id.length+1);if(a=X(e))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Sd(b);return c}function Td(a,b,c){a=X(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Ud(a,b,c){if(a.pg){var d=Rd(),e=Ha(a.id.length+1);C(a.id,e,a.id.length+1);Td(e,b,c);Sd(d)}else a.width=b,a.height=c}
function Vd(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ud(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=t,a.style.paddingTop=A,a.style.paddingBottom=F,a.style.marginLeft=z,a.style.marginRight=
P,a.style.marginTop=Q,a.style.marginBottom=ab,document.body.style.margin=De,document.documentElement.style.overflow=Ee,document.body.scroll=Fe,a.style.Ef=Ge,a.Ze&&a.Ze.Te.viewport(0,0,d,e),Od.cf&&E.get(Od.cf)(37,0,Od.vf))}var c=Qd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,t=a.style.paddingRight,A=a.style.paddingTop,F=a.style.paddingBottom,z=a.style.marginLeft,P=a.style.marginRight,Q=a.style.marginTop,ab=
a.style.marginBottom,De=document.body.style.margin,Ee=document.documentElement.style.overflow,Fe=document.body.scroll,Ge=a.style.Ef;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Wd(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Xd(a){return 0>Pd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Yd(a,b){if(0!=b.rf||0!=b.lf){Vd(a);var c=b.ig?innerWidth:screen.width,d=b.ig?innerHeight:screen.height,e=Xd(a),f=e.width;e=e.height;var g=Qd(a),m=g[0];g=g[1];3==b.rf?(Wd(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.rf&&(c*g<m*d?(f=g*c/m,Wd(a,(d-f)/2,0),d=f):(f=m*d/g,Wd(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Vf&&(a.style.Ef="pixelated");
f=2==b.lf?devicePixelRatio:1;0!=b.lf&&(c=c*f|0,d=d*f|0,Ud(a,c,d),a.Ze&&a.Ze.Te.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Ad()?-3:-1;Od=b;b.cf&&E.get(b.cf)(37,0,b.vf);return 0}function Zd(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.gf)a.gf();else return document.body.requestPointerLock||document.body.gf?-3:-1;return 0}
function $d(a,b){x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)u[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];u[a+1296>>2]=b.connected;u[a+1300>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;C(b.id,a+1304,64);C(b.mapping,a+1368,64)}var ae=[];
function be(a,b,c,d){for(var e=0;e<a;e++){var f=K[c](),g=f&&ld(d);f?(f.name=g,d[g]=f):T(1282);u[b+4*e>>2]=g}}function ce(a,b,c,d,e,f,g,m){b=N[b];if(a=K[a](b,c))d=m&&C(a.name,m,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)}function de(a,b){Ka[a>>2]=b;Ka[a+4>>2]=(b-Ka[a>>2])/4294967296}
function ee(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:r[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);p("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);p("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:de(b,
d);break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:r[b>>0]=d?1:0}}else T(1281)}function fe(a){var b=Ea(a)+1,c=D(b);C(a,c,b);return c}function ge(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function he(a){var b=a.Xe,c=a.kf,d;if(!b)for(a.Xe=b={},a.Mf={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var f=e.name;e=e.size;var g=ge(f);g=0<g?f.slice(0,g):f;var m=a.jf;a.jf+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Mf[m++]=g}}
function Y(a){var b=K.yf;if(b){var c=b.Xe[a];"number"===typeof c&&(b.Xe[a]=c=K.getUniformLocation(b,b.Mf[a]+(0<c?"["+c+"]":"")));return c}T(1282)}function ie(a,b,c,d){if(c)if(a=N[a],he(a),a=K.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else T(1281)}
function je(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else T(1281)}
function ke(a,b,c,d,e){a-=5120;a=1==a?B:4==a?u:6==a?w:5==a||28922==a?Ka:Ja;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=jd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var le=[],me=[];function ne(a,b){if(!Ad())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?rd&&xd.Ve?Yd(a,b):b.Sf?(ud(Yd,1,[a,b]),1):-2:-3:-4}
function oe(a,b){var c={target:X(2),Fe:"beforeunload",Ie:b,Ke:function(d){d=d||event;var e=E.get(b)(28,0,a);e&&(e=y(e));if(e)return d.preventDefault(),d.returnValue=e},He:!0};W(c)}function pe(a,b,c,d,e,f){Dd||(Dd=D(256));a={target:X(a),Fe:f,Ie:d,Ke:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Dd;C(zd(g.target),n+0,128);C(m,n+128,128);E.get(d)(e,n,b)&&g.preventDefault()},He:c};W(a)}
function qe(a,b,c,d,e){Fd||(Fd=D(280));W({target:a,Fe:e,Ie:d,Ke:function(f){f=f||event;var g=Fd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;u[g>>2]=n;u[g+4>>2]=Ad();var q=n?m:Ed,t=q&&q.id?q.id:"";C(zd(q),g+8,128);C(t,g+136,128);u[g+264>>2]=q?q.clientWidth:0;u[g+268>>2]=q?q.clientHeight:0;u[g+272>>2]=screen.width;u[g+276>>2]=screen.height;n&&(Ed=m);E.get(d)(19,g,b)&&f.preventDefault()},He:c})}
function re(a,b,c,d,e){Gd||(Gd=D(1432));b={target:X(2),Ve:!0,Fe:e,Ie:c,Ke:function(f){f=f||event;var g=Gd;$d(g,f.gamepad);E.get(c)(d,g,a)&&f.preventDefault()},He:b};W(b)}
function se(a,b,c,d,e,f){Hd||(Hd=D(164));a={target:X(a),Ve:!0,Fe:f,Ie:d,Ke:function(g){var m=Hd,n=m>>2;u[n]=g.location;u[n+1]=g.ctrlKey;u[n+2]=g.shiftKey;u[n+3]=g.altKey;u[n+4]=g.metaKey;u[n+5]=g.repeat;u[n+6]=g.charCode;u[n+7]=g.keyCode;u[n+8]=g.which;C(g.key||"",m+36,32);C(g.code||"",m+68,32);C(g.char||"",m+100,32);C(g.locale||"",m+132,32);E.get(d)(e,m,b)&&g.preventDefault()},He:c};W(a)}
function te(a,b,c){a>>=2;u[a]=b.screenX;u[a+1]=b.screenY;u[a+2]=b.clientX;u[a+3]=b.clientY;u[a+4]=b.ctrlKey;u[a+5]=b.shiftKey;u[a+6]=b.altKey;u[a+7]=b.metaKey;wa[2*a+16]=b.button;wa[2*a+17]=b.buttons;u[a+9]=b.movementX;u[a+10]=b.movementY;c=Xd(c);u[a+11]=b.clientX-c.left;u[a+12]=b.clientY-c.top}function ue(a,b,c,d,e,f){Id||(Id=D(64));a=X(a);W({target:a,Ve:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Fe:f,Ie:d,Ke:function(g){g=g||event;te(Id,g,a);E.get(d)(e,Id,b)&&g.preventDefault()},He:c})}
function ve(a,b,c,d,e){Jd||(Jd=D(260));W({target:a,Fe:e,Ie:d,Ke:function(f){f=f||event;var g=Jd,m=document.pointerLockElement||document.Nf||document.ng||document.mg;u[g>>2]=!!m;var n=m&&m.id?m.id:"";C(zd(m),g+4,128);C(n,g+132,128);E.get(d)(20,g,b)&&f.preventDefault()},He:c})}
function we(a,b,c,d){Kd||(Kd=D(36));a=X(a);W({target:a,Fe:"resize",Ie:d,Ke:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=Kd;u[g>>2]=e.detail;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset;u[g+32>>2]=pageYOffset;E.get(d)(10,g,b)&&e.preventDefault()}}},He:c})}
function xe(a,b,c,d,e,f){Ld||(Ld=D(1684));a=X(a);W({target:a,Ve:"touchstart"==f||"touchend"==f,Fe:f,Ie:d,Ke:function(g){for(var m={},n=g.touches,q=0;q<n.length;++q){var t=n[q];m[t.identifier]=t}n=g.changedTouches;for(q=0;q<n.length;++q)t=n[q],t.bg=1,m[t.identifier]=t;n=g.targetTouches;for(q=0;q<n.length;++q)m[n[q].identifier].eg=1;n=Ld;t=n>>2;u[t+1]=g.ctrlKey;u[t+2]=g.shiftKey;u[t+3]=g.altKey;u[t+4]=g.metaKey;t+=5;var A=Xd(a),F=0;for(q in m){var z=m[q];u[t]=z.identifier;u[t+1]=z.screenX;u[t+2]=z.screenY;
u[t+3]=z.clientX;u[t+4]=z.clientY;u[t+5]=z.pageX;u[t+6]=z.pageY;u[t+7]=z.bg;u[t+8]=z.eg;u[t+9]=z.clientX-A.left;u[t+10]=z.clientY-A.top;t+=13;if(31<++F)break}u[n>>2]=F;E.get(d)(e,n,b)&&g.preventDefault()},He:c})}function ye(a,b,c){var d=Pd[1];Md||(Md=D(8));W({target:d,Fe:"visibilitychange",Ie:c,Ke:function(e){e=e||event;var f=Md,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);u[f>>2]=document.hidden;u[f+4>>2]=g;E.get(c)(21,f,a)&&e.preventDefault()},He:b})}
function ze(a,b,c,d){Nd||(Nd=D(96));W({target:a,Ve:!0,Fe:"wheel",Ie:d,Ke:function(e){e=e||event;var f=Nd;te(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;E.get(d)(9,f,b)&&e.preventDefault()},He:c})}var Ae={};
function Be(){if(!Ce){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ae)void 0===Ae[b]?delete a[b]:a[b]=Ae[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ce=c}return Ce}var Ce;function He(a,b){He.Lf||(He.Lf=ib());for(var c=0;c<b;c++)r[a+c>>0]=He.Lf();return 0}
function Gb(a,b,c,d){a||(a=this);this.parent=a;this.Se=a.Se;this.ff=null;this.id=xb++;this.name=b;this.mode=c;this.Be={};this.Ce={};this.rdev=d}Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Vb();yb=Array(4096);Nb(I,"/");Pb("/tmp");Pb("/home");Pb("/home/web_user");
(function(){Pb("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Qb("/dev/null",259);lb(1280,ob);lb(1536,pb);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);var a=ib();Yb("random",a);Yb("urandom",a);Pb("/dev/shm");Pb("/dev/shm/tmp")})();
(function(){Pb("/proc");var a=Pb("/proc/self");Pb("/proc/self/fd");Nb({Se:function(){var b=rb(a,"fd",16895,73);b.Be={lookup:function(c,d){var e=wb[+d];if(!e)throw new H(8);c={parent:null,Se:{Hf:"fake"},Be:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();h.requestFullscreen=function(a,b){Oc(a,b)};h.requestAnimationFrame=function(a){nc(a)};h.setCanvasSize=function(a,b,c){Qc(h.canvas,a,b);c||Rc()};h.pauseMainLoop=function(){kc=null;pc++};
h.resumeMainLoop=function(){pc++;var a=fc,b=hc,c=ic;ic=null;oc(c,0,!1,rc,!0);ec(a,b);kc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Hc(a,b,c,d)};for(var K,Z=0;32>Z;++Z)ae.push(Array(Z));var Ie=new Float32Array(288);for(Z=0;288>Z;++Z)le[Z]=Ie.subarray(0,Z+1);var Je=new Int32Array(288);for(Z=0;288>Z;++Z)me[Z]=Je.subarray(0,Z+1);
var Le={a:function(a,b,c,d){l("Assertion failed: "+y(a)+", at: "+[b?y(b):"unknown filename",c,d?y(d):"unknown function"])},ha:function(a,b,c){ac=c;try{var d=cc(a);switch(b){case 0:var e=bc();return 0>e?-28:Sb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=bc(),d.flags|=e,0;case 12:return e=bc(),wa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return u[Ke()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof $b&&f instanceof H||
l(f),-f.Oe}},fb:function(a,b,c){ac=c;try{var d=cc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=bc();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=bc();if(!d.Ce.ag)throw new H(59);return d.Ce.ag(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:l("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof $b&&f instanceof H||
l(f),-f.Oe}},gb:function(a,b,c){ac=c;try{var d=y(a),e=c?bc():0;return Sb(d,b,e).fd}catch(f){return"undefined"!==typeof $b&&f instanceof H||l(f),-f.Oe}},ta:function(){l()},i:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=dc();else return u[Ke()>>2]=28,-1;u[b>>2]=a/1E3|0;u[b+4>>2]=a%1E3*1E6|0;return 0},ra:function(){l("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},za:function(a){if(12448==a)return L=12288,1;
L=12300;return 0},La:function(a,b,c,d,e){if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)M.alpha=0<u[b+4>>2];else if(12325==a)M.depth=0<u[b+4>>2];else if(12326==a)M.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],M.antialias=0<a;else if(12338==a)a=u[b+4>>2],M.antialias=1==a;else if(12544==a)M.vg=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(u[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},Ja:function(a,b,c,d){if(62E3!=a)return L=12296,0;for(a=1;;){b=
u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Ff=a-1;M.wg=0;Zc=Jc(h.canvas,M);if(0!=Zc)return L=12288,Kc(Zc),h.kg=!0,zc.forEach(function(e){e()}),Kc(null),62004;L=12297;return 0},Ha:function(a,b){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},Ia:function(a,b){if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=Zc;pd===J[a]&&(pd=null);if("object"===typeof Bd)for(var c=J[a].Te.canvas,d=0;d<U.length;++d)U[d].target!=
c||td(d--);J[a]&&J[a].Te.canvas&&(J[a].Te.canvas.Ze=void 0);J[a]=null;L=12288;Vc==b&&(Vc=0);return 1},Ga:function(a,b){if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Wc==b&&(Wc=0);Xc==b&&(Xc=0);L=12288;return 1},Ka:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return u[d>>2]=M.alpha?32:24,1;case 12321:return u[d>>2]=M.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>
2]=8,1;case 12325:return u[d>>2]=M.depth?24:0,1;case 12326:return u[d>>2]=M.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=M.antialias?4:0,1;case 12338:return u[d>>2]=M.antialias?1:0,1;case 12339:return u[d>>2]=4,
1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return L=12292,0}},V:function(){L=12288;return 62E3},xa:function(){return L},Na:function(a,b,c){if(62E3==a)return b&&(u[b>>2]=1),c&&(u[c>>2]=4),Uc=!0,L=12288,1;L=12296;return 0},
Fa:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;Kc(d?Zc:null);Vc=d;Xc=b;Wc=c;L=12288;return 1},ya:function(a,b){if(62E3!=a)return L=12296,0;L=12288;if(Yc[b])return Yc[b];switch(b){case 12371:a=Fa("Emscripten");break;case 12372:a=Fa("1.4 Emscripten EGL");break;case 12373:a=Fa("");break;case 12429:a=Fa("OpenGL_ES");break;default:return L=12300,0}return Yc[b]=a},Ea:function(){if(Uc)if(h.Le)if(h.Le.isContextLost())L=
12302;else return L=12288,1;else L=12290;else L=12289;return 0},Da:function(a,b){if(62E3!=a)return L=12296,0;0==b?ec(0,0):ec(1,b);L=12288;return 1},Ma:function(a){if(62E3!=a)return L=12296,0;Xc=Wc=Vc=0;Uc=!1;L=12288;return 1},Aa:function(){L=12288;return 1},Ca:function(){L=12288;return 1},b:function(a,b,c){qd.length=0;var d;for(c>>=2;d=B[b++];)(d=105>d)&&c&1&&c++,qd.push(d?x[c++>>1]:u[c]),++c;return bb[a].apply(null,qd)},Qa:function(){kc=null;pc++;ic=null},me:function(){if(!Ad())return-1;vd(Yd);var a=
Pd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},wa:function(){vd(Zd);if(document.exitPointerLock)document.exitPointerLock();else if(document.af)document.af();else return-1;return 0},m:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},g:function(a,b,c){a=X(a);if(!a)return-4;a=Xd(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},pa:function(a,b){if(0>a||a>=
Cd.length)return-5;if(!Cd[a])return-7;$d(b,Cd[a]);return 0},le:function(){return Cd.length},Td:function(a){K.activeTexture(a)},Rd:function(a,b){K.attachShader(N[a],R[b])},he:function(a,b){K.Je.beginQueryEXT(a,S[b])},Qd:function(a,b,c){K.bindAttribLocation(N[a],b,y(c))},Pd:function(a,b){K.bindBuffer(a,dd[b])},Od:function(a,b){K.bindFramebuffer(a,ed[b])},Nd:function(a,b){K.bindRenderbuffer(a,fd[b])},Md:function(a,b){K.bindTexture(a,O[b])},$d:function(a){K.bindVertexArray(gd[a])},Ld:function(a,b,c,d){K.blendColor(a,
b,c,d)},Kd:function(a){K.blendEquation(a)},Jd:function(a,b){K.blendEquationSeparate(a,b)},Id:function(a,b){K.blendFunc(a,b)},Hd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Gd:function(a,b,c,d){K.bufferData(a,c?B.subarray(c,c+b):b,d)},Fd:function(a,b,c,d){K.bufferSubData(a,b,B.subarray(d,d+c))},Ed:function(a){return K.checkFramebufferStatus(a)},Dd:function(a){K.clear(a)},Cd:function(a,b,c,d){K.clearColor(a,b,c,d)},Bd:function(a){K.clearDepth(a)},Ad:function(a){K.clearStencil(a)},zd:function(a,
b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},yd:function(a){K.compileShader(R[a])},xd:function(a,b,c,d,e,f,g,m){K.compressedTexImage2D(a,b,c,d,e,f,m?B.subarray(m,m+g):null)},wd:function(a,b,c,d,e,f,g,m,n){K.compressedTexSubImage2D(a,b,c,d,e,f,g,n?B.subarray(n,n+m):null)},vd:function(a,b,c,d,e,f,g,m){K.copyTexImage2D(a,b,c,d,e,f,g,m)},ud:function(a,b,c,d,e,f,g,m){K.copyTexSubImage2D(a,b,c,d,e,f,g,m)},td:function(){var a=ld(N),b=K.createProgram();b.name=a;b.Re=b.Pe=b.Qe=0;b.jf=1;N[a]=b;return a},sd:function(a){var b=
ld(R);R[b]=K.createShader(a);return b},rd:function(a){K.cullFace(a)},qd:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=dd[d];e&&(K.deleteBuffer(e),e.name=0,dd[d]=null)}},pd:function(a,b){for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=ed[d];e&&(K.deleteFramebuffer(e),e.name=0,ed[d]=null)}},od:function(a){if(a){var b=N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):T(1281)}},je:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(K.Je.deleteQueryEXT(e),S[d]=null)}},nd:function(a,b){for(var c=
0;c<a;c++){var d=u[b+4*c>>2],e=fd[d];e&&(K.deleteRenderbuffer(e),e.name=0,fd[d]=null)}},md:function(a){if(a){var b=R[a];b?(K.deleteShader(b),R[a]=null):T(1281)}},ld:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=O[d];e&&(K.deleteTexture(e),e.name=0,O[d]=null)}},_d:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];K.deleteVertexArray(gd[d]);gd[d]=null}},kd:function(a){K.depthFunc(a)},jd:function(a){K.depthMask(!!a)},id:function(a,b){K.depthRange(a,b)},hd:function(a,b){K.detachShader(N[a],
R[b])},gd:function(a){K.disable(a)},fd:function(a){K.disableVertexAttribArray(a)},ed:function(a,b,c){K.drawArrays(a,b,c)},Wd:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Xd:function(a,b){for(var c=ae[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];K.drawBuffers(c)},dd:function(a,b,c,d){K.drawElements(a,b,c,d)},Vd:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},cd:function(a){K.enable(a)},bd:function(a){K.enableVertexAttribArray(a)},ge:function(a){K.Je.endQueryEXT(a)},ad:function(){K.finish()},$c:function(){K.flush()},
_c:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,fd[d])},Zc:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,O[d],e)},Yc:function(a){K.frontFace(a)},Xc:function(a,b){be(a,b,"createBuffer",dd)},Vc:function(a,b){be(a,b,"createFramebuffer",ed)},ke:function(a,b){for(var c=0;c<a;c++){var d=K.Je.createQueryEXT();if(!d){for(T(1282);c<a;)u[b+4*c++>>2]=0;break}var e=ld(S);d.name=e;S[e]=d;u[b+4*c>>2]=e}},Uc:function(a,b){be(a,b,"createRenderbuffer",fd)},Tc:function(a,b){be(a,b,"createTexture",O)},Zd:function(a,
b){be(a,b,"createVertexArray",gd)},Wc:function(a){K.generateMipmap(a)},Sc:function(a,b,c,d,e,f,g){ce("getActiveAttrib",a,b,c,d,e,f,g)},Rc:function(a,b,c,d,e,f,g){ce("getActiveUniform",a,b,c,d,e,f,g)},Qc:function(a,b,c,d){a=K.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=R.indexOf(a[b])},Pc:function(a,b){return K.getAttribLocation(N[a],y(b))},Oc:function(a,b){ee(a,b,4)},Nc:function(a,b,c){c?u[c>>2]=K.getBufferParameter(a,b):T(1281)},Mc:function(){var a=K.getError()||
kd;kd=0;return a},Kc:function(a,b){ee(a,b,2)},Jc:function(a,b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Ic:function(a,b){ee(a,b,0)},Gc:function(a,b,c,d){a=K.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(u[c>>2]=b)},Hc:function(a,b,c){if(c)if(a>=cd)T(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Re)for(b=
0;b<K.getProgramParameter(a,35718);++b)a.Re=Math.max(a.Re,K.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Re}else if(35722==b){if(!a.Pe)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Pe=Math.max(a.Pe,K.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Pe}else if(35381==b){if(!a.Qe)for(b=0;b<K.getProgramParameter(a,35382);++b)a.Qe=Math.max(a.Qe,K.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Qe}else u[c>>2]=K.getProgramParameter(a,b);else T(1281)},be:function(a,b,c){if(c){a=K.Je.getQueryObjectEXT(S[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;de(c,d)}else T(1281)},de:function(a,b,c){if(c){a=K.Je.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T(1281)},ae:function(a,b,c){if(c){a=K.Je.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;de(c,d)}else T(1281)},ce:function(a,b,c){if(c){a=K.Je.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T(1281)},ee:function(a,b,c){c?u[c>>2]=K.Je.getQueryEXT(a,b):T(1281)},Fc:function(a,b,c){c?
u[c>>2]=K.getRenderbufferParameter(a,b):T(1281)},Dc:function(a,b,c,d){a=K.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(u[c>>2]=b)},Cc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},Bc:function(a,b,c,d){if(a=K.getShaderSource(R[a]))b=0<b&&d?C(a,d,b):0,c&&(u[c>>2]=b)},Ec:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(R[a]),
u[c>>2]=a?a.length+1:0):u[c>>2]=K.getShaderParameter(R[a],b):T(1281)},Ac:function(a){var b=hd[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=fe(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||T(1280);b=b&&fe(b);break;case 7938:b=fe("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=fe(b);break;default:T(1280)}hd[a]=b}return b},zc:function(a,b,c){c?w[c>>2]=K.getTexParameter(a,b):T(1281)},yc:function(a,b,c){c?u[c>>2]=K.getTexParameter(a,b):T(1281)},vc:function(a,b){b=y(b);if(a=N[a]){he(a);var c=a.Xe,d=0,e=b,f=ge(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.kf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else T(1281);return-1},xc:function(a,b,c){ie(a,b,c,2)},wc:function(a,b,c){ie(a,b,
c,0)},sc:function(a,b,c){c?u[c>>2]=K.getVertexAttribOffset(a,b):T(1281)},uc:function(a,b,c){je(a,b,c,2)},tc:function(a,b,c){je(a,b,c,5)},rc:function(a,b){K.hint(a,b)},qc:function(a){return(a=dd[a])?K.isBuffer(a):0},pc:function(a){return K.isEnabled(a)},oc:function(a){return(a=ed[a])?K.isFramebuffer(a):0},nc:function(a){return(a=N[a])?K.isProgram(a):0},ie:function(a){return(a=S[a])?K.Je.isQueryEXT(a):0},mc:function(a){return(a=fd[a])?K.isRenderbuffer(a):0},lc:function(a){return(a=R[a])?K.isShader(a):
0},kc:function(a){return(a=O[a])?K.isTexture(a):0},Yd:function(a){return(a=gd[a])?K.isVertexArray(a):0},jc:function(a){K.lineWidth(a)},ic:function(a){a=N[a];K.linkProgram(a);a.Xe=0;a.kf={}},hc:function(a,b){3317==a&&(jd=b);K.pixelStorei(a,b)},fc:function(a,b){K.polygonOffset(a,b)},fe:function(a,b){K.Je.queryCounterEXT(S[a],b)},ec:function(a,b,c,d,e,f,g){(g=ke(f,e,c,d,g))?K.readPixels(a,b,c,d,e,f,g):T(1280)},dc:function(){},cc:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},bc:function(a,b){K.sampleCoverage(a,
!!b)},ac:function(a,b,c,d){K.scissor(a,b,c,d)},$b:function(){T(1280)},_b:function(a,b,c,d){b=md(b,c,d);K.shaderSource(R[a],b)},Zb:function(a,b,c){K.stencilFunc(a,b,c)},Yb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Wb:function(a){K.stencilMask(a)},Vb:function(a,b){K.stencilMaskSeparate(a,b)},Ub:function(a,b,c){K.stencilOp(a,b,c)},Tb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Sb:function(a,b,c,d,e,f,g,m,n){K.texImage2D(a,b,c,d,e,f,g,m,n?ke(m,g,d,e,n):null)},Rb:function(a,b,c){K.texParameterf(a,
b,c)},Qb:function(a,b,c){K.texParameterf(a,b,w[c>>2])},Pb:function(a,b,c){K.texParameteri(a,b,c)},Ob:function(a,b,c){K.texParameteri(a,b,u[c>>2])},Nb:function(a,b,c,d,e,f,g,m,n){var q=null;n&&(q=ke(m,g,e,f,n));K.texSubImage2D(a,b,c,d,e,f,g,m,q)},Mb:function(a,b){K.uniform1f(Y(a),b)},Lb:function(a,b,c){if(288>=b)for(var d=le[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);K.uniform1fv(Y(a),d)},Kb:function(a,b){K.uniform1i(Y(a),b)},Jb:function(a,b,c){if(288>=b)for(var d=me[b-1],e=
0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);K.uniform1iv(Y(a),d)},Ib:function(a,b,c){K.uniform2f(Y(a),b,c)},Hb:function(a,b,c){if(144>=b)for(var d=le[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);K.uniform2fv(Y(a),d)},Gb:function(a,b,c){K.uniform2i(Y(a),b,c)},Fb:function(a,b,c){if(144>=b)for(var d=me[2*b-1],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);K.uniform2iv(Y(a),d)},Eb:function(a,b,c,
d){K.uniform3f(Y(a),b,c,d)},Db:function(a,b,c){if(96>=b)for(var d=le[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);K.uniform3fv(Y(a),d)},Cb:function(a,b,c,d){K.uniform3i(Y(a),b,c,d)},Bb:function(a,b,c){if(96>=b)for(var d=me[3*b-1],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);K.uniform3iv(Y(a),d)},Ab:function(a,b,c,d,e){K.uniform4f(Y(a),b,c,d,e)},zb:function(a,
b,c){if(72>=b){var d=le[4*b-1],e=w;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);K.uniform4fv(Y(a),d)},yb:function(a,b,c,d,e){K.uniform4i(Y(a),b,c,d,e)},xb:function(a,b,c){if(72>=b)for(var d=me[4*b-1],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);K.uniform4iv(Y(a),d)},wb:function(a,b,c,d){if(72>=b)for(var e=le[4*b-1],f=0;f<4*b;f+=
4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2];else e=w.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(Y(a),!!c,e)},vb:function(a,b,c,d){if(32>=b)for(var e=le[9*b-1],f=0;f<9*b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2];else e=w.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(Y(a),!!c,e)},ub:function(a,
b,c,d){if(18>=b){var e=le[16*b-1],f=w;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(Y(a),!!c,e)},tb:function(a){a=N[a];K.useProgram(a);K.yf=a},sb:function(a){K.validateProgram(N[a])},rb:function(a,b){K.vertexAttrib1f(a,
b)},qb:function(a,b){K.vertexAttrib1f(a,w[b>>2])},pb:function(a,b,c){K.vertexAttrib2f(a,b,c)},ob:function(a,b){K.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},nb:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},mb:function(a,b){K.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},lb:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},kb:function(a,b){K.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Ud:function(a,b){K.vertexAttribDivisor(a,b)},jb:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},
hb:function(a,b,c,d){K.viewport(a,b,c,d)},u:function(){return 0},ne:function(a,b,c){return ne(a,{rf:u[c>>2],lf:u[c+4>>2],Vf:u[c+8>>2],Sf:b,cf:u[c+12>>2],vf:u[c+16>>2]})},U:function(a,b){a=X(a);return a?a.requestPointerLock||a.gf?rd&&xd.Ve?Zd(a):b?(ud(Zd,2,[a]),1):-2:-1:-4},y:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ya.grow(Math.min(2147483648,d)-Ia.byteLength+65535>>>
16);La();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},qa:function(){return(Cd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},A:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;oe(a,b);return 0},M:function(a,b,c,d){pe(a,b,c,d,12,"blur");return 0},k:Td,r:function(a,b,c){a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},N:function(a,b,c,d){pe(a,b,c,d,13,"focus");
return 0},D:function(a,b,c,d){if(!Ad())return-1;a=X(a);if(!a)return-4;qe(a,b,c,d,"fullscreenchange");qe(a,b,c,d,"webkitfullscreenchange");return 0},q:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;re(a,b,c,26,"gamepadconnected");return 0},p:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;re(a,b,c,27,"gamepaddisconnected");return 0},G:function(a,b,c,d){se(a,b,c,d,2,"keydown");return 0},E:function(a,b,c,d){se(a,b,c,d,1,"keypress");return 0},
F:function(a,b,c,d){se(a,b,c,d,3,"keyup");return 0},Wa:function(a,b,c){a=E.get(a);oc(a,b,c)},S:function(a,b,c,d){ue(a,b,c,d,5,"mousedown");return 0},Q:function(a,b,c,d){ue(a,b,c,d,33,"mouseenter");return 0},P:function(a,b,c,d){ue(a,b,c,d,34,"mouseleave");return 0},T:function(a,b,c,d){ue(a,b,c,d,8,"mousemove");return 0},R:function(a,b,c,d){ue(a,b,c,d,6,"mouseup");return 0},H:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.af||document.body.Nf||document.body.gf))return-1;
a=X(a);if(!a)return-4;ve(a,b,c,d,"pointerlockchange");ve(a,b,c,d,"mozpointerlockchange");ve(a,b,c,d,"webkitpointerlockchange");ve(a,b,c,d,"mspointerlockchange");return 0},C:function(a,b,c,d){we(a,b,c,d);return 0},I:function(a,b,c,d){xe(a,b,c,d,25,"touchcancel");return 0},K:function(a,b,c,d){xe(a,b,c,d,23,"touchend");return 0},J:function(a,b,c,d){xe(a,b,c,d,24,"touchmove");return 0},L:function(a,b,c,d){xe(a,b,c,d,22,"touchstart");return 0},B:function(a,b,c){if(!Pd[1])return-4;ye(a,b,c);return 0},O:function(a,
b,c,d){a=X(a);return"undefined"!==typeof a.onwheel?(ze(a,b,c,d),0):-1},t:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},cb:function(a){for(var b=dc();dc()-b<a;);},ab:function(a,b){try{var c=0;Be().forEach(function(d,e){var f=b+c;e=u[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++>>0]=d.charCodeAt(f);r[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof $b&&d instanceof H||l(d),d.Oe}},bb:function(a,b){try{var c=
Be();u[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});u[b>>2]=d;return 0}catch(e){return"undefined"!==typeof $b&&e instanceof H||l(e),e.Oe}},ia:function(a){try{var b=cc(a);if(null===b.fd)throw new H(8);b.nf&&(b.nf=null);try{b.Ce.close&&b.Ce.close(b)}catch(c){throw c;}finally{wb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof $b&&c instanceof H||l(c),c.Oe}},eb:function(a,b,c,d){try{a:{for(var e=cc(a),f=a=0;f<c;f++){var g=u[b+(8*f+4)>>2],m=e,n=u[b+8*f>>2],q=g,t=void 0,
A=r;if(0>q||0>t)throw new H(28);if(null===m.fd)throw new H(8);if(1===(m.flags&2097155))throw new H(8);if(16384===(m.node.mode&61440))throw new H(31);if(!m.Ce.read)throw new H(28);var F="undefined"!==typeof t;if(!F)t=m.position;else if(!m.seekable)throw new H(70);var z=m.Ce.read(m,A,n,q,t);F||(m.position+=z);var P=z;if(0>P){var Q=-1;break a}a+=P;if(P<g)break}Q=a}u[d>>2]=Q;return 0}catch(ab){return"undefined"!==typeof $b&&ab instanceof H||l(ab),ab.Oe}},_a:function(a,b,c,d,e){try{var f=cc(a);a=4294967296*
c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Ub(f,a,d);xa=[f.position>>>0,(v=f.position,1<=+Math.abs(v)?0<v?(Math.min(+Math.floor(v/4294967296),4294967295)|0)>>>0:~~+Math.ceil((v-+(~~v>>>0))/4294967296)>>>0:0)];u[e>>2]=xa[0];u[e+4>>2]=xa[1];f.nf&&0===a&&0===d&&(f.nf=null);return 0}catch(g){return"undefined"!==typeof $b&&g instanceof H||l(g),g.Oe}},db:function(a,b,c,d){try{a:{for(var e=cc(a),f=a=0;f<c;f++){var g=e,m=u[b+8*f>>2],n=u[b+(8*f+4)>>2],q=void 0,t=r;if(0>n||0>q)throw new H(28);
if(null===g.fd)throw new H(8);if(0===(g.flags&2097155))throw new H(8);if(16384===(g.node.mode&61440))throw new H(31);if(!g.Ce.write)throw new H(28);g.seekable&&g.flags&1024&&Ub(g,0,2);var A="undefined"!==typeof q;if(!A)q=g.position;else if(!g.seekable)throw new H(70);var F=g.Ce.write(g,t,m,n,q,void 0);A||(g.position+=F);try{if(g.path&&Ab.onWriteToFile)Ab.onWriteToFile(g.path)}catch(Q){p("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+Q.message)}var z=F;if(0>z){var P=-1;break a}a+=
z}P=a}u[d>>2]=P;return 0}catch(Q){return"undefined"!==typeof $b&&Q instanceof H||l(Q),Q.Oe}},$a:He,h:function(a){var b=Date.now();u[a>>2]=b/1E3|0;u[a+4>>2]=b%1E3*1E3|0;return 0},ma:function(a){K.activeTexture(a)},ba:function(a,b){K.attachShader(N[a],R[b])},n:function(a,b){K.bindBuffer(a,dd[b])},j:function(a,b){K.bindTexture(a,O[b])},z:function(a){K.bindVertexArray(gd[a])},Ua:function(a){K.blendEquation(a)},ib:function(a,b){K.blendEquationSeparate(a,b)},Za:function(a,b){K.blendFunc(a,b)},ga:function(a,
b,c,d){K.blendFuncSeparate(a,b,c,d)},la:function(a,b,c,d){K.bufferData(a,c?B.subarray(c,c+b):b,d)},va:function(a){K.clear(a)},Ba:function(a,b,c,d){K.clearColor(a,b,c,d)},ca:function(a){K.compileShader(R[a])},Ya:function(){var a=ld(N),b=K.createProgram();b.name=a;b.Re=b.Pe=b.Qe=0;b.jf=1;N[a]=b;return a},ea:function(a){var b=ld(R);R[b]=K.createShader(a);return b},Y:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=dd[d];e&&(K.deleteBuffer(e),e.name=0,dd[d]=null)}},Va:function(a){if(a){var b=N[a];
b?(K.deleteProgram(b),b.name=0,N[a]=null):T(1281)}},$:function(a){if(a){var b=R[a];b?(K.deleteShader(b),R[a]=null):T(1281)}},na:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=O[d];e&&(K.deleteTexture(e),e.name=0,O[d]=null)}},Xb:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];K.deleteVertexArray(gd[d]);gd[d]=null}},aa:function(a,b){K.detachShader(N[a],R[b])},e:function(a){K.disable(a)},gc:function(a,b,c,d){K.drawElements(a,b,c,d)},f:function(a){K.enable(a)},w:function(a){K.enableVertexAttribArray(a)},
Z:function(a,b){be(a,b,"createBuffer",dd)},sa:function(a,b){be(a,b,"createTexture",O)},Lc:function(a,b){be(a,b,"createVertexArray",gd)},Sd:function(a){K.generateMipmap(a)},x:function(a,b){return K.getAttribLocation(N[a],y(b))},c:function(a,b){ee(a,b,0)},Pa:function(a,b,c,d){a=K.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(u[c>>2]=b)},W:function(a,b,c){if(c)if(a>=cd)T(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+
1;else if(35719==b){if(!a.Re)for(b=0;b<K.getProgramParameter(a,35718);++b)a.Re=Math.max(a.Re,K.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Re}else if(35722==b){if(!a.Pe)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Pe=Math.max(a.Pe,K.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Pe}else if(35381==b){if(!a.Qe)for(b=0;b<K.getProgramParameter(a,35382);++b)a.Qe=Math.max(a.Qe,K.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Qe}else u[c>>2]=K.getProgramParameter(a,b);else T(1281)},Ra:function(a,
b,c,d){a=K.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(u[c>>2]=b)},X:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=K.getShaderParameter(R[a],b):T(1281)},_:function(a,b){b=y(b);if(a=N[a]){he(a);var c=a.Xe,d=0,e=b,f=ge(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.kf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,
b)))return d}else T(1281);return-1},ua:function(a,b){K.hint(a,b)},l:function(a){return K.isEnabled(a)},Xa:function(a){a=N[a];K.linkProgram(a);a.Xe=0;a.kf={}},ka:function(a,b,c,d){K.scissor(a,b,c,d)},da:function(a,b,c,d){b=md(b,c,d);K.shaderSource(R[a],b)},oa:function(a,b,c,d,e,f,g,m,n){K.texImage2D(a,b,c,d,e,f,g,m,n?ke(m,g,d,e,n):null)},o:function(a,b,c){K.texParameteri(a,b,c)},Ta:function(a,b){K.uniform1i(Y(a),b)},Sa:function(a,b,c,d){if(18>=b){var e=le[16*b-1],f=w;d>>=2;for(var g=0;g<16*b;g+=16){var m=
d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(Y(a),!!c,e)},ja:function(a){a=N[a];K.useProgram(a);K.yf=a},v:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},s:function(a,b,c,d){K.viewport(a,b,c,d)},fa:function(){},d:function(){return 0},Oa:function(){return 0}};
(function(){function a(e){h.asm=e.exports;ya=h.asm.oe;La();E=h.asm.we;Na.unshift(h.asm.pe);Sa--;h.monitorRunDependencies&&h.monitorRunDependencies(Sa);0==Sa&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua&&(e=Ua,Ua=null,e()))}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){p("failed to asynchronously prepare wasm: "+f);l(f)})}var d={a:Le};Sa++;h.monitorRunDependencies&&h.monitorRunDependencies(Sa);if(h.instantiateWasm)try{return h.instantiateWasm(d,
a)}catch(e){return p("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ua||"function"!==typeof WebAssembly.instantiateStreaming||Va()||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){p("wasm streaming compile failed: "+f);p("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.pe).apply(null,arguments)};var D=h._malloc=function(){return(D=h._malloc=h.asm.qe).apply(null,arguments)};h._main=function(){return(h._main=h.asm.re).apply(null,arguments)};
var Ke=h.___errno_location=function(){return(Ke=h.___errno_location=h.asm.se).apply(null,arguments)},Rd=h.stackSave=function(){return(Rd=h.stackSave=h.asm.te).apply(null,arguments)},Sd=h.stackRestore=function(){return(Sd=h.stackRestore=h.asm.ue).apply(null,arguments)},Ha=h.stackAlloc=function(){return(Ha=h.stackAlloc=h.asm.ve).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.xe).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.ye).apply(null,arguments)};
h.dynCall_viijiijii=function(){return(h.dynCall_viijiijii=h.asm.ze).apply(null,arguments)};var Me;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ua=function Ne(){Me||Oe();Me||(Ua=Ne)};
function Oe(a){function b(){if(!Me&&(Me=!0,h.calledRun=!0,!za)){h.noFSInit||Wb||(Wb=!0,Vb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Yb("stdin",h.stdin):Rb("/dev/tty","/dev/stdin"),h.stdout?Yb("stdout",null,h.stdout):Rb("/dev/tty","/dev/stdout"),h.stderr?Yb("stderr",null,h.stderr):Rb("/dev/tty1","/dev/stderr"),Sb("/dev/stdin",0),Sb("/dev/stdout",1),Sb("/dev/stderr",1));zb=!1;db(Na);db(Oa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(Pe){var c=a,d=h._main;c=c||[];var e=
c.length+1,f=Ha(4*(e+1));u[f>>2]=Ga(da);for(var g=1;g<e;g++)u[(f>>2)+g]=Ga(c[g-1]);u[(f>>2)+e]=0;try{var m=d(e,f);qc(m,!0)}catch(n){n instanceof qa||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),p("exception thrown: "+c),ea(1,n))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Qa.unshift(c);db(Qa)}}a=a||ca;if(!(0<Sa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ra();
db(Ma);0<Sa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=Oe;function qc(a,b){Aa=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);za=!0}ea(a,new qa(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Pe=!0;h.noInitialRun&&(Pe=!1);Oe();
